### ISSUE TITLE
show progress bar when install a package

### ISSUE THREAD

**Issue by colin3dmax** [atom/settings-view#100]
when I install a package , there is no progress bar ,so I don't know when the package is install success , atom need it.

**Comment by sohrabsaran** [comment]
Please show progress bar with estimated time remaining.

**Comment by JosephTLyons** [comment]
Atom is the best editor on the market now that the performance issues have been addressed, but I can't understand, for the life of me, why the updates (package and Atom itself) have no progress bar.

**Comment by JosephTLyons** [comment]
@zatricky it doesn’t make make much sense to me.  So many specialized features have been developed and maintained, but this continues to go ignored.  Not sure why.

**Comment by Thmyris** [comment]
Its part of the "modern design" that every OS now goes for. Hate it so much.

**Comment by sakhimpungose** [comment]
I've been waiting for a package to download for the past 15 minutes. Should I continue waiting?

A progress bar has multiple uses.
1. It tells the user the status of the proceess e.g download in progress, download failed.

2. It also tells the user how fast the process is going. Without this information the user cannot make a reasonable estimate of when the process is expected to complete.

3. Progress bars have been common thing in the past and most user expect to see one when they are downloading or installing something.
4. Other reasons

**Comment by slavish-coder** [comment]
I just
