### ISSUE TITLE
Can't install certain package

### ISSUE THREAD

**Issue by icetee** [atom/settings-view#1018]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I try install my package https://github.com/icetee/remote-ftp, but can not be installed in Settings view. I do not get any error code that I can debug.
```
Installing package Remote-FTP failed Error: Installing “Remote-FTP@2.0.0” failed.
    at C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\node_modules\settings-view\lib\package-manager.js:547:27
    at exit (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\icetee\.atom\packages\Remote-FTP\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\icetee\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

### Steps to Reproduce

1. Settings View > Install
2. Type remote-ftp
3. Click install button
4. Wait and return error

**Expected behavior:** Error-free installation

**Actual behavior:** Returns the error and does not install the package.

**Reproduces how often:** 100%

### Versions

Windows 10
Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
There is no problem with version 1.22.1.
Installing the command line is perfectly installed. `apm install remote-ftp`
Related of https://github.com/icetee/remote-ftp/issues/1066

**Comment by rsese** [comment]
Thanks for the report - I can confirm the same behavior from `Settings > Install`:

* Installs in 1.22.1.
* Doesn't install in 1.23.1-beta0, same error from issue body
* Installing with `apm install remote-ftp` works

I also noticed:

* Installing with `apm-beta install remote-ftp` works fine
* Installing with `apm-beta install Remote-FTP` fails with the same error from the issue body
* Installing with `apm install Remote-FTP` works 

apm version info:

```
$ apm-beta -v
apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.23.0-beta0
python 2.7.10
git 2.13.5

$ apm -v
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```

**Comment by bhhaskin** [comment]
Same issue.

`apm install zen`

`Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
`
`$ apm -v
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.0
python 2.7.14
git 2.14.1`

**Comment by rsese** [comment]
@maxbrunsfeld we talked about this one last week and someone mentioned you might have some insight into this?  Possibly related to case sensitivity and package names?  I might be mis-remembering though so let me know if this doesn't ring a bell and I can see if anyone else can take a look :v:

**Comment by icetee** [comment]
It is acceptable to me if in the future can not be used uppercase letters in the package name.

I found a rule in the NPV documentation:
["New packages must not have uppercase letters in the name."](https://docs.npmjs.com/files/package.json)

- But from now it should be blocked so that it can not be create new packages with uppercase.
- When install it, need to convert package name to lowercase.

**Comment by lgeiger** [comment]
We are seeing similar issues on [Hydrogen](https://github.com/nteract/hydrogen).

Can we just change the package name in `package.json` to lower case without breaking the publishing?

**Comment by damieng** [comment]
Identified cause in apm https://github.com/atom/apm/commit/c9f021038f847376bff53150f1e2b28362b9981b#diff-2c69f8ac15f464ce4b59338eb9300b3fR358 - investigating fix.

**Comment by lgeiger** [comment]
@damieng Thanks for fixing this.

We are getting a lot of issues regarding this since the fix isn't shipped yet: https://github.com/nteract/hydrogen/issues/1137
Is it possible for package authors to just change the package name in `package.json` to lower case without breaking the upgrade for existing users?

**Comment by damieng** [comment]
I'm not sure that will solve the problem. I'll see if we can get the hotfixes pushed out asap.  Unfortunately hit the holiday period.

**Comment by lgeiger** [comment]
> I'll see if we can get the hotfixes pushed out asap. Unfortunately hit the holiday period.

Thanks, no problem!
I think in any case we'll try to rename the package to lowercase via  `apm publish --rename` during the next publish.
