### ISSUE TITLE
Settings view on Windows 8 is blank or the action does not work.

### ISSUE THREAD

**Issue by pscdodd** [atom/settings-view#1022]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The settings view on Windows 8 is blank or the action does not work.

### Steps to Reproduce

1. Open atom with "atom --safe" in a command window
2. Open the settings view from the menu with File -> Settings

**Expected behavior:**

The settings view is shown.

**Actual behavior:**

Nothing happens, the window remains as before i.e. blank

**Reproduces how often:**

Always. I tried with a fresh reinstall, but the result was the same. The loaded packages cannot be disabled as the settings view (see above) is not available.

### Versions
atom --version
Atom    : 1.22.1 (64bit)
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python
git 2.13.0.windows.1
visual studio

OS: Windows 8 Enterprise 64bit

### Additional Information

**Comment by damieng** [comment]
Can you post a screenshot?

**Comment by pscdodd** [comment]
Sorry, no, I have since migrated my PC from Windows 8 to windows 10 Enterprise. The Screenshot would have just shown an empty black window. On Windows 10 Enterprise the Settings view is shown.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by damieng** [comment]
Unable to repro.
