### ISSUE TITLE
Cannot change settings with default value

### ISSUE THREAD

**Issue by arcenik** [atom/settings-view#1028]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [ ] (n/a) Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot change the default value for multiple preference items.
When I select the edit field, the default value is edited (instead of nothing).
Then any change is ignored.

### Steps to Reproduce

1. Open the preferences tab

![bug-atom-001](https://user-images.githubusercontent.com/1905755/33984353-a39c963e-e0b7-11e7-88dc-f5a897a63f7a.png)

2. Click on the edit field to change the value

![bug-atom-002](https://user-images.githubusercontent.com/1905755/33984386-b4c364a6-e0b7-11e7-9112-443b109ff546.png)

**Expected behavior:** For an unset parameter, the field should be empty when you edit it.

**Actual behavior:** The default value is displayed and changes are ignored

**Reproduces how often:** All the time

### Versions

$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
(node:2225) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.18.11
npm  5.6.0
node 9.3.0 x64
atom 1.22.1
python 2.7.14
git 2.15.1

### Additional Information

Running on Archlinux x64

**Comment by 50Wliu** [comment]
Can you please show a GIF of you trying to edit one of the values?

Also, you are running an unofficial Atom distribution, which means that we may not be able to offer support to you.  Please instead download Atom from https://atom.io.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/1028#issuecomment-351679151. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
