### ISSUE TITLE
Cannot view the encoeded base64 image in package READMEs

### ISSUE THREAD

**Issue by yoonhyung** [atom/settings-view#1030]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Previously there was a problem with the relative path, so I used the base64 encoded image in the README file. As a result, the version of Atom version 1.22.1 worked well. However, the base64 encoded image is not visible as it is updated to 1.23.0.

So I checked the source(package-readme.view.js) and found that the sanitize function added a new line that merges the packaged path with the image source.

**Expected behavior:** [What you expect to happen]

it will show the encoeded based64 image in package REAEMEs

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.9.3.windows.1
visual studio 2015

### Additional Information
Before merging an image source with a package relative path, you need to check whether it is base64 as a regular expression in that source.

**Comment by yoonhyung** [comment]
refer to the below code

```
    // if src contains a base64 enconding string then it must be a base64 enconding
    if (/^data:image\/.*;base64/i.test(imageSrc)) {
      changeImageSrc = false;
    }
```

**Comment by maralv** [comment]
The referenced code snippet is not present in /lib/package-readme-view.js, this issue seems to be resolved.

**Comment by maralv** [comment]
> refer to the below code
> 
> in package-readme-view.js
> 
> ```
> function sanitize(...) {
> ...
>     // if src contains a base64 enconding string then it must be a base64 enconding
>     if (/^data:image\/.*;base64/i.test(imageSrc)) {
>       changeImageSrc = false;
>     }
> ...
> }
> ```

The referenced code snippet is not present in the current /lib/package-readme-view.js, the issue seems to be resolved.
