### ISSUE TITLE
Segmentation fault when trying to install packages and themes on Atom

### ISSUE THREAD

**Issue by theAlexandrian** [atom/settings-view#1031]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am not able to install any package nor theme from both the settings view and the terminal. I am getting a **segmentation fault error**. I tried on two different computers, both having a **freshly installed Ubuntu system**, and a **freshly installed Atom**, but I am getting the same result.

### Steps to Reproduce

**Atom**
1. Open atom
2. Open the settings view
3. Go to the install section
4. Iterate clicking on themes then packages, next to the search bar, many times

**Terminal**
1. Open the terminal
2. try installing a random package or theme: `apm install file-icons` for example

**Expected behavior:** Being able to view and install themes and packages.

**Actual behavior:** 

**1. Atom:**
- Whithout trying anything in the settings view, after going to the install section, there is a red band under Featured packages, logging the error:
> Fetching featured packages failed.Hide output…
/snap/atom/109/usr/share/atom/resources/app/apm/bin/apm: line 63:  3566 Segmentation fault      (core dumped) "$binDir/$nodeBin" "$cliPath" "$@"

- After each click on themes or packages, the same error is logged below the previous one.

**2. Terminal:**
- Getting a **Segfault error**:
`/snap/atom/109/usr/bin/apm: line 63: 4322 Segmentation fault (core dumped) "$binDir/$nodeBin" “cliPath" "@”`

**Reproduces how often:** 100%

### Versions

**Atom version**
`atom --version`
> /usr/share/themes/Radiance/gtk-2.0/apps/mate-panel.rc:30:
 error: invalid string constant "murrine-scrollbar", expected valid string constant
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**apm version**
`apm --version` _(Getting the same error)_
> /snap/atom/109/usr/bin/apm: line 63:  4469 Segmentation fault      (core dumped) "$binDir/$nodeBin" "$cliPath" "$@"

**Software informations**
`lsb_release -a`
> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

### Additional Information

- Atom was installed via the Ubuntu software app.
- No other additional information (The issue happens on a *newly installed Atom* on a *newly installed Ubuntu system*)

**Comment by theAlexandrian** [comment]
It seems like there is no problem when installing Atom using the debian package from the [Official website](https://atom.io/). Perhaps it comes from Ubuntu's snap.

**Comment by rsese** [comment]
> It seems like there is no problem when installing Atom using the debian package from the Official website. Perhaps it comes from Ubuntu's snap.

Thanks for confirming that things work ok with the official .deb - the snap install is unofficial and not supported by us so I'll go ahead and close this issue.  If you run into issue with the official .deb, please let us know.

**Comment by sektionschef** [comment]
thanks. that also solved my problem. the *.deb works
