### ISSUE TITLE
Font Issues: Change to Monaco [SOLVED BY MYSELF]

### ISSUE THREAD

**Issue by gspalato** [atom/settings-view#1037]
Well, I already checked a bunch of common questions on atom but, whenever I try to change the font to Monaco (which is one of my favorite fonts) on Atom, it changes to a weird and totally different font..
Also, Monaco isn't available on the _fonts_ package.

Currently I use the lastest atom, on Windows 10. The current theme I use is city-lights-ui.

Here's a screenshot of the font it changes when I write Monaco on the font settings.

![image](https://user-images.githubusercontent.com/3950465/34565996-0baed2ae-f144-11e7-86a1-c786f5f4bfcf.png)

**Comment by 50Wliu** [comment]
Glad you solved it.
