### ISSUE TITLE
Trying to install Julia on Atom

### ISSUE THREAD

**Issue by Mari2061** [atom/settings-view#1038]
My intenet access is with a proxy so I had to install the packege offline ( download it and put it on the packege folder on atom) ( My OS is Windows 10)
When I open Atom this happens
Error: Fetching package 'tool-bar' failed.

When I go to the packege, uber.juno says to be already installed
I´m new to atom and Julia, no idea why this is happening

**Comment by 50Wliu** [comment]
> ( download it and put it on the packege folder on atom)

That's not how you install packages, there's more steps than that and they require working internet access.  For help getting your proxy to work check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
