### ISSUE TITLE
Uncaught TypeError: body.filter is not a function

### ISSUE THREAD

**Issue by ghost** [atom/settings-view#1052]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.254.1

### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At D:\ProgramDevTools\Atom x64\resources\app\node_modules\settings-view\lib\atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (D:/ProgramDevTools/Atom x64/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  2x -4:37.1.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
     -1:54.7.0 core:backspace (input.hidden-input)
     -0:43.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25.1.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.1.0 github:toggle-github-tab (div.github-Panel.is-empty)
```

### Non-Core Packages

```
linter-gcc 0.7.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Saidbek** [comment]
any progress here? having the same error while trying to install a package Atom 1.26.0, Mac OS HS

**Comment by svalgaard** [comment]
Hi
I have the same error on my Mac

[Enter steps to reproduce:]

1. Go to "install packages"
2. Search for any package
3. The error message appars

The error also appears after a restart.
Using ```/Applications/Atom.app/Contents/MacOS/Atom --safe``` does not help

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.254.2


### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  3x -1:38.3.0 core:backspace (input.hidden-input)
  2x -1:36.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by jjmax75** [comment]
Happens when I try searching for a package to install

```
/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305
Hide Stack Trace
TypeError: body.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/Users/john/.atom/packages/atom-beautify/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/john/.atom/packages/atom-beautify/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (/Users/john/.atom/packages/atom-beautify/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

and

```
The error was thrown from the atom-beautify package. You can help by creating an issue. Please explain what actions triggered this error.
```

**Comment by Kimer0** [comment]
Today same problem here :(

**Comment by huangzheng2016** [comment]
Error
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.254.2


### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At C:\Users\hz2016\AppData\Local\atom\app-1.26.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  7x -1:39.3.0 core:backspace (input.hidden-input)
     -0:53.9.0 core:paste (input.hidden-input)
     -0:53.4.0 core:select-all (input.hidden-input)
     -0:51.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.1 
simplified-chinese-menu 5.3.5 
tokamak-terminal 10.0.1 
```

**Comment by Angristan** [comment]
Just happened to me to 1.26.0, W10, 64 bits. Disabling the extensions I just installed did not fix the issue, nor did restarting Atom

**Comment by igotinfected** [comment]
Same issue, I have a .md with markdown-preview-plus running.
Steps:
* load atom, load .md file, load markdown preview
* 'cmd + ,' to settings page
* click on install or theme
* enter text to look for package
* error popup

running on macOS HS
restart did not fix

**Comment by BennettDams** [comment]
Same issue when trying to install new packages.
Atom Beautify is installed.
Windows 7.

**Comment by ano95** [comment]
Related, #1058

**Comment by Angristan** [comment]
Fixed for me

**Comment by igotinfected** [comment]
For me too.

**Comment by jjmax75** [comment]
can confirm is working on my end too, serverside issue with package installs?

**Comment by BennettDams** [comment]
Enabling and disabling autosave fixed it for me.

**Comment by rsese** [comment]
Thanks for all the details everyone - I've been unable to reproduce with any of the mentioned repro steps mentioned so far.  It looks like a handful of folks have gotten past the error by enabling and disabling the autosave package as mentioned in https://github.com/atom/settings-view/issues/1058#issuecomment-383935592 (thanks @igotinfected ✨).

Is anyone else still seeing the error after trying that?

**Comment by aletundo** [comment]
The fault was triggered by a bad response from the search API (eg. a 500 error).

**Comment by DSamuylov** [comment]
The same issue on Ubuntu 18.04. After installation it works fine, then I try to find `sublime theme` in installer and get this message. Very said that I have to stop using it....

**Comment by jniewt** [comment]
Happens to me with 1.28.1 and 1.29.0. Seems to correlate with package search returning 500 on https://atom.io/packages.

**Comment by jaysaurus** [comment]
This problem started for me (on .deb install of 1.29.0 on ubuntu 16) after removing either node-debugger/atom-ternjs in quick succession (I forget which order; furthermore, I don't know if it was a coincidence, one of those specific packages or atom itself doing something strange) and then immediately searching install packages thereafter

My suspicion is that the install/remove command in atom can sometimes remove dependencies from a node_modules folder that has other dependencies.

Ultimately, I found the problem went away performing the following actions.  I don't know which action was the "fix", but hopefully this will help someone out:

1. set local ~/.atom to something like ~/old.atom; 
2. installing atom via the command line as per the documentation [here]( https://flight-manual.atom.io/getting-started/sections/installing-atom/)
3. merge in ~/old.atom via nautilus' folder view (ie. the Gnome Ubuntu standard folder view) into the new ~/.atom that should now have appeared in your home folder **but** be sure to skip overwrites; use the newly install modules.
4. run `atom --safe` from command line.  Immediately close atom command line
5. run `atom`.

good luck!

**Comment by Aerijo** [comment]
@jaysaurus Was this very recently? The Atom packages website suffered some issue, and was down for a few minutes. It's back up now, so that may have actually solved the issue.

**Comment by jaysaurus** [comment]
sorry, I posted before I was done. see above :)

**Comment by jaysaurus** [comment]
ah, ok, maybe it was the package website then! oh well :P

**Comment by jaysaurus** [comment]
Could we propose, therefore, that atom return a more generic 500 handler when the install packages module has issues talking to the Atom package website?  @rsese would you like me to raise that as a new issue?

**Comment by rsese** [comment]
@jaysaurus - https://github.com/atom/settings-view/pull/1065 has been opened to resolve this particular error, do you think that's enough?  Though it does seem like in general returning an informative error code/message would be useful in general if that's not the case now.

**Comment by jaysaurus** [comment]
I think a good clean message like "The atom package repository is temporarily unavailable" would save a lot of headaches because sticklers like me will spend more time than they should looking at error messages and going "Ooooh, I wonder if I can diagnose that" haha!

**Comment by h-b** [comment]
Same here, happened after searching for "lua". If this means that the package repository is unavailble, why isn't this exception catched to show a message telling the user what's going on? What's the intention of not doing that?

**Comment by deepio** [comment]
This issue still occurs in 1.34.0.

Uninstalling all themes (except those that come with atom) and reinstalling them fixed it for me.

**Comment by 50Wliu** [comment]
@deepio can you please open a new issue?

**Comment by BenSower** [comment]
I also encountered this today in 1.34.0 on Linux. Did @deepio already create a new ticket for it?

**Comment by BenSower** [comment]
Based on deepios comment, installed a new theme + syntax highlighting and the problem disappeared.

**Comment by noopurphalak** [comment]
Still Happening for me. Atom version 1.45.0, Mac OS 10.15.3

<img width="819" alt="Screenshot 2020-04-14 at 1 16 18 PM" src="https://user-images.githubusercontent.com/8924488/79199169-32a03680-7e52-11ea-9bb3-c1a53a8a6c3b.png">

**Comment by emr-dev** [comment]
Как решить проблему ?)

**Comment by galrosencov** [comment]
i.filter is not a function
[object Object]

Atom 1.49.0
MacOS Catalina 10.15.5

**Comment by altran-fabian** [comment]
any Solution for this? 
i tried completely removing atom and reinstalling it without any luck. atom is not working any more ... what can i do to solve this error?

**Comment by altran-fabian** [comment]
Has it maybe to do with the search not working on atom.io/packages as well? 
![image](https://user-images.githubusercontent.com/59995045/88917040-653a3780-d267-11ea-8920-1e8be8ccff95.png)
![image](https://user-images.githubusercontent.com/59995045/88917064-708d6300-d267-11ea-9af9-e8b174dd9a6b.png)

**Comment by elliott-impression** [comment]
I am getting the same issue when searching for a Theme or Package:
```i.filter is not a function
[object Object]```

**Comment by BugReportering** [comment]
This error is still active when searching for a package.

**Comment by Luk313** [comment]
The following error is still active after a fresh new install (for the first time) on Manjaro Linux.
body.filter is not a function
[object Object]

**Comment by Vinlock** [comment]
I just fresh installed and am getting this issue when searching for a package.
```
i.filter is not a function
[object Object]
```

**Comment by dswah** [comment]
I'm also seeing this bug (ubuntu 20.04, atom 1.55.0)

refreshing the search multiple times in atom or at atom.io/packages ends up working...

**Comment by jtlabs777** [comment]
On windows 11, just installed Atom for first time and getting this error as well.
