### ISSUE TITLE
Update text in notification says updating to 'undefined'

### ISSUE THREAD

**Issue by ungb** [atom/settings-view#1056]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Update text in notification says updating to 'undefined'

### Steps to Reproduce

1. Have a few packages that need update
2. Click on update to <version> to update the package

**Expected behavior:** Message should say '<oldversion> -> <new version>'

**Actual behavior:** says updated to undefined.

see screenshot:
![image](https://user-images.githubusercontent.com/5624870/38160691-7b75d50e-3476-11e8-850b-4d0094a08887.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by FalkF** [comment]
Oh, thats my code failing there :cold_sweat:
I will respond with a PR later today.
