### ISSUE TITLE
Initialize the program files with the base code(sample code) based on their extensions. 

### ISSUE THREAD

**Issue by babygame0ver** [atom/settings-view#1061]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[I am new to git and but using atom quite a long time, but I do programming everyday. So I have to write some base code in the every .py file. Example as follow:
`
def main():
    pass

if __name__ == '__main__':
    main()
`
it will be nice if there will be a feature in atom to add a feature of the sample code initialization based on the extension , surely this will also happen in .c extension file. ]

### Steps to Reproduce

1. [A configuration file where we can define the sample code of every file with their extensions ]
2. [whenever we create a new file through atom we will get the sample code as defined for that extension ]
3. [the file extension will be given by the user when he/she will create the new file]

**Expected behavior:** [A simple configuration file with key value pair where we can define the extensions as keys and sample code as the value of the key like for .py : sample_code and whenever I will create a new file it comes with the sample code.]

**Actual behavior:** [I don't know whether this feature is available or not i have searched on google also]

**Reproduces how often:** [Every day]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the suggestion!  It looks like this functionality might already be provided by a handful of community packages that you could try:

https://atom.io/packages/search?q=template

Additionally, snippets could help too e.g.:

'.source.python':
  'Initialization code':
    'prefix': 'my init code'
    'body': """
      def main():
        pass

      if name == 'main':
        main()
    """

https://flight-manual.atom.io/using-atom/sections/snippets/

Though not automatic, snippets give you a way to define your starter code (and other chunks of code) for each file type that you can easily insert into your files.
