### ISSUE TITLE
Theme cards should have a "use this theme" button

### ISSUE THREAD

**Issue by Aerijo** [atom/settings-view#1108]
### Description

Packages have settings / disable / uninstall buttons on the card. Themes currently have no buttons, but would highly benefit from a button that applies the theme.

It makes intuitive sense, and would reduce confusion like in https://github.com/atom/atom/issues/18824

**Comment by FalkF** [comment]
It would be cool if there was a hover function for that button. Just like firefox had on their themes site some while ago.

**Comment by rsese** [comment]
Thanks for opening this and for clearing things up in https://github.com/atom/atom/issues/18824 @Aerijo :+1:  Just wanted to mention that we talked about this one and though we agree it would be useful, it's not something the team would prioritize.  We would review a pull request for this however, so we'll close with the `help-wanted` label.
