### ISSUE TITLE
Bug: Developer links in the packages section cause Atom to crash

### ISSUE THREAD

**Issue by 1407arjun** [atom/settings-view#1200]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
In the packages section of the editor's settings, whenever one clicks on the publisher or developer link of a particular package, Atom just crashes.

### Steps to Reproduce

1. Open the settings of Atom.
2. Navigate to the packages section.
3. Search for any package and click on its developer/publisher.

**Expected behavior:**

Not sure about what should happen, but clicking on the link should display other packages made by that developer to the user.

**Actual behavior:**

The editor crashes.

**Reproduces how often:**

Every time.

### Versions

Atom version: 1.58.0
OS: Windows 10 64-bit

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/settings-view/pull/1199, and the fix will be available in a future release.
