### ISSUE TITLE
Soft Tabs "smart" behavior is not smart when tabs are removed.

### ISSUE THREAD

**Issue by jtkiley** [atom/settings-view#122]
The Soft Tabs setting overrides (to be "smart") seem to be applied based on a check when a file is opened. However, if you replace all of the characters that induced the override, that setting remains (until the file is closed and reopened). For example, with Soft Tabs checked and a file open with some tab characters used, the editor will continue to insert tab characters based on that initial setting, even after you have replaced each of the tab characters with four spaces.

The Soft Tabs setting is (rightly) ignored when opening a file that has the opposite case. For example, after opening a file that includes tab characters, the editor will use tab characters regardless of setting. This issue only seems to pop up when an open file is changed from one to the other without being closed and reopened.

Of course, the workaround is easy enough, but it's a little bit of friction after finding a few stray tabs and removing them in the course of doing some other work.

I tried this with Python, Gfm, and Stata `.do` files, and saw the same behavior.

Reproduce:
1. Turn off Soft Tabs (I know, who would do this?).
2. Create a new file, indent some nonsense with tabs, and save and close it.
3. Turn on Soft Tabs.
4. Reopen the file.
5. Note that additional indents still use tabs (rightly).
6. Replace all of the tabs with four spaces.
7. Note that additional indents continue to use tabs (wrongly).
8. Remove any tabs added in step 7.
9. Save, close, and reopen the file.
10. Note that indents now use spaces (rightly).

Workaround:
1. Replace the "wrong" type of characters.
2. Save, close, and then reopen the file.

**Comment by damieng** [comment]
There's been zero activity or discussion on this issue for over 2 years so I'm going to archive it.  If there are new thoughts or somebody wants to push it along please continue the discussion and we can reopen it.
