### ISSUE TITLE
can't override the default key binding

### ISSUE THREAD

**Issue by LeonardoGentile** [atom/settings-view#124]
I want to change the `cmd-[` and `cmd-]` key bindings for switching tabs so I've added this to my  `keymap.cson`

``` cson
'body':
  'cmd-]': 'pane:show-next-item'
  'cmd-[': 'pane:show-previous-item'
```

but no matter what when I press them I get the default behaviour (indentation/outdentation).

Should't the custom settings take precedence over the default ones?
![screen shot 2014-05-07 at 12 49 38](https://cloud.githubusercontent.com/assets/412061/2901467/62bb1852-d5d5-11e3-8bfc-67e927594173.png)

**Comment by joel-regen** [comment]
so...um... is there any way to just make this a little more user friendly? Like how eclipse works?

**Comment by DonkeyAfterDark** [comment]
Ditto. I'm having the worst fucking time associating "cmd-d" with duplicate lines and "cmd-e" with delete lines. I put the override commands in keymap.cson and they just don't work.

**Comment by TakanashiOuken** [comment]
Having the same issue
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
Does not seem to work

**Comment by emlazzarin** [comment]
I'm also having the problem TakanashiOuken is having.

**Comment by TakanashiOuken** [comment]
'body':
  "ctrl-alt-tab": "pane:show-next-item"
  "ctrl-alt-shift-tab": "pane:show-previous-item"
I did this at the end...

**Comment by iamsellek** [comment]
@TakanashiOuken @emlazzarin 

Just figured out the issue. If you do a search in the keybindings section for 'ctrl-tab', you'll see that there's this 'ctrl-tab ^ctrl' shortcut as well:

![image](https://cloud.githubusercontent.com/assets/5157053/17110159/917eb672-5269-11e6-8906-463c9ac6007a.png)

That one is the one taking precedence for the 'ctrl-tab' shortcut. To fix, just add an !unset for that one, too. To get browser-like tab navigation working, just do the following:

'body':
  'ctrl-tab': 'unset!'
  'ctrl-shift-tab': 'unset!'
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'

**Comment by k1-hedayati** [comment]
@iamsellek please add your respose to docs and save people from googling

**Comment by guyca** [comment]
time_spent_here += 2;
@iamsellek Thanks a lot!

**Comment by Gui38** [comment]
Had this problem with **platformio-ide-terminal** plugin
ctrl-enter (run selection) was overwritten by enter(new line) **even** after modyfying the specificity to the same "enter" has 
`atom-workspace atom-text-editor:not([mini])`
the `unset!` method worked but i could no longer make new lines, a bit annoying...
Finally @izuzak 's adding of `, .worspace` did it! :
![capture](https://cloud.githubusercontent.com/assets/19855994/19899557/e24fc2c2-a060-11e6-8167-e54a5bd34612.PNG)
I'll try to report this to **platformio-ide-terminal** people, anyway thank you

**Comment by rizkyramadhan** [comment]
I did this

'body':
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
  'ctrl-tab': 'pane:show-next-item'

**Comment by iamsellek** [comment]
@rizkyramadhan That seems to be the latest fix, after an Atom update at some point!
