### ISSUE TITLE
Feature Request - easy disable all 3rd-party packages/themes in Settings View

### ISSUE THREAD

**Issue by faddah** [atom/settings-view#126]
This is in Atom 0.94.0 on an iMac with Mac OS X 10.9.2 Mavericks with all the latest updates.

I recently had to hunt down a package conflict that was causing the Dev Tools console (usually invoked with cmd-option-i) to come up whenever I brought up the Settings View (it turned out to be php-beautifier package - i've filed a github issue with that developer).

Problem was, I had over 132 packages I had loaded to disable and then re-enable back on again, one at a time, re-starting Atom each time to see which package was causing the issue.

It would be nice if Settings View had an easier, one-click method to disable _all_ packages at once, then turn them back on, either one at a time, or better, in groups until it is narrowed down.

This would be in the main Settings Panel, and I envision it being in different levels —

a)  level one - disable/enable all packages  (reducing Atom to a bare editor).
b)  level two - disable/enable just third party packages, not created by Atom.
c)  level three - disable/enable packages in large groups, to narrow the search

It would also be nice if packages could be enabled/disabled just with a simple check box next to them, when hunting down packages one by one.

My suggestion, at any rate,

best,

—  faddah wolf
     portland, oregon

**Comment by Arcrammer** [comment]
Why do the packages still show as enabled in the packages list when you do an `atom --safe`?

**Comment by 50Wliu** [comment]
@Arcrammer Because you didn't exactly disable them - Atom is (basically) just ignoring the `~/.atom` folder for that run.

**Comment by damieng** [comment]
We have decided not to implement this feature so I am going to go ahead and close this issue.
