### ISSUE TITLE
remove updated packages in 'Available Updates' section

### ISSUE THREAD

**Issue by rixrix** [atom/settings-view#129]
In Packages pane, the updated packages in 'Available Updates' section should probably be removed once update is complete, as of 0.94.0 version, here's the following behaviour:

* clicked update icon for package eg. fizzy
* once update is complete, the check icon appears on the top right
* but the fizzy package stays in the update section forever or until atom is restarted
also, the update button should be disabled once the update is in progress or when package update is completed

FYI:  originally filed from https://github.com/atom/atom/issues/2069

![8a073ce2-d670-11e3-9f9d-d1625c6ada80](https://cloud.githubusercontent.com/assets/36795/2967044/7745e4ba-db24-11e3-9fd2-c068e6eb11b7.png)

**Comment by mnquintana** [comment]
This was resolved awhile ago.
