### ISSUE TITLE
Unable to set auto-indent

### ISSUE THREAD

**Issue by jwoertink** [atom/settings-view#132]
I'm writing slim markup and when I press enter, my cursor returns to the beginning of the line instead of indented under the tag I just created. When I go to `Edit > Lines > Auto Indent` and click on this, nothing happens. I see no checkmark or anything to indicate that this worked. 
![screen shot 2014-05-27 at 5 36 44 pm](https://cloud.githubusercontent.com/assets/2391/3099199/115b0b10-e5f8-11e3-8064-673e07352312.png)

I'm using Atom version 0.99.0 on OSX 10.9.2

**Comment by jakubheglas** [comment]
Guys, how have you managed to fix this indentation issue with Slim markup? A year later, I'm facing the very same issue. New line is not getting indented despite Auto indent specifically turned on in Settings. 

I'm using official slim-template for syntax highlighting (even tried Ian Mitchell's one) and linter-slim. Thanks for the tips!

**Comment by izuzak** [comment]
@jakubheglas Check out my comment https://github.com/atom/settings-view/issues/132#issuecomment-44419444 and https://github.com/slim-template/language-slim/issues/1. As far as I can tell, this was never fixed in slim-template.

**Comment by jakubheglas** [comment]
@izuzak Suggested hack worked for me, thanks!
