### ISSUE TITLE
Rating/Downvoting Packages

### ISSUE THREAD

**Issue by muchweb** [atom/settings-view#151]
There are packages that state to provide some functionality, but they don't. Or packages that are scam or don't work.

To add ability to
- rate
- or downwote
- or view current user count
- or view uninstall (remove) count
- or view usage time (i. e. installed and removed right away)

Here is how it may look like:

![screenshot from 2014-07-18 13 57 38](https://cloud.githubusercontent.com/assets/7157049/3626329/2a50cae0-0e7c-11e4-9426-61bede137748.png)

or

![screenshot from 2014-07-18 14 00 43](https://cloud.githubusercontent.com/assets/7157049/3626335/32bcfc58-0e7c-11e4-8cbb-84b32ff717b0.png)

**Comment by damieng** [comment]
There has been no further activity on this feature request so the issue is being archived.
