### ISSUE TITLE
Recently updated package info out-dated

### ISSUE THREAD

**Issue by batjko** [atom/settings-view#154]
After a package has just been updated, going to that package's settings will show as if the update hasn't yet happened:

e.g.
![image](https://cloud.githubusercontent.com/assets/7287076/3714673/93df1c3c-15b6-11e4-93a6-c434c239c346.png)

Afterwards:
![image](https://cloud.githubusercontent.com/assets/7287076/3714674/a12cc3da-15b6-11e4-9c7e-006b6e02f9b4.png)

That's a little bit confusing, especially since it still explicitly offers you to update the package, so it might make you wonder if the update failed or something.

**Comment by benogle** [comment]
This has been fixed somewhere along the way.
