### ISSUE TITLE
Hitting space bar in editors scrolls page

### ISSUE THREAD

**Issue by kevinsawicki** [atom/settings-view#25]
Moved over atom/atom#1238

**Comment by kofi-clever** [comment]
Seeing this issue in v1.8.0. Is it a regression or am I missing a config setting?
![space-scroll](https://cloud.githubusercontent.com/assets/16216084/16534766/3a2781fe-3f97-11e6-8fd7-133a1c404d4a.gif)

**Comment by blrodgers** [comment]
I second @kofi-clever.  I thought it was just me.  My fresh install of 1.8.0 has this behavior on the package, theme, and keybindings screens.

**Comment by zetoke** [comment]
Same here. Same screens. 1.8.0

**Comment by lee-dohm** [comment]
@kofi-clever @blrodgers @zetoke You may want to subscribe to https://github.com/atom/settings-view/issues/767 which is tracking the current incarnation.
