### ISSUE TITLE
Don't show uninstall button for bundled packages

### ISSUE THREAD

**Issue by kevinsawicki** [atom/settings-view#252]
Just use disable instead

![screen shot 2014-09-25 at 2 15 23 pm](https://cloud.githubusercontent.com/assets/671378/4412437/1c3916f2-44f9-11e4-94bc-81b183ecf1da.png)

**Comment by xlaywan** [comment]
Atom 0.206. I still see this button for bundled packages.

**Comment by izuzak** [comment]
Happens for core packages and themes, as far as I can tell.
