### ISSUE TITLE
No indicator for what the default is for checkbox

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#268]
![screen shot 2014-10-22 at 8 30 32 am](https://cloud.githubusercontent.com/assets/1038121/4738902/6e6fadd4-5a00-11e4-9bdf-1f923f83ec52.png)

`Non-word characters` and `Preferred line length` both clearly indicate that they are set to the default and what the default is. But none of the checkboxes give any indication of either whether they are set to the default nor what the default is.

I suggest adding a `Default: false/true` after checkboxes to give that visual indication.

**Comment by mnquintana** [comment]
:+1:

I didn't even realize checkboxes didn't show defaults until I came across this issue.

**Comment by thedaniel** [comment]
Perhaps to match the text inputs above, just a light italic *Default* after boxes that are set to their default values.

**Comment by braver** [comment]
Same goes for select (enums): you can't tell what's the default. 
I kinda wonder why that's important though. For a text input, it's hard to tell what you have to put there, hence the placeholder. A checkbox or a select are self explanatory, and all options should be equally valid.
Do you want to "reset"? Or do you feel the defaults are more reliable? Perhaps a small reset-to-default-button for each setting would be nice?

**Comment by simurai** [comment]
I guess knowing the default would be nice in case you're not sure anymore what's the "recommended" option. Like the Shadow DOM checkbox changed from being off by default to on. But adding lots of "Default: false/true" labels feels like too much.

@braver Ya, the reset button would be an option, but you might don't want to reset everything just to know what the defaults are.

Maybe a "Show defaults" button that then would add the labels? wow.. that's a setting for the settings. :stuck_out_tongue:

**Comment by braver** [comment]
Same thing goes for the text input though, you have to empty it to view the default. Wouldn't it be easier to show the default in a tooltip for every setting?

**Comment by simurai** [comment]
> Same thing goes for the text input though, you have to empty it to view the default.

Yeah, right. Tooltip would be easiest.

**Comment by bastilian** [comment]
Closable?

![screen shot 2016-06-24 at 19 03 52](https://cloud.githubusercontent.com/assets/7757/16344752/77f6d86c-3a3e-11e6-96fc-b3c72438a722.png)

**Comment by 50Wliu** [comment]
@bastilian Your screenshot still doesn't show the default for checkboxes.

**Comment by bastilian** [comment]
ah, i totally missed that it was not just about explaining what the option was. ...oh, well. then let's prepare a PR... :D

**Comment by iokiwi** [comment]
Could use switches instead of checkboxes where in their default state the switches are a plain color
 
![image](https://cloud.githubusercontent.com/assets/1480457/21968657/de5cf294-dbfb-11e6-9da1-5604797f2186.png)

But a switch which has been enabled by the user goes green and a switch which has been disabled by the user goes red.

![image](https://cloud.githubusercontent.com/assets/1480457/21968681/1ed5401a-dbfc-11e6-8289-ea37f2b7c5b1.png)

Check out JSFiddle for intended UI https://jsfiddle.net/s9gd0u4p/

**Comment by lee-dohm** [comment]
We discussed using switches like you're suggesting but decided to go with native controls in the default themes to make things easier for community packages to style. See https://github.com/atom/settings-view/pull/350 (among others) for more information.

**Comment by iokiwi** [comment]
Ah, OK. I had a read of the referenced PR and can understand the reasoning behind sticking to native controls.

I guess that only leaves a few options. Could simply state the default in the description under the control label, or put an indicator next to the control label such as the _Default_ text as suggested above. May I alternatively suggest placing an icon next to the label for check boxes which are not in their default state. 

![ui](https://cloud.githubusercontent.com/assets/1480457/22000127/64b5619a-dca2-11e6-959d-73ba1b4fdcb9.png)

**Comment by johanderuijter** [comment]
If this is still a wanted feature and you decide on tooltips, i could try to revive my old pr #688, if not, i'll close it.

**Comment by lee-dohm** [comment]
@johanderuijter Yes, I think the tooltips would be a good idea. If you could update your PR, that would be great 👍

**Comment by simurai** [comment]
@iokiwi Nice ideas. Something that would be tricky is showing the default for dropdowns. So that you don't have to select each option to see which is the default. Tooltips would make that easier with just showing it in text form.
