### ISSUE TITLE
Progress indicator for installing/updating an individual package

### ISSUE THREAD

**Issue by MetaMemoryT** [atom/settings-view#270]
It would be nice to have a progress bar, showing an estimate of how long it will take to install/update a package.

**Comment by Moter8** [comment]
:+1: Luckily packages aren't that bloated yet :)

**Comment by thedaniel** [comment]
We could probably use the content-length header to show the pct of the s3 download but some packages have compilation steps of variable / unpredictable lengths...

I'm personally OK with the current "spinner" background on the install button and think it communicates the information that we do have now well enough. Maybe someone will come by with a UI mockup that's not too noisy and we can talk about it more ;)

**Comment by simurai** [comment]
I agree that a progress bar that is stuck for a while at 100% wouldn't be that great, UX wise. Maybe it could first be a "progress" for the download, that later turns into a "spinner" while installing. Could look super cool.. I might give it a shot, but not as highest priority.

**Comment by jadekler** [comment]
+1 this, I get a lot of coffee shops that block >1MB installs. In Atom, it's hard to tell if this is the case or if the install is just going slowly, leading to incorrect install stops and manual grabs a bunch of times.

**Comment by damieng** [comment]
Because we actually shell out to `apm` and that doesn't have any kind of progress reporting this is not possible.

**Comment by absynce** [comment]
I don't know if https://github.com/atom/apm/issues/148 would be the place to vote for `apm` progress reporting support since it's referencing a particular implementation option, but I'm voting for it. Please let me know if there's a better one.

**Comment by winne42** [comment]
I also vote for it. Currently, "platformio-ide" is installing since half an hour and I really don't know what to do now...
