### ISSUE TITLE
UI performance

### ISSUE THREAD

**Issue by thedaniel** [atom/settings-view#291]
Panes do not load immediately - I think we could do a lot to make the UI *feel* more responsive even before tuning the underlying package and settings operations.

**Comment by evjan** [comment]
@thedaniel I'm interested in looking at this one. What do you mean by "panes" in this context? Do you have any particular ideas in mind about how to make it feel more responsive?

**Comment by carloscarcamo** [comment]
+1

**Comment by thedaniel** [comment]
@evjan It's been a while since I filed this issue, but it still holds true. I think that I meant "panel" rather than "pane" - things like "settings" "keybindings" etc that load when you click the nav on the left. They are named like `<topic>-panel.coffee` in the source. 

In general responsiveness could be improved across the board. The panels loading mentioned above, or for example the loading and display of packages in the Packages panel. This issue should probably be more specific, but it can serve as a tracking issue for more specific perf concerns.
