### ISSUE TITLE
Setting for UI font-size

### ISSUE THREAD

**Issue by braver** [atom/settings-view#307]
It has been mentioned in #275, but not addressed. 

UI themes set a single `@font-size` in `ui-variables`. This cannot be changed effectively by a user (since font-sizes in most themes aren't relative), so you're stuck with whatever the theme developer deemed a suitable size.

UI stylesheets can be set up to use `em`, `rem` and calculations in less to derive additional font-sizes from a single variable. That should make it possible to give users some influence over the font-size of the UI and not just in the editor.

I've set up a theme with the intention of providing such an option and taking that flexibility into account from the get go. However, I'm running into problems because I can't seem to reach `<html>` to set attributes or classes. I need to be able to change that element's font-size to be able to effectively use `rem` units (which seems to be the only sane way to accomplish this anyway). There are ways around this of course, but it all gets kinds hacky. And perhaps this should be a core setting anyway?

**Comment by simurai** [comment]
Do you have a concrete example why you want to add attributes or classes to `<html>`? I tried out changing `@font-size` in your Isotope theme and it works already pretty well.

One problem with adding a general UI Font Size setting is that then a user expects that it works with all themes. And that is probably not feasible, at least not for the 1.0. So for now, I think it should just be part of a theme's settings. Those that want can opt-in. Also the latest discussion re #275 is that configuring colors should also be done in a theme's settings. Like you already did with the 2 toggles and font picker.

If you add a text input that updates `@font-size`, would that work?

**Comment by braver** [comment]
The only reason to change anything at the <html> level would be to change the font-size. I agree that it's best done in the theme and not in core, at least for now. 

Is it possible to change less variables via config? That would be plenty powerful and also solve the 'problem'.

**Comment by simurai** [comment]
> Is it possible to change less variables via config?

Officially not, but I think @alchiadus has been brewing something custom: https://discuss.atom.io/t/settings-view-for-a-syntax-theme-package/14045

Ultimately, would be nice if there is an easier way. Maybe part of a theme's `package.json` like https://github.com/atom/settings-view/pull/275#issuecomment-62884127 It would add controls to a theme's settings that change the variables.

**Comment by simurai** [comment]
Gonna close this for now. Not saying it will never happen (I hope it does), but it's currently not that easy to add, see https://github.com/atom/atom/issues/5735 for more infos about it.

**Comment by braver** [comment]
Sure, no problem. I'll track that issue instead. It's not even much of a problem if it doesn't happen, there are solutions in place for the UI themes that work that way.
