### ISSUE TITLE
Failed avatar downloads cached

### ISSUE THREAD

**Issue by postcasio** [atom/settings-view#327]
Not sure how it happened, but my avatar cache contains a bunch of zero length files:

```
total 816
drwxr-xr-x  31 dominic  staff   1054  9 Jan 08:58 ./
drwx------  10 dominic  staff    340  9 Jan 08:56 ../
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 ArnaudRinquin-1420793804883
-rw-r--r--   1 dominic  staff  67698  9 Jan 08:56 AtomLinter-1420793804879
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 Chris911-1420793804870
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 DavidLGoldberg-1420793804875
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 Zren-1420793804880
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 abe33-1420793804884
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 atom-1420793804900
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 atom-community-1420793804871
-rw-r--r--   1 dominic  staff  12288  9 Jan 08:56 blakeembrey-1420793804873
-rw-r--r--   1 dominic  staff  64342  8 Jan 08:54 dualmoon-1420707269103
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 emmetio-1420793804873
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 fundon-1420793804879
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 izuzak-1420793804881
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 jacobbednarz-1420793804875
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 jawee-1420793804875
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 jerolimov-1420793804882
-rw-r--r--   1 dominic  staff  55549  8 Jan 08:54 jesseweed-1420707269104
-rw-r--r--   1 dominic  staff  39750  8 Jan 08:54 jglovier-1420707269101
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 kenwheeler-1420793804883
-rw-r--r--   1 dominic  staff  39317  8 Jan 15:29 kevinsawicki-1420730948639
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 lee-dohm-1420793804882
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 nathanborror-1420793804876
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 nikhilkalige-1420793804873
-rw-r--r--   1 dominic  staff  21684  8 Jan 08:54 noseglid-1420707256675
-rw-r--r--   1 dominic  staff   9348  8 Jan 15:29 orderedlist-1420730948639
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 postcasio-1420793804884
-rw-r--r--   1 dominic  staff  48933  8 Jan 15:29 smashwilson-1420730948636
-rw-r--r--   1 dominic  staff      0  9 Jan 08:56 thomaslindstrom-1420793804872
-rw-r--r--   1 dominic  staff  42903  8 Jan 15:29 tombell-1420730948638
```

The settings view fails to realise these images are broken and doesn't invalidate them, resulting in a bunch of broken image icons in the package views:

![screen shot 2015-01-09 at 09 25 57](https://cloud.githubusercontent.com/assets/1759837/5677668/8c99ff5c-97e1-11e4-9eef-e625691783ab.png)

**Comment by xPaw** [comment]
Just noticed this happening too.

**Comment by brunoric** [comment]
Also happening with me.

**Comment by Horta** [comment]
Same here. But the avatars do exist and can be rendered outside Atom.

![screen shot 2015-08-18 at 09 35 53](https://cloud.githubusercontent.com/assets/514522/9325747/92c40ad6-458c-11e5-8970-07996a54a032.png)

![screen shot 2015-08-18 at 09 36 03](https://cloud.githubusercontent.com/assets/514522/9325752/99f92200-458c-11e5-8f10-732f46d48e47.png)

**Comment by pjcarly** [comment]
Same here

**Comment by 50Wliu** [comment]
@Horta that is a different issue with the Available Updates page - please see #595.

**Comment by n370** [comment]
Same thing happening for me for the past few months. 
Thought 1.x release would fix it but got it wrong.

**Comment by michelemarrionline** [comment]
same here!

**Comment by diogo-gomes** [comment]
+1

Atom 1.5.4
Ubuntu 14.04.4 64-bit

**Comment by alexpaluzzi** [comment]
Still broken.. 1.5 years later.
Same issue here: https://github.com/atom/settings-view/issues/595

**Comment by 50Wliu** [comment]
@alexpaluzzi No, that is a different issue specifically regarding the "Available Updates" screen.  This issue is tracking the bug that images aren't cleared if they failed to download correctly.

**Comment by alexpaluzzi** [comment]
@50Wliu My bad. They look like the same problem. Noted.

**Comment by LeonBlade** [comment]
I had no idea this was such a long standing issue...  I have it as well.

**Comment by theFroh** [comment]
I've got this issue as well, the inspector renders the avatar correctly, and I solved it by deleting the settings-page folder within atom's cache.

**Comment by digeomel** [comment]
Same here, on atom 1.7.4 on RHEL 7 behind proxy

**Comment by adambuczynski** [comment]
Still a persistent issue in atom 1.10.0-dev-35bdaf3

![image](https://cloud.githubusercontent.com/assets/490562/16904515/1906b96a-4cec-11e6-9372-974c3705863a.png)
