### ISSUE TITLE
Packages don't sort alphabetically

### ISSUE THREAD

**Issue by olmokramer** [atom/settings-view#332]
Right now there's some structure in the packages list, but for example `linter-csslint` is always at the top of the `community packages` list, and `turbo-javascript` is always third. In the `core packages` list, `language-objective-c` is always at the top

Atom: `v0.169.0`
OS: `Linux Debian 8 (testing)`

**Comment by 50Wliu** [comment]
:+1:.  Mine goes something like `autocomplete`, `language-objective-c`, <everything here's in order>, `language-*`, `bookmarks`, ...
And the disabled packages list...I don't even know what order that's in.  It goes o->p->r->b->e->s->i->s->i->aaa->u->w->...

**Comment by olmokramer** [comment]
Upgraded to Atom 0.170.0 and the problem's still there.

**Comment by mnquintana** [comment]
Yup, same here on Atom 0.172.0 on OS X Yosemite and Ubuntu 14.04.1 LTS.

I actually have no idea what order it lists in because it's not alphabetic or in chronological order of install time / date.

**Comment by benogle** [comment]
This should be fixed in the next version of atom
