### ISSUE TITLE
Update Installed Themes list when themes are installed

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#335]
**Expected:** When I install a theme from the "Install" pane, if I go to the Themes pane, I should see the newly installed theme listed under Installed Themes.

**Actual:** When I install a theme from the Install pane, if I go to the Themes pane, I don't see the theme listed anywhere under Installed Themes. (It is listed in the UI or Syntax Theme select dropdowns, though.)

**Comment by benogle** [comment]
This was fixed in https://github.com/atom/settings-view/pull/570
