### ISSUE TITLE
Inconsistent title fonts

### ISSUE THREAD

**Issue by dgraham** [atom/settings-view#340]
Lucida Grande is in use in some places, Helvetica Neue in others.

![screen shot 2015-01-13 at 9 52 18 am](https://cloud.githubusercontent.com/assets/122102/5724962/833cc344-9b0c-11e4-9c53-071161ff4cbd.png)

**Comment by simurai** [comment]
@dgraham Looks like you're using the Unity theme?

Anyways.. it's now fixed for all themes. Core was overriding Bootstrap, but now it just `inherit`s from whatever font-family the theme uses.

**Comment by dgraham** [comment]
Yep, it's the Unity theme.
