### ISSUE TITLE
Clickable area of labels is too big

### ISSUE THREAD

**Issue by gustavpursche** [atom/settings-view#343]
![screen shot 2015-01-14 at 00 22 41](https://cloud.githubusercontent.com/assets/2244375/5731425/8809b9dc-9b83-11e4-9c9d-7e25803287d0.png)

A quickfix could be

```less
.settings-view .checkbox .setting-title {
  display: inline-block;
}
```
![screen shot 2015-01-14 at 00 25 29](https://cloud.githubusercontent.com/assets/2244375/5731456/e1247e30-9b83-11e4-8d43-d482ba5597d1.png)

but this has a problem, if there is also `.setting-description`, which will be still a block-element and therefore has a width of 100%. To apply inline-block also to the description is not possible, since there has to be a linebreak between both elements. Maybe somebody has an idea how to solve that?

Atom: 172

**Comment by simurai** [comment]
@gustavpursche Thanks, that's a great suggestion. Limits accidental clicks. The `.setting-description` elements are now moved outside of the `<label>`s, so they can stay as blocks.

**Comment by gustavpursche** [comment]
Alright, I can live with that. Actually I liked the description inside of the `<label />` for accessibility reasons (if the title wouldn't be self-explaining) but it's hard to bring together.

Thanks for fixing it so quickly!

**Comment by simurai** [comment]
An empty dummy `<div>` between the title and description could work too, but since descriptions can take up a lot of space, I think it's safer to make them non-clickable.
