### ISSUE TITLE
esformatter plugin settings are empty on Windows

### ISSUE THREAD

**Issue by lewisl9029** [atom/settings-view#345]
I just installed esformatter on Atom for Windows v0.172.0 (might be platform specific?), and the settings panel seems to be empty:

![Screenshot](http://i.imgur.com/LCk8K4o.png)

I've tried uninstalling and reinstalling the plugin, but no luck.
According to the [author](https://github.com/sindresorhus/atom-esformatter/issues/7) this is more likely to be an Atom issue than with the plugin itself.

**Comment by sindresorhus** [comment]
Related to https://github.com/atom/settings-view/issues/383

**Comment by sindresorhus** [comment]
This was resolved in #371

**Comment by izuzak** [comment]
Yep, thanks @sindresorhus.
