### ISSUE TITLE
Config not loaded for inactive themes

### ISSUE THREAD

**Issue by braver** [atom/settings-view#347]
This seems to be new, not sure. Originally reported in my UI theme: https://github.com/braver/isotope-ui/issues/9. 

Config is only available for the currently selected themes. While all installed themes have a "settings" button, settings will not show up for themes that are not selected. 

After switching to a theme that has settings, the settings only show up after a reload. 

If you previously used a theme with settings, in the settings view for that theme only the settings that deviate from the defaults show up.

Steps to reproduce:
* Install [isotope-ui](https://atom.io/themes/isotope-ui).
* Click the settings button for isotope-ui.
* *You will not see any settings.*
* Set the ui theme to isotope-ui.
* Click the settings button for isotope-ui.
* *You will not see any settings.*
* Reload atom.
* *Settings are now available for isotope-ui.*
* Check the box for "Background gradient".
* Install [graphite-ui](https://atom.io/themes/graphite-ui)
* Click the settings button for graphite-ui.
* *You will not see any settings.*
* Set the ui theme to graphite-ui.
* Click the settings button for graphite-ui.
* *You will not see any settings.*
* Reload atom.
* *Settings are now available for graphite-ui.*
* Click the settings button for isotope-ui.
* *Only the setting for "Background Gradient" is visible.*

There are 2 important problems:
- If you install a new theme you can't tweak settings until you reload (and it's impossible to communicate that requirement effectively).
- Displaying only non-default settings for a theme that is not active is messy and confusing.

**Comment by braver** [comment]
I was able to solve problem # 1 by making the coffee that enables the config run on `atom.themes.onDidChangeActiveThemes`. This enables the config directly after a theme is selected.
Problem # 2, where themes have settings buttons but no settings (except for some residual non-default settings), still persists as far as I can tell.

**Comment by mnquintana** [comment]
Was this resolved in https://github.com/atom/settings-view/pull/371?

**Comment by braver** [comment]
Seems like it :+1:
