### ISSUE TITLE
Strange behavior when disabling then uninstalling packages. 

### ISSUE THREAD

**Issue by zephraph** [atom/settings-view#352]
I was testing something for another issue and ended up disabling and uninstalling two packages. Now when I search for those packages to install them the show up as installed but disabled. 

Showing what I'm seeing
![package](https://cloud.githubusercontent.com/assets/3087225/5877642/9aee924c-a2e6-11e4-8d10-63d50d1676a5.PNG)

Proof that the packages aren't installed
![package2](https://cloud.githubusercontent.com/assets/3087225/5877663/bc8e9d84-a2e6-11e4-9367-9602876ed6e8.PNG)

When pressing "Enable" in this weird, out of state view the console logs:
```
Could not resolve 'minimap-highlight-selected' to a package path
```

When clicking uninstall it sits there for a second before transition to this state:
![package3](https://cloud.githubusercontent.com/assets/3087225/5877708/22929a68-a2e7-11e4-91d4-26dbd077791f.PNG)
(Notice the disabled coloring).

Clicking install in this view does install the package and get things back in the proper state. It didn't show the installed package under the packages view until after I reloaded the window though.

**Comment by thedaniel** [comment]
Weird. Thanks for the super detailed bug report.

**Comment by zephraph** [comment]
This was on 0.175.0. I haven't retested since 0.176.

**Comment by olmokramer** [comment]
I'm getting the same behavior (on Atom 0.176.0), even when I restart Atom right after disabling then uninstalling the package.
I should also note that the disabled coloring on the install button (last image in OP) also happens when the package is <em>enabled</em> (though the color will be green instead of orange/red):
![atom-install-d](https://cloud.githubusercontent.com/assets/3612514/5931727/d60415f0-a6a1-11e4-91eb-62db0cc37307.png) and ![atom-install-e](https://cloud.githubusercontent.com/assets/3612514/5931728/d60440d4-a6a1-11e4-9e4d-cc9c598fb89c.png)

**Comment by zephraph** [comment]
@thedaniel, I feel like the package cards (available-package-view) needs a better defined state. This is also important for #351. Right now view changes are managed in [handlePackageEvents](https://github.com/atom/settings-view/blob/0a1329ce422a9dbf5ac18e834e94a29d764966d5/lib/available-package-view.coffee#L129). I feel like adding a class of installed-package or available-package and basing the state more off that would be easier to follow. Thoughts?

**Comment by thedaniel** [comment]
> I feel like the package cards (available-package-view) needs a better defined state

I think this is very likely. During the last UI overhaul I noted a lot of places, including that, that needed a refactor to become less brittle. Having more of a view-model style separation in a lot of places makes the package more testable as well. As far as the implementation details I am afraid I can't comment as I'm in the middle of digging through some other code today but if you have an idea that you feel good about, PRs welcome - don't feel like you need to get it perfect before opening the PR (if that's what you decide to do) - just enough of a spike to get your ideas across and we can discuss it as you go.

**Comment by zephraph** [comment]
@thedaniel I'll add it to my list of stuff to work on. I still probably won't get around to it till this weekend because I'm trying to push out my [github notifications package](https://github.com/zephraph/atom-github-notifications) today or tomorrow.

**Comment by jlord** [comment]
We've made some updates to the buttons in `settings-view` over the last few months and I'm wondering if you're still seeing this behavior? I tried to reproduce it and got the expected behavior..

**Comment by zephraph** [comment]
Nope.
