### ISSUE TITLE
What is "Completions"? Need info/help caption

### ISSUE THREAD

**Issue by CaptSaltyJack** [atom/settings-view#353]
I find this "Completions" box to be fairly vague/ambiguous. What kind of completions? What's an example of what this box expects? I have no idea what this does. I'd recommend an explanatory caption.

![settings-completions](https://cloud.githubusercontent.com/assets/440132/5893148/c4f5b914-a48d-11e4-99fa-92341e91513d.png)

**Comment by thedaniel** [comment]
Good catch!

**Comment by jlord** [comment]
@CaptSaltyJack Thanks for the issue, this was confusing and not needed in Settings here anyways so we've removed it. :sparkles:
