### ISSUE TITLE
Hide / disable settings button if package / theme has no settings

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#355]
**Expected:** When I see a Settings button on a package card (like in the Packages or Themes panes' lists), I expect that there will be user-configurable settings for that package.

**Actual:** There may or may not be user-configurable settings for the package – there's no way of knowing without clicking the button (or on the package name link).

I think it would be extremely helpful if those Settings buttons were hidden or disabled if the package doesn't expose any user-configurable settings. You would still be able to easily navigate to the same package detail view by clicking on the package name link in the package card. This would be a simple visual indicator for packages without user-configurable settings, and would keep users from wasting too much time clicking through looking for configurable settings.

#### Hidden
![image](https://cloud.githubusercontent.com/assets/823545/5921964/d80f2a60-a615-11e4-884b-406fe795805a.png)

#### Disabled
![image](https://cloud.githubusercontent.com/assets/823545/5922026/5609d230-a616-11e4-8b4a-0d23ce07917a.png)

**Comment by 50Wliu** [comment]
:+1: for hidden.

**Comment by zephraph** [comment]
There's a problem with this though. 

The settings view has all those important links for that package. Navigating to the repo, opening an issue, viewing the code, README, changelog, etc. You'd be effectively cutting off access to these links.

**Comment by mnquintana** [comment]
@zephraph Fortunately: 
>You would still be able to easily navigate to the same package detail view by clicking on the package name link in the package card.

The package name links to the same detail view as the settings button, so it wouldn't be cutting off access to that view.

**Comment by zephraph** [comment]
Assuming that sticks around (Check out the discussion going on in #351). I agree that doing this would provide more visibility to where there are actually settings that can be adjusted, but there could be an admittedly small subset of people out there that don't use package name navigation. It would be confusing for those users. (Not saying that this shouldn't be done because of that reason, just providing an extra perspective).

**Comment by mnquintana** [comment]
That's totally true, it would be a trade-off, but I think it would be a worthwhile one to have some kind of visual indicator for packages with configurable settings. (I for one have wasted so much time hunting for configs in my packages. :confused:)  That's kinda why I support hiding the button over disabling it - I think if it were disabled it could be seen more as some kind of package / Atom core bug, instead of an intentional design choice.

**Comment by mnquintana** [comment]
@thedaniel Would you mind if I took a crack at this one? I was looking to contribute code more now and this seems like a good entry point.

**Comment by thedaniel** [comment]
Given that clicking the settings button and the package card do the same thing, isn't it a little strange to have it at all? That said I think we need to have some indication that settings are available, because there's a lot of user confusion around core vs. package settings already. I don't have a good answer. I guess this is a good first step.

**Comment by mnquintana** [comment]
Hmmm that's true. I could imagine the Settings button immediately setting the scroll position at the package's Settings heading though (while clicking the package card always sets the scroll position to the top). But let's try this out and see how it works.

(Would you mind assigning the issue to me? It makes it a little easier to keep track of. Thanks!)

**Comment by zephraph** [comment]
@thedaniel, I think you've got a point there. It doesn't really seem necessary anymore. Do you think there's somewhere that we could put a simple gear to indicate that there's settings?
![atom_mockup_settings](https://cloud.githubusercontent.com/assets/3087225/6717048/b0080b34-cd77-11e4-9b97-77556c359b98.png)

(On, and on a side note thanks for the highlight on card hover! I was going to implement that myself today until I found that it was in the latest version).

**Comment by thedaniel** [comment]
cc @simurai

**Comment by simurai** [comment]
Yeah, I think having the gear icon to indicate if a package/theme has settings is a good idea. How about in front of the version?

![screen shot 2015-03-21 at 6 56 53 pm](https://cloud.githubusercontent.com/assets/378023/6764610/125e8ade-cffc-11e4-8ba2-1b22dc3fd5e1.png)

Just so there is less chance to clash with the download number.

And to make it more clear, with a tooltip on hover that says something like "Has package settings".

**Comment by mnquintana** [comment]
@simurai That looks pretty good, but it might be a problem down the line if we implement #424 – there wouldn't be enough room for everything, I don't think.

**Comment by zephraph** [comment]
@mnquintana I've had some ideas about how to handle that. 

First off, just shorten what you show.

![downloads-icon](https://cloud.githubusercontent.com/assets/3087225/6766520/3c073d24-cfd7-11e4-9e77-6be91f89f350.png)

Secondly, hide information until you want to see it.

![package-icon](https://cloud.githubusercontent.com/assets/3087225/6766494/5d9d79f4-cfd6-11e4-9666-4724205ad25a.gif)
[_codepen_](http://codepen.io/anon/pen/bNOxzY) example

Optionally this could be done only in situations where space was less than a certain amount. So, by default everything would be expanded, but if the window was collapsed and the card had less room then the icons would collapse down. 



@simurai @thedaniel What do you think?

**Comment by mnquintana** [comment]
I'm sort of torn on the location of the settings indicator. On the one hand, it seems to make sense in the stats row because it's just a row of icons, but on the other hand, the stats row is really a section dedicated to atom.io stats about the package – whether or not a package has settings is really unrelated info. I'm thinking @zephraph's mockup of butting it where the settings button used to be, while maybe not as visually congruent, makes more sense organization-wise. What do you think?

Also, @zephraph @simurai what do you think about my other idea, to use the Settings button as the indicator, but also change the click behavior so it opens the package detail view scrolled to its settings (like adding `#id` at the end of a URL)? (Of course, this would only be noticeable if the package had enough settings / keybindings / a long enough Readme.)

**Comment by zephraph** [comment]
I'd be fine with having the icon appear beside the uninstall button. I'd rather that than have the settings button still be present, regardless of where it links to.

**Comment by simurai** [comment]
If the gear icon can be clicked (to scroll to the settings section) and is right next to the uninstall button, then I think it should look like a button too and we could keep it as is. And just remove the buttons for packages that have no settings.

If the gear icon is just a hint (to show there are settings), then the icon alone is fine. Or another place that might fit well is next to the package name?

![screen shot 2015-03-25 at 6 30 51 am](https://cloud.githubusercontent.com/assets/378023/6813439/88513caa-d2b8-11e4-8d42-2172a3acb4e2.png)

**Comment by thedaniel** [comment]
> If the gear icon can be clicked (to scroll to the settings section) and is right next to the uninstall button, then I think it should look like a button too and we could keep it as is.

I'm coming back around to just following the title of this PR - hide the button if there aren't settings, and maybe scroll to settings if the button is clicked, and leave the rest be.

**Comment by zephraph** [comment]
![image](https://cloud.githubusercontent.com/assets/3087225/6814884/2f17e790-d251-11e4-83c9-b991ccd5e331.png)

I don't know, at this point I'd almost rather not see it at all. -_-

Having it next to the name wouldn't be good because it would seem like clicking on the link would take you to the settings. 

I'm inclined to agree with @thedaniel I guess. Just drop it if there aren't settings.

**Comment by mark-hahn** [comment]
> The package name links to the same detail view as the settings button,

This isn't working.  The name links to a web page.  There is no visible way to get to the settings.  No one would think to click on the background.  This was a serious problem for me when I was looking for the load time of my package.

**Comment by jlord** [comment]
@mark-hahn You're right, clicking the name does go to the web page. I believe this comment came before the fix was shipped. 

If a package has settings a Settings button will be shown. Clicking this button or the card itself will take you to the settings. 

If there are no settings, you can still click on the card (on hover the color of the card changes and the cursor changes) to see the Readme and a bit more information about the package. 

Since the settings view does contain useful information like startup time, that can't be found anywhere else (correct?), it may be worth making an action to it more obvious.
