### ISSUE TITLE
Navigating to the settings view while in the settings view removes the package breadcrumb

### ISSUE THREAD

**Issue by zephraph** [atom/settings-view#358]
While in the settings view the *Settings* button is available and the package name is still clickable. Clicking on that name removes the package breadcrumb at the top permanently (or until window reload). 

![settings-view-error](https://cloud.githubusercontent.com/assets/3087225/5941200/e43e1dea-a6d4-11e4-829c-610bd8fc6047.gif)

The package name probably shouldn't be clickable here and the settings view button shouldn't be present.

**Comment by mnquintana** [comment]
:+1: I've run into this so many times.

**Comment by jlord** [comment]
> breadcrumb at the top permanently

Expanding on this, the breadcrumb does disappear even when you return to the view that had it after you've clicked the view that doesn't have it. 

- Click _Packages_
- Click first package, get taken to view with breadcrumb
- Click package, lose breadcrumb
- Click _Packages_ again
- Click on same first package, no breadcrumb

**Comment by mnquintana** [comment]
I think this is resolved now
