### ISSUE TITLE
Development themes showing up in community section

### ISSUE THREAD

**Issue by thedaniel** [atom/settings-view#372]
The title says it all, @jlord is seeing this on her machine (in a dev window, should confirm in a non-dev window)

**Comment by braver** [comment]
No repro here (0.187, OS X 10.10.3). Themes linked with `amp link -d` show up in the development themes. Themes linked with `amp link` show up in the community themes.

![normal window](https://cloud.githubusercontent.com/assets/2543659/6791397/f3d04634-d1ae-11e4-8c5b-1a8683278752.png)
![dev window](https://cloud.githubusercontent.com/assets/2543659/6791398/f3eca6a8-d1ae-11e4-85a1-e5751e4b739d.png)

**Comment by 50Wliu** [comment]
No further reports, I'm going to tentatively close this one out for now.
