### ISSUE TITLE
settings-view:open command doesn't open settings view anymore

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#380]
Doesn't work neither when triggered with a keybinding nor from command palette:

![settings](https://cloud.githubusercontent.com/assets/38924/6187623/3470124e-b389-11e4-81e3-d7f285801251.gif)

cc @benogle -- not sure, but maybe related to some of the [recent changes you made](https://github.com/atom/settings-view/commits/master?author=benogle)?

**Comment by stramel** [comment]
Moving my issue to this so it is in one location. Sorry for the duplicate issue!

> I am unable to open the settings through the command palette or using the keys `Ctrl-,`. Using the Menu however, I am able to access it through Edit > Preferences. 
>
> I have verified this is still an issue in Atom's Safe Mode (`--safe`) and that there are no errors in the console. 
> 
> My setup:
> **OS:** Ubuntu 14.04
> **Atom:** 0.180.0-2dac7fd
> **settings-view:** 0.181.0
