### ISSUE TITLE
Supports short repository url

### ISSUE THREAD

**Issue by fundon** [atom/settings-view#387]
NPM supports 
```js
  "repository": "atom-minimap/minimap",
```

But in Atom, that was broken.
![screen shot 2015-02-20 at 4 03 43 pm](https://cloud.githubusercontent.com/assets/27926/6283076/1b0eeece-b91a-11e4-8981-0e7913048ea0.png)
![screen shot 2015-02-20 at 4 03 51 pm](https://cloud.githubusercontent.com/assets/27926/6283077/1b47dd2e-b91a-11e4-925b-876b9f76bdb0.png)

**Comment by sindresorhus** [comment]
The fix is to always use [`read-package-json`](https://github.com/npm/read-package-json) to read package.json as it normalizes a lot of fields.
