### ISSUE TITLE
Find should allow you to search within the Settings View

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#394]
_From @benbalter on February 24, 2015 0:56_

I went to the packages list, looking to change a particular packages setting, and expected Command-F to allow me to search the list (thinking it was just an Atom view). Turns out that's not the case (I had to click into the search filter box, despite the native search dialog popping up).

It'd be awesome if either native search worked, or hitting Command-F hijacked the native functionality and dropped me in the filter dialog when listing installed plugins.

_Copied from original issue: atom/atom#5703_

**Comment by izuzak** [comment]
_From @50Wliu on February 24, 2015 1:11_

I'd actually consider the find box popping up a bug (the best behavior would be to put focus into the filter dialog).

**Comment by izuzak** [comment]
Related: https://github.com/atom/settings-view/issues/253

**Comment by 50Wliu** [comment]
Generalized the title a bit because fnr can be pretty useful in the package's settings as well.

**Comment by damieng** [comment]
Closing in favor of a general settings search function.

**Comment by chenglou** [comment]
@damieng where can we follow on the progress of that?

**Comment by damieng** [comment]
There isn't any visible progress to report just yet but I'll post a link in here once a branch is available.

**Comment by IanVS** [comment]
It's been about a year since the last update, and this feature would be really nice to have.  Nuclide seems to have implemented their own settings package, which includes a filter/search that could perhaps be used as a model.  Is this issue still under consideration, even though it's closed?

**Comment by damieng** [comment]
It is something we want to get to - the real problem is that settings basically needs a rewrite for a whole bunch of reasons.  Search would definitely be a top-billed feature of such a rewrite.
