### ISSUE TITLE
Can't open links to package pages

### ISSUE THREAD

**Issue by 1j01** [atom/settings-view#400]
When I try to click a link to a package in the Install screen to see if I want to install it, nothing happens.

![](https://cloud.githubusercontent.com/assets/3630663/6417837/2d6cf0a2-be7e-11e4-8011-960eeb29cd58.gif)

Apparently the links don't link to anything.

![atom-linky-link](https://cloud.githubusercontent.com/assets/3630663/6417952/229a65e6-be7f-11e4-9a72-bb5f79d74201.png)

That's not very helpful. :confused:

**Comment by 50Wliu** [comment]
This is currently being fixed in #373.
