### ISSUE TITLE
Clicking the 'package updates available' icon searches again for package updates

### ISSUE THREAD

**Issue by olmokramer** [atom/settings-view#409]
When Atom is started, it looks for package updates, and if it finds some an icon is displayed in the status bar indicating I should update my packages. However, when I click that button Atom searches <em>again</em> for package updates instead of using the information it got just some seconds ago... This takes quite some time, so I try to get some work done in the meantime. But now I forgot that there were package updates in the first place...

**Comment by adambuczynski** [comment]
+1 it would be nice if Atom wouldn't search for package updates again, after it has just prompted the user that there are in fact an X number of updated packages. Just showing those packages is enough, it's unlikely *more* updated packages came out in the short timeframe between displaying the notification and user action.
