### ISSUE TITLE
`Unexpected token :` in pure JS

### ISSUE THREAD

**Issue by JamesGould123** [atom/settings-view#410]
I'm editing a pure JS package, and I added the following config key to the module.exports

    config: {
      trimLines: {
        type : "boolean",
        title : "",
        description : "Trims leading and trailing spaces before comparing",
        "default" : true
      }
    };

and it fails with the error message `SyntaxError: Unexpected token :` on the colon after title. You can see [the full stack trace here](
https://gist.github.com/JamesGould123/a72b3173e57216bf3a76)

So I created another package using the generate package command, I disabled the activation command so it auto-activates, and added the following key to the module.exports.

<pre>
  config:
    trimLines:
      type : "boolean",
      title : "",
      description : "Trims leading and trailing spaces before comparing",
      "default" : true
</pre>
It works just fine and shows up in the package settings.

Now I'm guessing/hoping those two pieces of code are somehow different and this is a stupid mistake, but I really do not see the difference.

You can see the [full code of the package I'm working on here.](https://github.com/floydpink/atom-compare-files)

**Comment by lee-dohm** [comment]
Why not just delete the `title` key since you're not using it?

**Comment by JamesGould123** [comment]
@lee-dohm  Deleting the title does not fix the error. Deleting all the "optional values" (everything but the type) simply does not show the value, which may be somehow related to #386 Deleting any one of the optional values, and reordering them also does not fix the error, it always errors on the second colon in the TrimLines object.

**Comment by thomasjo** [comment]
Can you show us more context as to how you are adding the config schema to `module.exports`. It's a little bit tricky to figure out what's going wrong without more code. Ideally add the schema to your package and push it to a new branch so we can potentially clone and work out the issue.

**Comment by JamesGould123** [comment]
@thomasjo I just branched my fork of this repo into a new branch called config-error, with the relevant code. You can find that [here](https://github.com/JamesGould123/atom-compare-files/tree/config-error)

**Comment by izuzak** [comment]
@JamesGould123 I think there are some JavaScript syntax problems in that. You have this:

https://github.com/JamesGould123/atom-compare-files/blob/config-error/lib/compare-files-view.js#L37-L46

```js
module.exports = CompareFilesView = (function (_super) {
    config: {
      trimLines: {
        type : "boolean",
        title : "",
        description : "Trims leading and trailing spaces before comparing",
        "default" : true
      }
    };
```

So, you started a function and then have the line `config: {` as the first line in its body. That's not valid JavaScript, as far as I know. Can you clarify how you got to that point? 

The reason why the other snippet works when you generate a package with the generate package command is that the snippet is valid in CoffeeScript. 

Let me know if I'm missing something. :v:

**Comment by JamesGould123** [comment]
@izuzak I suspected I had made a dumb mistake, thanks for replying, I'm not quite sure what I was thinking.

Now I've added the config key to the object returned by the function, as you can see [in my latest commit](https://github.com/JamesGould123/atom-compare-files/commit/430ada61ce0806ce6c78ef7bf7c36dbef026d9ca). However, the checkbox still does not appear, and no error is thrown on the settings page for the module.

**Comment by izuzak** [comment]
@JamesGould123 Any chance that's because you're not doing that in the file pointed to by `main`:

https://github.com/JamesGould123/atom-compare-files/blob/430ada61ce0806ce6c78ef7bf7c36dbef026d9ca/package.json#L3

Try moving that config-related stuff to the `./lib/compare-files` file.
