### ISSUE TITLE
Open Package Detail View for any package from URI

### ISSUE THREAD

**Issue by thedaniel** [atom/settings-view#436]
In order to support atom/atom#5262 and atom/welcome#28 we should be able to open a package in Atom from a URI that looks like `atom://config/packages/<package-name>`. If the package is not already installed, we'll need to get it from apm / the atom.io API and display an appropriate message if the network is unavailable or the package is not found for some reason.

**Comment by thedaniel** [comment]
I'm finally starting on this.

**Comment by thedaniel** [comment]
Started implementation in #614

**Comment by jerone** [comment]
So with #614 merged, is it now possible to open the settings view for a particular package by opening an URI that looks like `atom://config/packages/<package-name>`? If yes, can you show an example.

**Comment by mnquintana** [comment]
@jerone It is! If you want to try it yourself you can try entering `atom.workspace.open('atom://config/packages/autocomplete-plus')` in the DevTools console, or you can take a look at the About dialog and click on the atom/metrics link for a running example.
