### ISSUE TITLE
Focus search field after openning install package / theme screen

### ISSUE THREAD

**Issue by Trudko** [atom/settings-view#440]
Hi :),

how about to focusing search field after opening Settings View: install screen? Right now I have to double tab to get there.

**Comment by mnquintana** [comment]
Related to #432

**Comment by Trudko** [comment]
True thanks!

**Comment by mnquintana** [comment]
You could reopen it – it's actually not a duplicate (just related). Currently no panel in settings-view focuses in the search field if you open it from the command palette, but a few do if you click to navigate to them.

**Comment by madeinqc** [comment]
This is still the case on Mac with Atom v.1.23.3. If I hit tab, the search field never focus, the only way to focus is to click it.
