### ISSUE TITLE
clicking links locks up atom

### ISSUE THREAD

**Issue by despairblue** [atom/settings-view#456]
Clicking any external link locks up atom on linux (also tried in safe mode)

## Repro Steps

1. open the settings pane
2. click any external link
3. atom will lock up

## Command History

```
     -0:09.0 ready (#document)
     -0:05.7 command-palette:toggle (atom-pane.pane.active)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 bug-report:open (atom-pane.pane.active)
```

## Versions

* **Atom:**       0.189.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.19.2-1-ARCH
* **Misc**
    * apm  0.157.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.9
    * git 2.3.5

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.3.</small>

**Comment by despairblue** [comment]
Clicking on `language-latex`, atom seems to launch `/bin/sh /usr/bin/xdg-open https://atom.io/packages/language-latex` synchronously, but that process never returns. If I kill it, atom responds again. If I run that command manually, it works and opens the page in chrome. :confused:

**Comment by fgimian** [comment]
I think I'm experiencing this too though I can't pinpoint the trigger in my case.  The editor locks up completely, sometimes for up to 60 secs and I get a dialog telling me that Atom is taking too long to respond.

This is probably the biggest issue I have found with Atom at the moment.

Cheers
Fotis

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#6320.
