### ISSUE TITLE
Can't find metrics section

### ISSUE THREAD

**Issue by masaeedu** [atom/settings-view#461]
https://github.com/atom/metrics mentions that metrics tracking is opt-in, and you can disable it if you so choose from the "Metrics section" of the settings view. I'm brand new to atom so I might just be misunderstanding the interface, but the settings view doesn't seem to have a metrics section, or any other option that lets you toggle metrics collection.

**Comment by mnquintana** [comment]
You can get to it by going to Settings > Packages and searching for metrics, and clicking the Disable button. It should get to be a little easier to find once #284 is implemented.

**Comment by izuzak** [comment]
@masaeedu Sorry for the unclear instructions -- I just updated them in https://github.com/atom/metrics/pull/44. If you're still having trouble disabling that package -- let us know. :+1:

**Comment by masaeedu** [comment]
@izuzak Managed to find it with the instructions above. Thanks!
