### ISSUE TITLE
Open package detail view in new tab on middle click

### ISSUE THREAD

**Issue by zephraph** [atom/settings-view#462]
In most modern browsers middle clicking opens the link the user clicked in a new tab. It'd be nice to have this functionality when middle clicking a package-card.

**Comment by mnquintana** [comment]
Or <kbd>Cmd / Ctrl + Click</kbd> for those of us without 3-button mice :smiley:

**Comment by scherii** [comment]
I agree. It would be great if there were multiple options:
* `⌘/ctrl + click`
* context menu / right click (something like "Open in a new tab")
* (mouse) middle click

Or at least a command for a custom keybinding.

It probably even would be kind of a workaround for #361. It annoys me a little that I have to scroll the package list to where I was before and I think the option to open a package detail in a new tab would "solve" this problem.

Does this conflict with Atom's "only one settings view"-behavior?
