### ISSUE TITLE
Clicking on a package doesn't reset the scrollbar

### ISSUE THREAD

**Issue by 50Wliu** [atom/settings-view#472]
Expected: Clicking on a package will reset you to the top of whatever package you clicked on
Actual: Clicking on a package will put you wherever your scrollbar was while clicking on it...kinda.

Here's a GIF (with some issues listed below):
1) The GIF started a bit late so instead of seeing me scroll down to markdown-preview it starts in the middle of me scrolling back up to Packages
2) For some reason my mouse didn't show up
3) My computer froze for a second when clicking on language-clojure so ignore that period where the GIF doesn't do anything
![settings-scroll](https://cloud.githubusercontent.com/assets/2766036/7265393/07d7e370-e867-11e4-8750-8803bcc24249.gif)

Atom 0.193.0-c795879, safe mode, Ubuntu 14.10.

**Comment by mnquintana** [comment]
:+1: I've noticed this too.
