### ISSUE TITLE
Collapse package section on title click

### ISSUE THREAD

**Issue by zephraph** [atom/settings-view#475]
Request: Click on the community packages section (or any other section) in the installed packages panel and have that section collapse. 

Use Case: There are a large number of packages installed and the user is looking for a particular package that they don't remember the name to but know what section it's in. 

(Clicking what I've underlined here would collapse the section)

![image](https://cloud.githubusercontent.com/assets/3087225/7283726/294ec3ec-e8fe-11e4-9a94-0510f77e8ad2.png)

**Comment by acontreras89** [comment]
:+1:

**Comment by acontreras89** [comment]
enjoy @zephraph!

**Comment by zephraph** [comment]
thank you sir!
