### ISSUE TITLE
No Settings Button in Install View

### ISSUE THREAD

**Issue by jlord** [atom/settings-view#479]
I noticed today that the an installed package with settings is shown to have a Settings Button in the Packages View but not in the Install View. I don't think it happens to every package... self assigning and investigating :+1: 

Packages View

![screen shot 2015-04-24 at 4 12 49 pm](https://cloud.githubusercontent.com/assets/1305617/7330059/c9d5a05c-ea9c-11e4-9dbb-4efc2515b80d.png)

Install View

![screen shot 2015-04-24 at 4 12 03 pm](https://cloud.githubusercontent.com/assets/1305617/7330066/e6503ecc-ea9c-11e4-8795-8c5dfaafaa16.png)

**Comment by benogle** [comment]
This works for me. merge-conflicts doesnt have settings, so the initial view is wrong. On my kit, merge-conflicts shows no settings button in both places. Is this still an issue for you @jlord?

**Comment by jlord** [comment]
Interesting, shows correctly now in both places for me, too :+1:
