### ISSUE TITLE
Core packages sporadically use community package avatar if org name contains "atom"

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#482]
This is sort of a strange one, but I've seen it for quite a long time:

![screenshot_2015-04-26_17_53_10](https://cloud.githubusercontent.com/assets/823545/7339457/c1bb5f90-ec3d-11e4-80e2-b59f85e765cb.png)

The avatar icon for toggle-quotes is actually [atom-minimap](https://github.com/atom-minimap)'s avatar. I've also seen this happen with AtomLinter's and atom-community's avatars too. This only happens if the package's org name happens to contain (or maybe start with) `atom`.

Possible steps to reproduce:
1. Ensure that minimap is installed.
2. Look at avatar icon for a core package.

/cc @thedaniel

**Comment by lee-dohm** [comment]
I can't reproduce this behavior using Atom v0.195.0-4ad32ee on Mac OS X 10.10.3 ...

![screen shot 2015-04-26 at 5 18 09 pm](https://cloud.githubusercontent.com/assets/1038121/7340021/50a586a0-ec38-11e4-845a-0fb869d3c17e.png)

**Comment by 50Wliu** [comment]
This has happened occasionally for me.  It's not reproducing right now but I'll try later.

**Comment by mnquintana** [comment]
Hmm yeah I suspect there are more specific repro steps, but I'm not quite sure what they are yet.

**Comment by abe33** [comment]
I had this issue occasionally, but I can't reproduce it actually. There's even times when the substituted icon is only partially rendered (only the upper half is visible).

**Comment by 50Wliu** [comment]
Just got this again (was happening for all Atom packages/themes, but just showing one to keep the image small):
![image](https://cloud.githubusercontent.com/assets/2766036/7693467/b86ad68c-fd9f-11e4-884d-d80d948f71e0.png)

**Comment by 50Wliu** [comment]
Looks like @benogle hit this too:
![image](https://cloud.githubusercontent.com/assets/2766036/7874123/415d0f10-0579-11e5-9c1a-bb28d20315fb.png)

**Comment by thedaniel** [comment]
@50Wliu I'm pretty sure that image is just a mockup.

**Comment by benogle** [comment]
Nah, my avatars for atom are always screwed up. I dont think I've ever seen them have the correct avatar.
