### ISSUE TITLE
Fetching outdated packages and themes failed

### ISSUE THREAD

**Issue by fogine** [atom/settings-view#493]
On `Packages` and `Themes` tabs atom shows a message `Loading packages...` all the time...
On `Updates` tab I get error message:

> Fetching outdated packages and themes failed.Hide output…
> Unexpected token C: 
> C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY art=php artisan $* 
> 
> 
> C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY ls=dir 
> 
> []

On `Install` tab I get same error as above. In addition It dumps retrieved JSON data about packages...

Platform Windows 7 x64.
Atom 0.196.0
I've no custom packages installed.
Probably I opened few php files in past, in older atom version...

This issue is related to https://github.com/atom/atom/issues/6161

**Comment by kevinsawicki** [comment]
Do you have any ideas where these lines are coming from?

```
C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY art=php artisan $*

C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY ls=dir
```

**Comment by fogine** [comment]
Only thing which is familiar to me is "php artisan". It's console command from Laravel framework. But I haven't used it in Atom as far as I remember... Only thing I could possibly think of is that I wrote the text  "php artisan" as regular text to an atom window...
I haven't used Atom on that machine for work yet... I've just installed it and tried basic functionality...

**Comment by kevinsawicki** [comment]
So Atom spawns the `apm outdated` command and on your machine this is the output:

```
C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY art=php artisan $*

C:\Users\David Lastname\AppData\Local\atom\app-0.196.0>DOSKEY ls=dir

[]
```

The array (`[]) at the end is valid JSON which means there are no outdated packages which is expected if you have no packages installed.

I'm really unsure though where those first two lines come from, could it be some sort of command prompt customization you have on your machine?

**Comment by fogine** [comment]
Ahh, I remember now... It's output from console.  It automatically loads file with abbreviations for terminal every time I run  new instance of a terminal...
`DOSKEY art=php artisan $*` is content of the file console is loading every time... (It creates abbreviation `art` for `php artisan` )...

**Comment by kevinsawicki** [comment]
>  Or does it try to parse the whole free lines as JSON?

It tries to parse the entire output as JSON.

**Comment by fogine** [comment]
Ok, so I turned off automatic loading of file with abbreviations, atom gets proper JSON and everything works just fine :)
