### ISSUE TITLE
Settings button in update view

### ISSUE THREAD

**Issue by Stanzilla** [atom/settings-view#499]
..does not work after having updated the package. For example, I just updated One-Dark-UI but the settings button does nothing in that view now.

**Comment by YuriSolovyov** [comment]
Confirmed:
```
$ atom -v
0.197.0-a79a8fa
```

**Comment by thedaniel** [comment]
Clicking the body of the view also doesn't do anything (not that it did anything before but we've established a pattern of clicking package to navigate elsewhere)

![screen shot 2015-05-12 at 5 25 29 pm](https://cloud.githubusercontent.com/assets/1476/7601539/301cfd50-f8cc-11e4-8bb6-f9f6be3d02d6.png)

**Comment by mnquintana** [comment]
@thedaniel We should probably just replace these with the updated package cards at this point. (Extended for the Updates panel of course)

**Comment by jerone** [comment]
Still confirmed in Atom 0.207.0
