### ISSUE TITLE
Uninstalled packages are still in the disabledPackages array

### ISSUE THREAD

**Issue by Eschon** [atom/settings-view#504]
Recently Atom showed me available updates for some packages that I had currently disabled. Since I didn't need them anymore I decided to uninstall them using the button in the Updates menu. When looking at my config.cson I realised that the uninstalled packages did still show up in the disabledPackages array.

disabledPackages:
![screen shot 2015-05-13 at 14 53 46](https://cloud.githubusercontent.com/assets/11647830/7610792/00faed70-f980-11e4-9d50-16e4edb0ce65.png)

installed packages:
![screen shot 2015-05-13 at 14 54 28](https://cloud.githubusercontent.com/assets/11647830/7610798/0cd82090-f980-11e4-8744-ca254a4d665a.png)

**Comment by jerone** [comment]
Confirmed. Annoying when reinstalling later on.

**Comment by lee-dohm** [comment]
There was some discussion around this on https://github.com/atom/settings-view/pull/139, but I never got around to implementing it.
