### ISSUE TITLE
Git repository link trimmed

### ISSUE THREAD

**Issue by jerone** [atom/settings-view#505]
The [repository link](https://github.com/atom/settings-view/blob/9b8bfe1b5727b58f1fc2a558d94e24c3fe99c289/lib/package-manager.coffee#L306) is incorrectly [trimmed](https://github.com/atom/settings-view/blob/master/lib/package-detail-view.coffee#L90) at the beginning of the link when it's a `git@github.com:` URI. 
Example: [`git@github.com:jerone/menu-manager.git`](https://github.com/jerone/menu-manager/blob/386b01aad8c85c49ba7153f44d43dba08229b9b3/package.json#L21)

![Git repository link trimmed](https://cloud.githubusercontent.com/assets/55841/7652182/085be1ba-fb0a-11e4-8653-488d64802131.png)

Windows 7 64-bits
Atom 0.198.0

**Comment by jlord** [comment]
Strange... @mnquintana maybe, but not sure why just the 'g' would be getting trimmed. I'll dig into it today.

**Comment by jerone** [comment]
[**@jlord**](https://github.com/jlord) commented on [15 mei 2015 18:01 CEST](https://github.com/atom/settings-view/issues/505#issuecomment-102448278 "2015-05-15T16:01:52Z - Replied by Github Comment Enhancer"):
> Strange... [@mnquintana](https://github.com/mnquintana) maybe, but not sure why just the 'g' would be getting trimmed. I'll dig into it today.

The `g` is trimmed because of the code is only accepting `http(s)://` urls, which then is stripped to a [pathname](https://github.com/atom/settings-view/blob/master/lib/package-detail-view.coffee#L89) and the leading slash is [trimmed](https://github.com/atom/settings-view/blob/master/lib/package-detail-view.coffee#L90).
