### ISSUE TITLE
Status bar icon persists after installing updates

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#511]
Settings View's status bar icon persists after installing updates if you installed updates by opening Settings View from the keybinding, menu item, or command palette, rather than by clicking on the status bar icon. The only way to dismiss the status bar icon is by clicking it afterwards, or reloading the window.

**Comment by 50Wliu** [comment]
The status bar icon also shouldn't disappear just by clicking on it - it should only disappear after the packages are updated (with the number going down as each package is updated).

I'll try to work on this.

**Comment by lee-dohm** [comment]
@50Wliu I assumed that an event would have to be created, like `onDidUpdateAllPackages` or something.
