### ISSUE TITLE
Package Search doesn't find the most relevant package

### ISSUE THREAD

**Issue by bronson** [atom/settings-view#513]
Search for `file-icons` on the Install tab.

Any idea why `file-type-icons` sorts above `file-icons`?  file-type-icons is both more obscure and doesn't match the search string exactly.

![screen shot 2015-05-19 at 3 51 08 pm](https://cloud.githubusercontent.com/assets/1776/7735836/a72ec184-fef4-11e4-9014-6fdd0550245a.png)

This may be related to https://github.com/atom/settings-view/issues/332

Atom 0.200.0

**Comment by xPaw** [comment]
Yeah I keep noticing this too. It usually finds some obscure packages first above what I want.

**Comment by calebmeyer** [comment]
Ditto (but worse) for the `react` package. It's way down the list for me in the atom-beta, and didn't even show up for a coworker on stable.

We should sort exact matches to the top.

**Comment by pcarn** [comment]
Just came across the same thing with the react package. It's an exact match on the name, and many more downloads than the others, why isn't it shown first?

**Comment by Ben3eeE** [comment]
A PR has now been merged which addresses this. See https://github.com/atom/settings-view/pull/761#issuecomment-228257289.
