### ISSUE TITLE
Searching for Packages error

### ISSUE THREAD

**Issue by 50Wliu** [atom/settings-view#514]
_From @borovez on May 20, 2015 19:31_

Hello, I recently installed Atom on my new PC and I am having this error when I go to settings > packages:

Fetching featured packages failed.
Requesting packages failed: Application error

It does not want to load the features packages, and searching for packages does not do anything.

Can anyone tell me what im missing here? (I have version 2.000)

Thanks!

_Copied from original issue: atom/atom#6874_

**Comment by 50Wliu** [comment]
_From @natecox on May 20, 2015 20:27_

I'm having the same issue. Can search for packages and update existing packages, but fails to find _featured_ packages and themes.

**Comment by 50Wliu** [comment]
Ditto, on Windows 7 Atom 0.200.0, Ubuntu 15.04 Atom 0.200.0, and also on a friend's Fedora with an Atom version of at least 0.198.0.

@natecox what system and Atom version are you using?

**Comment by natecox** [comment]
I'm on Atom 0.200.0 and OSX 10.10.3

**Comment by kyoh86** [comment]
+1

I'm on Atom 0.200.0 and OSX 10.10.3

**Comment by rpominov** [comment]
Same here.

![image](https://cloud.githubusercontent.com/assets/825702/7752713/ba575280-ffe9-11e4-8216-5abb9c42b2be.png)

**Comment by GameplayJDK** [comment]
Same for me. I'm using Atom 0.200.0 on Ubuntu GNOME 15.04 x64 (I used the .deb)

**Comment by hugufc** [comment]
Same. I'm on Atom 0.201.0 and OSX 10.10.3

**Comment by borovez** [comment]
Hi, in addition to this error. When I try to manually install a package I get this error:

Request for package information failed: Not Found

![Image of ERROR](http://i.gyazo.com/a633f75bd59daa54800b1ed83959b5d6.png)

**Comment by adamnoffie** [comment]
Having this problem still on version 0.201.0
![screenshot](http://i.imgur.com/Wbf3Dow.png)

**Comment by rpominov** [comment]
Works for me at the moment (still on 0.200.0). Seems like a server-side issue, but the error message is confusing in this case.

**Comment by oskarmurand** [comment]
Same error on osx on 0.200.0

**Comment by thoughton** [comment]
Same problem here, version 0.201.0 on OSX 10.9.5.

**Comment by mahonnaise** [comment]
Workaround:

1. Enter search term (error message pops up).
2. Click on "Themes".
3. Wait until themes start to show up.
4. Click on "Packages".
5. Wait until packages start to show up.

I'm not entirely sure if this actually works, because the package I want to install throws an error during installation and ultimately fails to install.

**Comment by lejo1989** [comment]
Noob the same here.

**Comment by soroktu** [comment]
same problem (I'm behind NTLM proxy)

**Comment by EdelMaks** [comment]
same error, the mahonnaise workaround does not help.

**Comment by ryancartoon** [comment]
the same issue on windows 7. atom version: 0.201.0

**Comment by christopherdwhite** [comment]
I'm also having this issue, please let me know if there's anything I can do to help.

**My Setup**

OS X 10.10.3
Atom 0.201.0 (0.201.0)
Installed via [Kitchenplan](https://github.com/kitchenplan/kitchenplan) & [Homebrew Cask](http://caskroom.io)
Path: `/opt/homebrew-cask/Caskroom/atom/latest/Atom.app`
Symlinked to: `/Applications` 

Windows 10 Pro Insider Preview (fully updated, slower branch)
VM via Parallels 10.
Atom 0.201.0
Installed via [Chocolatey](http://chocolatey.org)
Path: `C:\Users\cwhite\AppData\Local\atom\app-0.201.0`

**Comment by bordeltabernacle** [comment]
On Windows 7 I am getting the following error:

```Fetching featured packages failed.
spawn C:\Windows\system32\cmd.exe;C:\Python27\Scripts ENOENT```

Atom 0.204.0

**Comment by batjko** [comment]
Win8.1 here, 64bit, v204, works just fine.

![image](https://cloud.githubusercontent.com/assets/7287076/7938888/dd210ca2-093f-11e5-804c-7bebc8051847.png)

**Comment by rustedwolf** [comment]
Appears in "Install" section:
While typing the package name - nothing happens (no warnings), after pressing Enter nothing happens as well. To initiate the package search I have to press "themes" button and then go back to "packages".

Does anyone has the same problem?

Atom: 0.207
OS: Linux Mint 17.1

**Comment by mikestecker** [comment]
I've never had this issue until today with the release of 1.0.

Everything else outside of the updates works (Packages, Themes, Install)

Atom 1.0
Mac OS X 10.11 (Beta 2) - please note it was working on Beta 2 before the Atom 1.0 release.

![screenshot 2015-06-25 10 21 28](https://cloud.githubusercontent.com/assets/407465/8360826/210bd29e-1b24-11e5-9fa2-803a37d1e16f.png)

**Comment by mnquintana** [comment]
Sorry about that! See https://github.com/atom/atom/issues/7414#issuecomment-115318468

> atom.io is under heavy load right now (since the 1.0 announcement :stuck_out_tongue_closed_eyes:) - a fix is in the works though!

**Comment by mnquintana** [comment]
This should be fixed now, so I'm going to close this one out.

**Comment by gabriel-detassigny** [comment]
Hi,

I just installed Atom (version 1.0.2) on Ubuntu and I have this issue.
Never had it before on my Mac though.

Any idea?

**Comment by coopie** [comment]
Just happened to me this morning too, version 1.0.2

**Comment by asg1612** [comment]
I have the same issue. Version 1.0.2.

**Comment by deadsunrise** [comment]
https://atom.io/packages/search?q=git  is giving out a 500 error

**Comment by izuzak** [comment]
Thanks for the reports, everyone. We're aware of the problem and looking into it. /cc @thedaniel

**Comment by gatisdukurs** [comment]
Same here.

**Comment by inetfuture** [comment]
Same here, mac, 1.0.2, it worked before, but suddenly it doesn't.

**Comment by marcelombc** [comment]
I have the same issue in mac OS

**Comment by ngo6012** [comment]
I am having the same issue - just installed Atom on Windows. Is there a fix for this?
![screenshot 2016-01-24 15 35 15](https://cloud.githubusercontent.com/assets/13487136/12538756/17bd04a4-c2b0-11e5-88b3-62cb133f10fe.png)

**Comment by 50Wliu** [comment]
@ngo6012 Try again in a few hours - that usually just means atom.io is experiencing some trouble at the moment.

**Comment by fredddy-genuine** [comment]
exactly the same error
"Searching packages failed: Application error"

before that it showed 
"the system cannot find the path specified"

it's already starting to piss off. if it persists - will go for sublime text.

**Comment by joedborg** [comment]
Me as well.  Fedora 23, no proxy

**Comment by irnes** [comment]
Me too. Ubuntu 15.10. Atom 1.4.0

**Comment by ChongTang** [comment]
Same here. Linux Mint 17.3. Atom 1.4.0.

**Comment by longbeardmen** [comment]
Atom 1.1.0
Ubuntu 14.04 LTS
the same problem

**Comment by zignar** [comment]
same..
Win 10
Atom 1.4.0

**Comment by BobCochran** [comment]
I suggest being patient. The East Coast of the USA just had a very severe winter storm, and this could be affecting Atom's connectivity.

**Comment by astewart-twist** [comment]
+1

**Comment by bnied** [comment]
Also having this issue. Atom 1.4.0, OS X 10.11.3.

This appears to be an issue with atom.io, rather than a connectivity issue, since https://atom.io/themes/search?utf8=✓&q=native 500s.

**Comment by DreamHazard** [comment]
Windows 10, 
Atom 1.4.0, 
no proxy

I can view packages on atom.io but not search, 500 as @bnied stated. 

installed highlight-selected via cmd using "apm install highlight-selected". Just the search function is down.

**Comment by jackgeek** [comment]
Thanks @DreamHazard, that work around worked for me

**Comment by zignar** [comment]
Just tried manual installation and it works thanks @DreamHazard

**Comment by CendyLee** [comment]
I have the same error in windows 10

**Comment by Z-starts** [comment]
+1

**Comment by C4co** [comment]
+1

**Comment by michaelmaw** [comment]
Same issue here - I think the Atom search engine is covered in a meter of snow. I tried searching for "atom-snow-shovel" to help dig it out, but no luck.

**Comment by kristremblay** [comment]
Tried searching in the browser, returned a 500 response.

**Comment by lishengzxc** [comment]
```
yp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/lisheng/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/Users/lisheng/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/lisheng/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/lisheng/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.5" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/lisheng/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

`apm install xxx` was wrong

**Comment by scottwarren** [comment]
Seems like it's solved now (https://atom.io/packages/search?q=git is returning a 200). Ideally when this happens Atom could respond with something more helpful other than "Application error". I will look into fixing this.

**Comment by imfly** [comment]
I have the same error in Ubuntu 14.04 x86_64. And, can`t install via apm through the terminal.

atom: 1.5.3
no proxy

**Comment by fanxiushan** [comment]
OS X EI Capitan 
ATOM 1.5.3

`gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install`

**Comment by joedborg** [comment]
I've got around this by pulling the apm packages via their GitHub repos and then using and up-to-date npm install to get all the dependencies.

It's a horrible hack, but it seems apm is forked from a very old npm that didn't have much support for anything outside of straight https connections (e.g. behind proxies).

**Comment by KenEucker** [comment]
OS X El Capitan (10.11.3)

Atom 1.6.2

**Comment by trickbz** [comment]
Same issue. Tried to find packages in installation section and got an error msg "Searching packages failed: Application error".

**Comment by makokaka** [comment]
Is there any solution?

**Comment by tiagocedrim** [comment]
+1

**Comment by Ghstart** [comment]
some problem!!!!!!!!

**Comment by Ghstart** [comment]
I have the solution. You can try.....

1.    cd ~/.atom/packages
2.    git clone <packages url (You can get url from "Repo" button)> # git clone https://github.com/facebook/nuclide
3.    cd <packages> #nuclide
4    npm install

**Comment by pedrotnascimento** [comment]
Same issue and the above didn't wok!

**Comment by tofof** [comment]
same issue. disgraceful.

**Comment by natecox** [comment]
@tofof That attitude isn't constructive or helpful.

**Comment by damieng** [comment]
I'm going to lock this issue as it has become a dumping ground for any kind of failure searching for packages.  

Please open an issue if you run into this error with specific details - especially the detail behind "show output".  Without that we can't help.
