### ISSUE TITLE
Ability to reopen previously edited files automatically after editor restart

### ISSUE THREAD

**Issue by butenkor** [atom/settings-view#515]

**Comment by izuzak** [comment]
@butenkor Such an ability already exists -- if you start Atom without specifying a path, Atom will reopen files which were open when you previously quit Atom.

If you're not referring to that but to the ability to list recently open files, then check out this issue: https://github.com/atom/atom/issues/106.

If I misunderstood your suggestion, please try to explain it in a bit more [details](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by butenkor** [comment]
@izuzak You understood me right. I was using older version of Atom. Now it works, thanks!
