### ISSUE TITLE
Wrap whole words in upgrade notification detail

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#517]
Refs https://github.com/atom/settings-view/pull/509

Extremely minor, but I noticed that the notification detail where package names are listed wraps characters instead of whole words, which can have some interesting results with package names:

![screen shot 2015-05-22 at 3 41 11 pm](https://cloud.githubusercontent.com/assets/823545/7778455/7690a78a-0099-11e5-95d9-b7f0b4abeec2.png)

`hellcheck`

**Comment by benogle** [comment]
This notification doesnt exist anymore. Closing. I suppose this could be an issue with notification's detail field.

**Comment by mnquintana** [comment]
This issue was moved to atom/notifications#84
