### ISSUE TITLE
Report of clicking Update All for 120 outdated packages crashing system

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#519]
See: https://discuss.atom.io/t/terrible-bug-update-all-packages-freeze-my-machine/17106

I assume that Atom trying to update 120 packages at once consumed too many resources?

**Comment by Nijikokun** [comment]
Even updating 16 at once for me lags my computer to the 7 hells.

Perhaps a queue where it downloads one at a time, and waiting until one is finished installed, rather than what I guess is all of them at once?

**Comment by 50Wliu** [comment]
> Perhaps a queue where it downloads one at a time, and waiting until one is finished installed, rather than what I guess is all of them at once?
Seems reasonable.  Every other update system seems to follow that pattern.

**Comment by rymohr** [comment]
:+1: I'm tight on memory already. Each install process consumes 50-100mb and once you hit the swap you're done for.
