### ISSUE TITLE
Don't ruin it! Please don't make "Font Family" in Settings a drop-down menu!

### ISSUE THREAD

**Issue by grandsong** [atom/settings-view#525]
### Background

There are quite a few issues about improving "Font Family" in Settings.

People are calling for a list of available font names to select from.

Before a change happens, which is very likely, I must do some effort to **avert a great negative consequence for non-Latin users**.

### Two choices

About **how to show and select** the list of font names, the first and simplest solution people usually come to is a drop-down menu.

Some also mention auto-completion as an alternative. But they don't seen to know why it can be much better.

**I highly advocate auto-completion**, which suggests but **DOES NOT FORCE** a user to select from the list.

Otherwise, **a drop-down menu will hurt** me as well as many users whose natural language is not Western. In my case, Chinese.

I am going to explain.

### Why an improvement is needed at first place?

Atom is based on Chromium. And "Font Family" is a mechanism in CSS, **a web technology**.

As a result, font names which work well in other **conventional** editors may fail to work in Atom.

I am a web front-end developer and thus very familiar with CSS, so I have no problem at all.

However, those who have experienced frustrating attempts to type font names right, understandably, want Atom to be more user-friendly.

### Why non-Latin users will be hurt if drop-down is implemented?

A drop-down menu **forces a user to choose one and only** option.

If you just need one, that is obviously fine.

But **I need two**.

---

Please let me ask you a question: Why is it "Font **Family**", not "Font Face" or "Font Name"?

"Family" has members, often not only one.

World Wide Web is international. Many non-English languages have character sets beyond ASCII or Latin.

If a web site has texts from two or more character sets, such as English and Chinese, what will happen?

If there is only one font face and it is a Latin one, such as Arial, other characters (in Chinese) will not be displayed.

Well, some may say, since Chinese fonts always include Latin set, a Chinese font can simply make everyone happy.

It is partly true.

Unfortunately, due to some reasons, which is still a mystery to me, in most Chinese fonts, the Latin characters look awful and inconsistent to Chinese ones.

Moreover, what if a web site like Wikipedia needs to support several languages?

So, **the best solution is to apply different fonts to different character sets.**

And based on that requirement, "Font Family" in CSS was invented.

---

Well, some may ask me: Can't you just find a Chinese font whose Latin characters look OK enough?

Yes, I can. "Microsoft YaHei" is a good example.

But there is another big problem:

**I need a mono-spaced font for Latin!**

None of officially released Chinese fonts has mono-spaced characters. Since a Chinese font is **always very big, a mono-spaced variation is not affordable** for the majority.

I bet the same thing happens to every Japanese and Unicode font, too.

---

**For people like me, "Font Family" is a necessity.**

It works now in Atom.

**If a drop-down menu forces us to input only one font name, we will be doomed.**

An auto-completion, at the other hand, can still allow us to input an array of font names as we do now. It will work for both Latin and non-Latin users.

### Appendix: How did we survive before Atom?

If you are curious, then go on.

In Microsoft Word, in Font Dialog, we can set both a Latin/Western font and a Chinese one for the identical text.

For coding, a few guys forge their own fonts combined with a mono-spaced Latin font. You can imagine how difficult it is.

Some including me find a more flexible way.

In Windows Registry, there is a group of "Font Links". We can assign a Chinese font as a "bench player" to a mono-spaced font. Then, I use that mono-spaced font in my editors.

It works for EditPlus, Sublime Text, etc.

However, Chinese characters look weird due to some deficiency of Windows (mine is Win7). We have to use [MacType](http://www.makeuseof.com/tag/make-windows-fonts-look-like-mac-fonts/) to replace the rendering of Windows. (Note: There are more reasons to use MacType. Otherwise, it would not be worthwhile.)

This is not an easy way, either.

---

You can conclude that "Font Family" is the best.

So far, as I know, Atom is the only editor which applies "Font Family".

I love it.

Please don't ruin it.

**Comment by lee-dohm** [comment]
@grandsong I appreciate your enthusiasm and admire the detail you put into the items you contribute to the community. Where this information would be most helpful is on #286, which is where the discussion around using a drop-down and how exists. Would you mind re-posting this information there?

**Comment by grandsong** [comment]
Thanks for reminding, @lee-dohm.

Of course it is a good idea to re-post as a comment in existing issues!

PS: Before I posted this one, I had read a few issues, including #286. I decided to start a new issue, but didn't realize I could later expand my potential audience by re-posting. Actually, as you might have suspected, I am new to such online communities and need to learn how things work here.

**Comment by lee-dohm** [comment]
You are most welcome, @grandsong. Your feedback is directly applicable to #286 since that is where we are tracking how to improve the font selection experience (whether it turns out to be a drop-down or not). Because of that, I will close this Issue to direct others to continue the conversation there as well.

Thank you for understanding!
