### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by mtanzi** [atom/settings-view#527]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.207.0

### Stack Trace

Uncaught TypeError: Cannot read property 'find' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:377

TypeError: Cannot read property 'find' of undefined
    at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.filterPackageListByText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:377:15)
    at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.matchPackages (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:410:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:176:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1207:25
```

### Commands

```
     -1:04.4.0 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": []
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by qnub** [comment]
Have same issue, but 0.206 disables `sublime-tabs` which replaces and disable `tabs` and `tree-view`. In new version atom have `use preview tabs` option and disables `sublime-tabs` but not enable back own `tabs` :) When i've manually removed `tabs` and `tree-view` from `*.core.disabledPackages` in `~/.atom/config.cson` — search start working.

**Comment by bassu** [comment]
Someone broke my settings :package: LOL

**Comment by iamstarkov** [comment]
my settings is broken too

**Comment by iamstarkov** [comment]
and I have no tabs too 😭

**Comment by kankaristo** [comment]
Same thing here. Turning off "Use Preview Tabs" and restarting Atom fixed this.

I didn't have `sublime-tabs` installed and Atom's preview tabs were working fine. They just seem to break some other packages, like `settings-view` and probably `minimap` too (https://github.com/atom-minimap/minimap/issues/339).

**Comment by abe33** [comment]
Actually, `sublime-tabs` is disabling and deactivating `tabs` and `tree-view` in a not reversible manner. So if you have it running it'll add those two packages in the disabled packages array so you'll have to disable/uninstall `sublime-tabs`, then manually delete `tabs` and `tree-view` from the disabled packags in `config.json` and then restart.

**Comment by kankaristo** [comment]
I didn't have `sublime-tabs` installed; my `tabs` and `tree-view` are working fine. It's just the search in `settings-view` that's broken. Probably 2 unrelated issues, that were just introduced in the same Atom version.

**Comment by abe33** [comment]
@kankaristo oh sorry, I read your message too quickly, I thought you were also using it, ignore my comment then.

**Comment by kevinsawicki** [comment]
@benogle I added a guard for this to get a fix out but couldn't reproduce it and couldn't figure out how it was happening.

**Comment by d0nkeyBOB** [comment]
This bug happened to me, but after a restart, it has seem to fix itself. I also have "Use Preview Tabs" checked.
