### ISSUE TITLE
Uninstall button doesn't work in package list

### ISSUE THREAD

**Issue by xlaywan** [atom/settings-view#529]
Woks only in package settings view("Settings" button).

Also cannot open package settings in "Updates" tab.

win 10; atom 0.207

**Comment by mnquintana** [comment]
Thanks for the report! I was able to reproduce the first bug, and the second bug has already been reported in: https://github.com/atom/settings-view/issues/499

**Comment by izuzak** [comment]
There's a similar report in https://github.com/atom/atom/issues/7265, which points out that the uninstall button for themes doesn't seems to work as well (but does actually work -- it uninstalls the theme, but doesn't refresh the view, it seems). /cc @PierBover

**Comment by 4rlekin** [comment]
I also stumbled upon this bug, but i have a feeling that it is more general problem with refreshing of UI - for instance splitting panes seemed to stop working for a while (in the same manner as above-mentioned uninstall button), but after restart i ended up with 20+ panes (result of my hectic clicking).
