### ISSUE TITLE
Search(filter) installed packages doesn't work

### ISSUE THREAD

**Issue by xlaywan** [atom/settings-view#530]
All packages are disappear and even if I clear the filter field they don't appears.

win 10; atom 0.207

**Comment by mnquintana** [comment]
Hmmm that's strange – package search should be working as of 0.207.0 (and I can't reproduce this in 0.208.0-f850750). Can you reproduce this in safe mode? (`atom --safe`)

**Comment by xlaywan** [comment]
No, in safe mode is OK. In regular mode is ok too now.

To reproduce click on Uninstall button of bundled package, wait for about 5-10sec, type anything in filter field. I think this belongs to https://github.com/atom/settings-view/issues/252

**Comment by izuzak** [comment]
I was able to reproduce this -- the uninstall button is visible for bundle packages (not expected), and after clicking that button and waiting 10 secs -- searching using the searchbox returns 0 results.

/cc @kevinsawicki @benogle

**Comment by izuzak** [comment]
And thanks for the report, @xlaywan. :bow:

**Comment by mnquintana** [comment]
Related to https://github.com/atom/settings-view/issues/529

**Comment by AustP** [comment]
+1. I just ran into this as well. Here are the steps to reproduce:

1. Open settings
2. Click on Packages panel
3. Search for git-tab-status
4. Uninstall git-tab-status
5. Wait for it to be uninstalled
6. Search for tabs

I got 0 results from this. Restarting atom and searching directly for tabs allowed me to see it. (v 0.210.0)

**Comment by benogle** [comment]
Thanks for the report!
