### ISSUE TITLE
Install: searching after closing pane doesn't work on enter press

### ISSUE THREAD

**Issue by alexrussell** [atom/settings-view#535]
Steps to reproduce:

1. Open settings
2. Install
3. Search for anything and press enter to run the search
4. Items come up
5. Repeat 3-4 if you want to to prove that it'll work again and again
6. Close settings tab
7. Open settings (it should still be on install pane)
8. Search for anything and press enter to run the search
9. It doesn't work

As a side note, you can make it work by toggling to themes and then back to packages. So presumably the keybinding gets lost when the tab is first closed.

I'm using Atom 2.0.7.

Screencap (though not overly helpful as you'l have to trust that I'm pressing enter after typing my search terms!):

![settings](https://cloud.githubusercontent.com/assets/412784/8057188/092f4748-0ea7-11e5-959e-24f7111c1488.gif)

**Comment by alexrussell** [comment]
Probably worth me saying the same happens in `--safe` mode.

**Comment by azoerb** [comment]
Yep, this is super annoying.  Please fix!

**Comment by solbjorn** [comment]
Confirm this in 0.208.

**Comment by azoerb** [comment]
Poking around a bit in `lib/install-panel.coffee`, it seems to be a problem caused by not re-subscribing to the events (specifically `core:confirm` on `@searchEditorView.element`) found in `handleSearchEvents` after being unsubscribing from them in `detach`.

I haven't dug much further than that so far, to see what the root cause is.  I'll keep you posted on what I find.

**Comment by azoerb** [comment]
Not sure if this is the preferred way to go about this, but this fix works fine for me.  Essentially, we re-add the calls to `@subscribe` in the `attached` handler to mirror the call to `unsubscribe()` in `detached`.

**Comment by ssfrr** [comment]
Confirming this is still an issue as of v1.0.0

**Comment by azoerb** [comment]
My pull request fixes this, but I need to figure out how to properly test it before they'll accept it.
