### ISSUE TITLE
Packages using short GitHub URIs have broken repo links and some missing metadata

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#543]
![screenshot 2015-06-12 07 20 42](https://cloud.githubusercontent.com/assets/823545/8129092/90823146-10d3-11e5-852e-8fc506cb1aa0.png)

This is https://atom.io/packages/jshint - it uses a repo path of the form `username/repo` in `package.json`. The repo link in the package card is missing the first letter, and tries to open an invalid URL. The package card also failed to download the username and avatar from GitHub.

Atom 0.210.0-7a6a48d

/cc @jlord

**Comment by jerone** [comment]
Related: https://github.com/atom/settings-view/issues/505

**Comment by evjan** [comment]
Atom seems to no longer show GitHub links, but the avatar and username still aren't being loaded properly.

<img width="688" alt="screen shot 2015-10-17 at 10 09 02 pm" src="https://cloud.githubusercontent.com/assets/18362/10558502/eee7e9ea-751b-11e5-80d0-0da894c093a9.png">

**Comment by jerone** [comment]
> Atom 1.0.19 seems to no longer show GitHub links

You need to go into the package details / settings view to see the repo link.

> the avatar and username still aren't being loaded properly

That is another issue https://github.com/atom/settings-view/issues/327 which could have been solved with https://github.com/atom/settings-view/pull/661 which hasn't been released with a new Atom version (yet).

**Comment by evjan** [comment]
@jerone Thanks! I don't think #661 would fix this, the problem AFAICT is in utils.coffee. It doesn't see a short GitHub URI like "sindresorhus/atom-jshint" as something it can extract the owner name from and therefore it fails. I'm working on a fix right now, will submit PR as soon as I have it done.
