### ISSUE TITLE
Unable to page up and page down scrolling in Settings view

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [atom/settings-view#544]
When in Settings view, for any sidebar selection such as Package or +Install, I am not able to do page up and page down scrolling after a search.

But I can scroll using the mouse scroll wheel.

Also notice the search result of extension names are not in alphabetical order. Is there an extension to fix this also?

Platform: Linux Mint 17.1 / 64 bits. Atom v0.207.0.

Thank you.

**Comment by mnquintana** [comment]
There's actually an open PR for this enhancement: https://github.com/atom/settings-view/pull/468
