### ISSUE TITLE
High CPU usage when updating multiple packages.

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#546]
_From @v3ss0n on June 12, 2015 18:30_

Atom takes 40% CPU when updating multiple packages.
Doing it one by one do not increase CPU usage but when clicking multiple updates at once , atom raise to 40% cpu and never finishes.

Tested at : 
atom version v0.209.0-33accdf
Linux 64bit.

_Copied from original issue: atom/atom#7253_

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by envygeeks** [comment]
I have this same problem on my Linux install.  If there is more than one package to update it consumes 100% of the available CPU time until our watcher brings it back down to a max of 60% so that nothing else has problems.

**Comment by CKrawczyk** [comment]
I am seeing the same thing happen on my Mac.  The process "Atom Helper" takes 60-100% of my CPU usage and the final package that updates never finishes.

Atom version: 1.0.7
Macbook pro: OS X 10.10.5
