### ISSUE TITLE
Shift+Tab changes page position.

### ISSUE THREAD

**Issue by envygeeks** [atom/settings-view#549]
When in settings view (for example on the main page.) If you tab and then shift tab when the page is scrolled it actually changes the page position when you shift tab instead of keeping the current position like most UI's behave.  If this is expected behavior? It's very (for lack of a better word since I can't right now come up with the word) confusing+distracting.  It forces people to refocus what they had already focused.  Is this expected behavior?

**Comment by damieng** [comment]
Unable to repro but this might be that I don't understand the issue. If this is still a problem can you provide a screenshot?

**Comment by envygeeks** [comment]
Wait, you don't understand a problem, and can't reproduce it so your resolution is to close it? That makes total sense in software programming.  That's gonna be my new line at work, don't understand, won't fix.
