### ISSUE TITLE
Setting changes in config not updated in settings view

### ISSUE THREAD

**Issue by nice-shot** [atom/settings-view#556]
If I make changes in the config.cson file directly instead of the settings view, these settings will not be updated in the view. For example if I change the font size in the config.cson it will either remain default in the view or be the previous setting:

![settings_bug](https://cloud.githubusercontent.com/assets/2602328/8405878/67e77aee-1e60-11e5-900e-c17593f772b0.gif)

**Comment by benogle** [comment]
f47609116be0453a481e0cb9044e48c87d3a73d3 should fix this
