### ISSUE TITLE
Install Packages search not working

### ISSUE THREAD

**Issue by simurai** [atom/settings-view#559]
Saw a tweet that the search for new packages doesn't work.

![tmlrhcw](https://cloud.githubusercontent.com/assets/378023/8426066/6df8c252-1f47-11e5-918a-71a9279b2ce5.gif)

From the gif it seems that the first search was successful, otherwise there would be a bigger gap after the input. Search term was probably `set`.

Can't reproduce it myself.

**Comment by samueloph** [comment]
Pressing [Enter] doesn't updates the search string here, I have to switch to [Themes] or [Packages] search (the one that I'm not using) and then come back to make atom actually search.

**Comment by simurai** [comment]
__Update__: The person on twitter actually was hitting enter too and it didn't trigger a search. I'll update the description from being an UX issue to a bug. Although I can't reproduce it myself.

**Comment by samueloph** [comment]
I reinstalled atom here because of bug https://github.com/atom/settings-view/issues/555
And now the search works, could this be related to Nuclide packages? (I think the settings-view's bug has something to do with Nuclide). I need somebody else to reproduce it.

**Comment by benogle** [comment]
Ok, I can reproduce this with steps: 

* open settings
* click install tab
* close settings
* open settings again
* try to search
* nope

Looking into now
