### ISSUE TITLE
Settings button doesn't work on 'Updates' page

### ISSUE THREAD

**Issue by rm-code** [atom/settings-view#574]
When I try to click the settings button of an updated package in the _Updates_ view it doesn't react at all:
![screenshot 2015-07-07 12 38 14](https://cloud.githubusercontent.com/assets/11627131/8544386/1eab9e78-24a5-11e5-8be1-4f627d792982.png)

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/settings-view/issues/499 and has been fixed for the next version of Atom.

**Comment by rm-code** [comment]
Ah, sorry for the duplicate. I only searched for open issues.
