### ISSUE TITLE
Install packages search does not update on new query after package installed

### ISSUE THREAD

**Issue by matmar10** [atom/settings-view#580]
Environment
----

* Mac OS X 10.10.1
* Atom 1.0.0

Steps to reproduce
----

* Navigate to `Preferences > Settings > Install`
* Enter a search query and hit Enter
* Install one of the packages in the search results
* Close the Settings tab
* Navigate back to `Preferences > Settings > Install`
* Enter a new search query and hit Enter

Expected behavior
----

New search queries should pull up new results when submitted in the search query input box

Actual behavior
----

Old (stale) search query results are displayed and not refreshed when new query is entered

Work-around
----

* Click the `Themes` box and hit enter
* Click the `Packages box and hit enter
* Search query seems to be applied now

![Animation of stale search results after install](https://cloud.githubusercontent.com/assets/19975/8619174/736814de-26c9-11e5-9fa0-7ac4ba727327.gif)

**Comment by izuzak** [comment]
Do you see the same problem after updating to Atom 1.0.2?

**Comment by matmar10** [comment]
Confirmed fixed in Atom 1.0.02
