### ISSUE TITLE
Default text is cut off and no way to see the rest

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#585]
<img width="756" alt="screen shot 2015-07-14 at 8 06 39 am" src="https://cloud.githubusercontent.com/assets/1038121/8676605/60a8463c-29ff-11e5-8bb8-b09846e535ce.png">

When the default text is too long for the setting box, it gets cut off and there is no way to scroll or select it to see the rest.

**Comment by 50Wliu** [comment]
Should be fixed now because the default text becomes actual text when clicked on.
