### ISSUE TITLE
Atom Installed Packages Page Doesn't Search Well Before Items Are Loaded 

### ISSUE THREAD

**Issue by bobber205** [atom/settings-view#586]
An example:

I wanted to uninstall my xml formatter plugin because I'm not using it at all anymore.

I go to installed packages, type xml, press enter, packages keep loading and nothing happens.
Nothing is searched for while packages are loading.

To get it to search again, I gotta clear the field, press enter, type xml again, then press enter again.

If I just wait for everything to load before typing, it searches successfully the first time.

If all packages have to be loaded, can the search box resubmit the search terms once they're all loaded?
Odd behavior.

**Comment by alexrussell** [comment]
:+1: for this. Supremely annoying.

Obviously it depends on your system and the packages you have, but certainly for me, loading them all on a new window takes maybe 3-4 seconds, so I've usually finished typing before they've loaded and then have to delete the last character and then type it again.

The suggestions of having the search 'resubmit' on finishing loading the packages list makes the most sense to me.
