### ISSUE TITLE
Changelogs don't have a tab title anymore

### ISSUE THREAD

**Issue by Stanzilla** [atom/settings-view#596]
On 1.0.2

![changelog md_preview_-_cusersbenjamindocuments_2015-07-20_17-38-47](https://cloud.githubusercontent.com/assets/75278/8779950/53047972-2f06-11e5-9b77-446d22c30737.png)

When you tab away from it, the text shows up. So it might just be a text color problem?

**Comment by 50Wliu** [comment]
Does this happen with all UI themes or just one-dark?

**Comment by Stanzilla** [comment]
Ah damn, should have tested that before. Yeah it's only happening in One Dark. Can you move the issue, please?

**Comment by 50Wliu** [comment]
This issue was moved to atom/one-dark-ui#85
