### ISSUE TITLE
Order of a package's settings dialog

### ISSUE THREAD

**Issue by nikmartin** [atom/settings-view#597]
Is there a way for a package author to group and order settings? A package like atom-beautify has a LOT of settings for each language, but the package author has no control over the order of grouping of the settings for that package. There are 15-20 settings options for every language atom-beautify supports, and they are sprinkled across the package settings dialog.

**Comment by Glavin001** [comment]
I think having collapsible groups would be very helpful. Group all of the language options together and then collapse them until a User wants to expand the options for a specific language.

**Comment by olmokramer** [comment]
You can set an `order` property on the items in your `config` object, and you can group by putting  those items in an object:

```coffee
exports.config = {
  group1: {
    type: 'object',
    order: 1,
    properties: {
      prop1: {
        type: 'integer',
        # ...
      },
      prop2: {
        # ...
      },
    },
  },
  group2: {
    type: 'object',
    order: 2,
    # ...
  },
};
```
Collapsible groups in the settings view would be a nice to have, though!

**Comment by Glavin001** [comment]
Great, thanks @olmokramer ! It would be very nice to have these groups be collapsable. Is someone already working on that? Hopefully I can find time later this month to possibly contribute to that feature.

**Comment by lee-dohm** [comment]
Since the original question about ordering and grouping was answered, I'm going to close this. Thanks for working on the PR @Glavin001 :grinning:
