### ISSUE TITLE
Having slack-atom installed breaks settings view.

### ISSUE THREAD

**Issue by despairblue** [atom/settings-view#601]
Just cross referencing this since I think packages shouldn't be able to break the settings view https://github.com/pavloo/slack-atom/issues/15

**Comment by despairblue** [comment]
This also breaks https://github.com/lee-dohm/package-sync, so probably every package that tries to get a list of all installed packages.

**Comment by thedaniel** [comment]
> I think packages shouldn't be able to break the settings view

Unfortunately, packages can do pretty much whatever they want to the DOM or JS context that settings-view also lives in, so we don't have a good way to keep them from breaking the settings view without some heavy re-architecting. I wish I had a better answer for you than "uninstall slack-atom and file an issue on its repo" but here we are.
