### ISSUE TITLE
Don't re-enable (or display as enabled) disabled packages after upgrade

### ISSUE THREAD

**Issue by Fishrock123** [atom/settings-view#602]
Was sent here from https://github.com/atom/apm/pull/400#issuecomment-124193617 -- I also can't find if there was a previous issue.

**Comment by mnquintana** [comment]
Ah, now I found it – it was https://github.com/atom/atom/issues/7861. Just moved it to https://github.com/atom/settings-view/issues/603 – gonna close this out.
