### ISSUE TITLE
Updating a disabled package automatically re-enables that package

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#603]
_From @rktjmp on July 13, 2015 2:57_

I'm not sure how to test this again locally, because I'm not sure how to install an older version of a package.

I had the vim-mode package installed but disabled. I manually clicked the "update package" button (not the "update all" button). After the package had been updated, it seemed that it re-enabled itself. I would have expected it to remain disabled.

Not a large issue but might catch some people out if they had a larger number of disabled packages.

_Copied from original issue: atom/atom#7861_

**Comment by mnquintana** [comment]
What version of Atom are you using? You can install an old version of a package with `apm install`, e.g.:

```
apm install linter-eslint@1.0.0
```

**Comment by mnquintana** [comment]
_From @rktjmp on July 13, 2015 13:47_

```
$ atom --version
1.0.2
```

On OS X.

To reproduce:

1) Confirm vim-mode is disabled, quit atom
2) `apm install vim-mode@0.54.0`
3) Load atom and confirm vim-mode remains disabled.
4) Click "Update to 0.55.0"
5) Observe package is automatically re-enabled after update finishes

**Comment by mnquintana** [comment]
_From @rktjmp on July 14, 2015 2:53_

This also happens with `minimap-git-diff`, so i don't think its specific to `vim-mode`.

**Comment by mnquintana** [comment]
_From @palango on July 15, 2015 19:38_

Just saw this as well. Works with any package as far as I can tell.

**Comment by tedyun** [comment]
+1

Confirmed in Atom 1.0.8 on Windows 7 x64

**Comment by steelbrain** [comment]
:+1:

**Comment by polarathene** [comment]
Still occurring in 1.0.19. Seems common to report this on atom/atom, I did search but forgot to search closed issues(was thinking if it was reported it wouldn't be closed since it's still a problem, keeping one open on atom/atom might make some sense :P )

**Comment by steelbrain** [comment]
I think I'll send a PR for this

**Comment by steelbrain** [comment]
Nevermind, there's a PR for it already, https://github.com/atom/settings-view/pull/649 fixes this
