### ISSUE TITLE
invisible character settings are removed after first open

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#611]
_From @chharvey on July 21, 2015 15:30_

I just installed Atom on my new work computer for the first time and opened the settings. I noticed there were a few options for setting invisible characters, such as **Cr, Eol, Tab,** etc. This was surprising to me since I did not see those settings for Atom installed on my home computer. I checked to make sure both versions were the latest, which they were. I decided not to worry about it for the time being…

Then after quitting and reopening Atom on my new computer, the character settings were gone! I still have "Show Indent Guide" and "Show Invisibles" but no options to choose invisible characters.

Is this a bug?

---
stats:

- Work Computer: MacBook Pro (Retina, 13-inch, Early 2013), 3 GHz Intel Core i7, OS X 10.10.4 (Yosemite) 
- Home Computer: MacBook Pro (Retina, 15-inch, Mid 2014), 2.2 GHz Intel Core i7, Os X 10.10.4 (Yosemite)

_Copied from original issue: atom/atom#8004_

**Comment by izuzak** [comment]
Yeah, seems like a bug in Settings View. Thanks for the report -- gonna move this issue over to that package.

Note: you should still be able to change those config values by manually editing your config.cson file.

**Comment by izuzak** [comment]
@benogle I was able to reproduce this -- removed ~/.atom, started Atom, noticed that Settings View showed input boxes for setting invisibles, quit Atom, started Atom, noticed that Settings View no longer showed input boxes for setting invisibles (probably because config.cson was created and available on the second run).

**Comment by izuzak** [comment]
Seems like this was fixed in the meantime by other changes, so I'm closing this. @chharvey -- if you can still reproduce this in Atom 1.0.19, please let me know.

**Comment by chharvey** [comment]
@izuzak  everything seems to be working great. thanks for your help :smile:
