### ISSUE TITLE
accidentally clicking Git add in the context menu in an input field adds the entire directory

### ISSUE THREAD

**Issue by nikmartin** [atom/settings-view#612]
I have atom open and the project view open with a root folder of a git project displayed.  I went into settings view and was going to add a file pattern to the 'Ignored Names' input field, and somehow ended up clicking 'Git add' in the context menu by mistake.  I canceled the context menu and pasted the string I was trying to paste in there, and about 3 minutes later, a confirmation notice popped saying `'git add succeeded'`. I panicked and went out and did a `git status`,  and sure enough, every file and folder from the root down had been added. luckily, my working tree was in a state that `git reset` undid the add without affecting any other of my working set.

**Comment by mnquintana** [comment]
Atom doesn't ship with a "Git add" command, so this is something provided by a community package you have installed (possibly [git-plus](https://atom.io/packages/git-plus)) - you should open an issue on their repo requesting that they only add that context menu item in TextEditors with files that are in Git projects.
