### ISSUE TITLE
Updated list is cleared after moving to a different part of settings view

### ISSUE THREAD

**Issue by olmokramer** [atom/settings-view#615]
After updating my packages, I like to read the changelogs, so I click on a package card in the list, then on the changelog button to open the changelog, and it's awesome. However, when I go back to the updated packages list, it is cleared and searching for updates again. I would suggest to not clear the list automatically, but instead add a button or something.

**Comment by mnquintana** [comment]
Seems legit, especially since package cards automatically check for updates on their own and there already is a Check For Updates button.

**Comment by dsernst** [comment]
Agreed, this is a minor irritation.

**Comment by 50Wliu** [comment]
Fixed with #887.
