### ISSUE TITLE
Show view code button even when package is disabled

### ISSUE THREAD

**Issue by eboracus** [atom/settings-view#617]
The view code button is no longer available when a package is disabled. I think this should be present regardless of the current package state. The Changelog and License buttons too.

![view_code_enabled](https://cloud.githubusercontent.com/assets/11758299/9022287/e434e80e-3867-11e5-8ef8-2df1b2a58bf7.png)
![view_code_disabled](https://cloud.githubusercontent.com/assets/11758299/9022437/4d7e3054-386d-11e5-9283-1a9c2d28baae.png)

Just to confirm, I don't see this if I just disable a package and take a look at its details (I guess that view is cached in some way?). The buttons will be gone if the page is reloaded.

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/settings-view/pull/878
