### ISSUE TITLE
Render setting description links as links

### ISSUE THREAD

**Issue by benogle** [atom/settings-view#618]
![link](https://cloud.githubusercontent.com/assets/69169/9047894/cd7c1b86-39e9-11e5-8fe5-96b2e5bbaa9c.jpg)

We could probably render them as markdown.

**Comment by thomasjo** [comment]
Rendering descriptions as Markdown would be amaze! If we're down with that, I can begin working on that right now.

**Comment by mnquintana** [comment]
Yessss that would be awesome! I think we should probably whitelist allowed Markdown syntax though? (It would get kinda weird if `h1`s and images were allowed in there...)

**Comment by benogle** [comment]
Not sure if it's possible to whitelist specific features with marked. But we could either

* use the marked lexer and output the bit we want
* Just grab the contents of the first `<p>` from the output and use that

I think markdown makes the most sense.

**Comment by lee-dohm** [comment]
I've got a fix for this but I didn't have time to write specs before work. I'll work on that later today or tonight and get a PR submitted.

**Comment by benogle** [comment]
@lee-dohm :+1:
