### ISSUE TITLE
Markdown tables render incorrectly in package Readmes

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#620]
Looks like Markdown tables currently don't render as expected in package Readmes:

<img width="738" alt="settings_-__users_machistequintana_code_campus-map_-_atom" src="https://cloud.githubusercontent.com/assets/823545/9083780/256ef3fc-3b3b-11e5-8c1b-0ab3cde2b05c.png">

/cc @simurai

**Comment by jlord** [comment]
Ah, I'm guessing it's because we're not telling the markdown parser to use GitHub Flavored Markdown? Thought it seems like that is the default with `marked` which `roaster` (that we're using here) depends on... but maybe it's not actually default.

**Comment by simurai** [comment]
Started a PR #622 and added some styling for the tables.

It renders `<table>` correctly, except that empty cells seem to be missing:

![screen shot 2015-08-07 at 1 04 09 pm](https://cloud.githubusercontent.com/assets/378023/9128530/12070cb6-3d05-11e5-949c-04865ad710e2.png)
