### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by Aarilight** [atom/settings-view#623]
Ever since I started using atom, settings-view has basically stopped responding every time I use it. Steps to reproduce: Open settings, go to packages. Freezes! For 10 seconds to two minutes, usually. I don't know if there's something blocking execution/events when it's loading packages or something, but whatever it is, it's bad. I should still be able to use Atom when I open settings view. Unfortunately, I can't right now. It's not just me, is it? I've tried reinstalling atom to no avail.

**Comment by arryaas** [comment]
I also facing same issue. Atom is very slow. I like Atom very much but due to its freeze problem, I am frustrated. If this issue could be solved then it would be amazing. I recommended Atom to most of my friends but they switched back to sublime due to Atom's freezing issue.

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/atom/issues/7275

**Comment by Aarilight** [comment]
Oh thanks, sorry, I did a search for a similar issue but must have missed 'freezing'
