### ISSUE TITLE
Do some caching in loadOutdated()

### ISSUE THREAD

**Issue by benogle** [atom/settings-view#632]
Currently `PackageManager::loadOutdated()` is stateless, and it sucks. Anytime any part of the settings view needs to know what outdated packages there are, it needs to hit the network and ask. This leads to https://github.com/atom/settings-view/issues/409. And this is being exacerbated by package cards in any view that can have the update information. No bueno. 

We should cache the outdated packages in the settings view's `PackageManager`. `loadOutdated` could do the network bit, load the cache, and emit events. This method could be called when it is currently for the status bar icon. Every consumer of the outdated data can call some other method like `getOutdated` which could return a promise, just in case the cache isnt loaded up yet.

This will fix https://github.com/atom/settings-view/issues/409, and could be the way to https://github.com/atom/settings-view/issues/615

cc @thedaniel

**Comment by 50Wliu** [comment]
As far as I can tell in my latest tests (with #887) there is caching going on in loadOutdated, and the updates panel loads _fast_.  As in, it takes longer to load the font icons then it does to load the package cards.

Closing.
