### ISSUE TITLE
Links in package view open twice

### ISSUE THREAD

**Issue by rugk** [atom/settings-view#639]
If I view an installed or not installed package and click on on of the links/buttons ('view on Atom.io' or 'Changelog' e.g.) the link will open twice.

That happens with web links ('view on Atom.io') but - as I said - also with links which are opened in Atom itself (like 'Changelog').

Atom 1.0.7
Windows 7

Moved from: https://github.com/atom/atom/issues/8457

**Comment by rugk** [comment]
So FYI I could just reproduce it again, but it happens quite randomly.

This were recent error messages displayed in the console, but I don't think they have something to do with this issue - it was just a failed package installation:
![recerror](https://cloud.githubusercontent.com/assets/11966684/9393074/58f7daa8-4780-11e5-8ba0-ff1aa83ac3f9.PNG)

**Comment by izuzak** [comment]
@rugk I just tried reproducing this and wasn't able to with Atom 1.0.19 on Windows 8 or OSX 10.11 (I spent 5 minutes clicking on both). Are you still able to reproduce this with Atom 1.0.19 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by rugk** [comment]
Like I said it's very difficult to reproduce (it happens quite randomly) and so I was not able to reproduce it in safe mode until now.
However I had several different packages installed when this issue appeared in the past, so I don't think this is caused by another package.

**Comment by izuzak** [comment]
@rugk That's fine, let us know if you're able to trigger this in safe mode. I'll keep trying as well and reopen if I succeed. Thanks for reporting this.
