### ISSUE TITLE
No user-agent when requesting icons

### ISSUE THREAD

**Issue by zerowidth** [atom/settings-view#640]
When doing some log analysis for an internal GitHub project, I noticed a very large number of requests to `https://github.com/atom.png`. After clearing my settings-view cache in Atom and reloading the settings page, I immediately saw requests to this url from my IP (no one else was using Atom at the time), so I know it's the settings view that's loading these avatars. It does cache them after first load, but there's a lot of traffic for these still.

What made this particularly difficult to track down was that these avatar requests are coming in without a user agent header. Could you add something to the settings view to help identify these requests? For comparison, the GitHub desktop app uses `GitHubMac/31` or similar, so something like `Atom/1.0.7` would be appropriate.

Secondarily, I wouldn't mind if you more aggressively cached these - when loading the plugins from the atom org, it means repeated requests for the same avatar when only one request is needed.

cc @thedaniel

**Comment by kevinsawicki** [comment]
>   For comparison, the GitHub desktop app uses GitHubMac/31 or similar, so something like Atom/1.0.7 would be appropriate.

Most definitely, sorry about this.

**Comment by aroben** [comment]
I think there's a more efficient URL that can be used to load the Atom avatar. @technoweenie would know for sure.
