### ISSUE TITLE
group all individual package settings into the main settings view

### ISSUE THREAD

**Issue by a7madgamal** [atom/settings-view#669]
I suggest this to make it easier for users to find those sometimes hard-to-find hidden settings in core or community packages. I had a hard time after a clean atom installation to customize all my settings again with many community packages installed!

A good place would be the main settings view under all the settings under a main title like Package settings and smaller titles for each package

**Comment by izuzak** [comment]
Thanks for the suggestion -- if I understood correctly, this is already being discussed in https://github.com/atom/settings-view/issues/284, so I suggest you add a comment there or just subscribe for updates.

**Comment by a7madgamal** [comment]
Thanks!
I really tried to find duplicates before posting but i guess I failed :D

**Comment by izuzak** [comment]
It's fine -- finding related issues is definitely not easy :sweat_smile:.
