### ISSUE TITLE
There shouldn't be a text input field for `core.customFileTypes`

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/settings-view#670]
`customFileTypes` is a relatively new config field under the `core` schema. It is an object whose keys are scope names, and whose values are arrays of file extensions, like this:

```coffee
'*':
  core:
    customFileTypes:
      "source.cpp": [
        "h"
      ]
```

Settings view is rendering each key in the object as a text input, with the content `[object Object]`. This causes invalid data to be written to the config.

![screen shot 2015-09-28 at 11 59 58 am](https://cloud.githubusercontent.com/assets/326587/10145586/c8d71a8e-65d8-11e5-838a-1180bdc4f18d.png)

**Comment by izuzak** [comment]
I've never looked at this part of code before, but here are some notes after looking at this for a bit. I suspect this will be related to the fact that the key of that property has a dot in it: `"source.cpp"`. My hunch is based on [this](https://github.com/atom/settings-view/blob/5a115f9e051da32e7af676daf6076d890d8d5e75/lib/settings-panel.coffee#L191) -> [this] (https://github.com/atom/atom/blob/8fb4e887df800438b2deeb23a2c23004b9ff358a/src/config.coffee#L639) -> [this](https://github.com/atom/atom/blob/8fb4e887df800438b2deeb23a2c23004b9ff358a/src/config.coffee#L1145-L1154). Basically, the dot is used as a namespace separator -- it has special meaning, so using it in the name of a property causes problems. If you use `"source-cpp"`, for example -- then everything works fine. Looking at that [last piece of code](https://github.com/atom/atom/blob/8fb4e887df800438b2deeb23a2c23004b9ff358a/src/config.coffee#L1150), it _seems_ as if there's a way to escape the dot?
