### ISSUE TITLE
Cannon read property 'message' of undefined

### ISSUE THREAD

**Issue by yafp** [atom/settings-view#683]
While trying to update 'pigments (0.15.0 -> 0.17.1)' i get the following error -> see attached screenshot

![20151014_130405](https://cloud.githubusercontent.com/assets/67605/10481928/7f91fabc-7274-11e5-8030-04ae8ecd7e7f.png)

I restarted atom and tried it again with the same result.

**Comment by izuzak** [comment]
Can you please create the issue using the "Create issue on the settings-view package" button, which is shown in the screenshot you posted? That will create an issue with more information, such as the complete stack trace. Thanks!

**Comment by yafp** [comment]
That button does not work - i tried it several times before i've choosen that ugly way.

**Comment by izuzak** [comment]
Okay, can you click the "Show stack trace" link and provide a full screenshot of that, together with your Atom version and OS?

**Comment by izuzak** [comment]
Does the clipboard icon/button next to the "Create issue" button work? That should copy the contents of the exception to your clipboard so that you can paste it here.

**Comment by yafp** [comment]
Dont ask me how - but problem seems solved.
Maybe related with a systemupdate i installed in the meantime

Checking right now i do get

> All of your installed packages are up to date!

I'll close this issue.
Sorry for the circumstances
