### ISSUE TITLE
Collapsing lists of packages doesn't work in some places

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#684]
Just noticed this problem -- seems like collapsing works for themes, but doesn't for packages:

![collapse](https://cloud.githubusercontent.com/assets/38924/10508893/18b26956-732a-11e5-9a9f-b2594f32815a.gif)

Anyone else seeing that? I'm able to reproduce on Atom 1.0.19 and latest master version (1.2.0-dev-a4efded). cc some people from https://github.com/atom/settings-view/pull/593: @simurai @acontreras89 @thomasjo @50Wliu 

I tried to figure out why that's happening, and it seems that the package cards on the Packages panel have a `style="display: block;"` defined on the elements themselves (and that seems to override the `display: none;` when the collapse is triggered), but I couldn't figure out where that's defined.

Also, seems like collapsing doesn't work on the Themes panel when the list of themes is filtered using the searchbox.

**Comment by thomasjo** [comment]
I'm able to reproduce this as well. This is definitely a regression. I'll try to figure out what and when.

**Comment by acontreras89** [comment]
@izuzak yeah, I noticed this last week while working on another PR. I thought it could be caused by my dev packages so I didn't pay much attention to it.

I've tried it now at the office (with Atom 1.0.11) and it was working, however I've applied a filter and then removed it and it has no longer worked, just as you mentioned for themes.

I can take a look at it during the week, check why the action of filtering is adding styles to the elements directly.

**Comment by thomasjo** [comment]
Some piece of code is adding a style attribute directly to the `.package-card` element with `display: block`.

**Comment by thomasjo** [comment]
The fix I just pushed is a bit of a hack, but instead of digging through all of the filtering code and changing it from applying DOM-level styling to using CSS classes instead, I opted for simply appending a `!important` marker on the `display` property for the collapsed package-card style.

**Comment by izuzak** [comment]
@thomasjo Thanks for doing that. :bow: I was thinking of such an approach myself, but was also interested in figuring out which part of the code was setting that style attribute. I think that would give us better insight into what happened here and help us prevent future problems. Were you able to figure out what was setting that style attribute? As far as I could tell, there's nothing in Settings View doing that.

**Comment by thomasjo** [comment]
@izuzak Problem can be seen in https://github.com/atom/settings-view/blob/v0.230.1/lib/installed-packages-panel.coffee#L178-L181 — the usage of `.hide()` and `.show()` causes `display: block` to be toggled at the DOM-level.

**Comment by izuzak** [comment]
> the usage of .hide() and .show() causes display: block to be toggled at the DOM-level.

Very interesting -- thanks for finding that! :zap: Those hide() and show() methods are from jQuery, correct? I wonder if there's something we should be doing differently in these cases so that we don't get :trollface: again. I know nuttin' about these kinds of style shenanigans, so I'll leave that to the professionals. :smile: Thanks again for fixing this.

![](http://fat.gfycat.com/OptimalThoseFoal.gif)
