### ISSUE TITLE
Can't copy text from Settings window

### ISSUE THREAD

**Issue by bronson** [atom/settings-view#697]
I want to copy the suggested keybindings into my keymap...

![bug3](https://cloud.githubusercontent.com/assets/1776/11133125/c823c482-8948-11e5-96ce-a8de51c18c67.gif)

Expected behavior: the selected text gets copied to the clipboard.

Actual behavior: visually the copy appears to work but it doesn't actually change what's on the clipboard.

**Comment by 50Wliu** [comment]
Should be fixed by atom/atom#9796.
