### ISSUE TITLE
Package list cut off if no search is performed?

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#703]
It looks like I have too many packages installed :laughing:

<img width="901" alt="screen shot 2015-11-24 at 9 08 19 am" src="https://cloud.githubusercontent.com/assets/1038121/11374472/12283950-928b-11e5-89b7-05f7119718de.png">

I can keep scrolling, but packages after exception-reporting are not drawn.

**Comment by pdxwolfy** [comment]
I have the same issue with a brand new installation (have only added the "lines" package to date).

**Comment by simurai** [comment]
Is that the One light theme? It might be a rendering issue.. see https://github.com/atom/one-dark-ui/issues/109

Should be fixed on the dev channel: https://github.com/atom/one-dark-ui/pull/112

You can already test it in your `styles.less` with:

```less
.tree-view::before {
  transform: none;
}
```

**Comment by pdxwolfy** [comment]
Thanks, Simurai. Yes, it is that theme. It's gone away now after I installed a bunch more packages, but nice to know it is fixed (and can be dealt with if it pops up again).
