### ISSUE TITLE
'linter-eslint' package version appeared as 'undefined' in Settings|Packages (after Atom auto-update I think) and I had to uninstall and re-install that package to make it work again

### ISSUE THREAD

**Issue by darkred** [atom/settings-view#704]
Using Atom 1.3.0 beta 6 in win10 x64.
The installed packages are `linter-eslint 5.2.4` `autoupdate packages`, `language-batchfile` `jshint`(disabled) and `linter` ([screenshot](https://i.imgur.com/s5af0ea.jpg)).

The problem is that `linter-eslint` package version today appeared as "undefined" in Settings|Packages.
(Unfortunately I didn't keep a screenshot of that)
I noticed that because the package was not working, though it was enabled.

Disabling and re-enabling it didn't fix it. 
This is the 2nd time this occurs the last days (both cases were after an Atom update I think) and in both cases what only fixed it (i.e. made the package work, and display it's version number instead of "undefined") was uninstalling+re-installing the package.
But, this works only until the next Atom update_(I think that today it occurred after Atom getting auto-updated from beta 5 to beta 6)_

I didn't find any relevant entry in Developer Tools|Console
Also,I don't have such issues with the other packages.
<br>

Thank you

**Comment by lee-dohm** [comment]
Can you reproduce this error without [autoupdate-packages](https://atom.io/packages/autoupdate-packages) installed? If autoupdate-packages installs things incorrectly (since there have been many recent changes in how package code is being compiled and cached on install, I suspect this is likely) then that could easily explain the problems you're seeing.

**Comment by darkred** [comment]
Ok, I just disabled `autoupdate-packages` and will inform you the next days (especially after the next Atom auto-update) whether this was the cause.

**Comment by lee-dohm** [comment]
Thank you very much! :grinning:

**Comment by darkred** [comment]
I have updated from Atom 1.3.0 beta 6 to Atom 1.4.0
as well as updated various packages, having always the package `autoupdate-packages` disabled
and the issue never occured again.
So, this was caused by that package.
Thanks for the suggestion, @lee-dohm .

cc @wufuC

**Comment by lee-dohm** [comment]
Thanks for the update!

**Comment by wufuC** [comment]
Thanks for the report.

I have tried to reproduce this but failed (I'm on OS X, though). This seems more likely to be a problem of `apm` or `linter-eslint` itself as `autoupdate-packages` is just a scheduler that periodically calls `apm` to find and install updates.

Will appreciate if you can help further diagnosing the issue. Steps are as follows:

1. Save your work before proceeding
3. Launch Atom. Check whether the version is missing in `settings-view`.
4. Re-enable `autoupdate-packages`. It will call `apm` to update `linter-eslint` (bump to 5.2.6, as of the time of this writing). This may take a 1-2 minutes.
5. Select "View" in the window menu. Then select "Reload". This will reload the Atom window.
6. Check if the version number is still missing.

[Please file an issue here if the problem persists] (https://github.com/wufuC/atom-autoupdate-packages/issues/new). Thank you very much.

**Comment by darkred** [comment]
In the issue 359 referenced above, it seems like the linter-eslint package installation has been corrupted. I'll uninstall all packages and Atom itself, and then delete all leftovers in `C:\Users\user\.atom`. Then I'll do a re-install.
If the issue occurs again, I'll file an issue in your repositoty @wufuC. Thanks for your reply.
