### ISSUE TITLE
Characters Invisible in a long line

### ISSUE THREAD

**Issue by sayantaghosh** [atom/settings-view#708]
After a certain length the characters become invisible, this is very annoying when long string operations need to be done.

**Comment by lee-dohm** [comment]
It sounds like you're talking about https://github.com/atom/settings-view/issues/585. Am I correct?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/708#issuecomment-161529310. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
