### ISSUE TITLE
Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by gbhopal** [atom/settings-view#709]
I am trying to get data from my MongoDB however i am able to get the data, but my response code is not working, i keep getting the above error.

``` js
exports.getWeatherAll = () => {
  console.log('Get all Weather for city')

  mongoDB.getAll(data => {
    console.log(data)
    return createSuccess('list found', 201, data)
  })
}

createSuccess = (message, code, data) =>{
  console.log('data is here')
  console.log(data)
  var success = {code:code, response:{status:'success', contentType:'application/json', message:message, data:data}}

  if(data !== null || data !== underfined){
    success.response.data = data
  }

  return success
}

exports.getAll = (callback) => {
  WeatherDB.find( (err, body) => {
    if (err) {
      callback('error: '+err)
    }
    const data = body.map( item => {
      return {
              _id: item.id, city: item.city, country: item.country
            }
    })
    callback(data)
  })
}
```

**Comment by lee-dohm** [comment]
I'm not sure what this has to do with either the Settings View or [Atom](https://atom.io). Are you sure you posted this in the right repository?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/709#issuecomment-161702438. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
