### ISSUE TITLE
Disable updates for disabled packages

### ISSUE THREAD

**Issue by adamreisnz** [atom/settings-view#713]
I have a bunch of core Atom packages that I'm not using (nor ever plan to use), for example specific language packages. It's not possible to uninstall or remove those core packages form Atom, with the only option being to disable the package. I have done that, but now Atom keeps bugging me about updates for those packages.

I don't care to know that there are updates for my disabled packages, and would prefer not to waste bandwidth on downloading them either.

Is there a way to prevent disabled packages from being updated? Can they somehow be excluded from the auto-update process until enabled again?

**Comment by lee-dohm** [comment]
Issues I see with this:

1. Disabled packages could become so out-of-date that they would no longer work with the current version of Atom when enabled again
1. When a disabled package is enabled, it would have to check for updates and, potentially, update before it could be enabled

**Comment by 50Wliu** [comment]
> I have done that, but now Atom keeps bugging me about updates for those packages.

Atom should not ask you to update bundled packages.  Are you sure you didn't install them yourself through `apm install`?  What is the output of `apm list --installed`?

**Comment by adambuczynski** [comment]
No, I didn't install them manually. It were Atom core packages, e.g. language Go and the like.
They do show up in my list of installed packages

```
├── atom-handlebars@1.2.0
├── atom-pair@2.0.10
├── atom-text-transformer@0.7.0
├── editorconfig@1.2.2
├── highlight-line@0.11.0
├── highlight-selected@0.11.1
├── html-entities@0.4.0
├── language-c@0.51.1
├── language-csharp@0.11.0
├── language-go@0.41.0
├── language-java@0.17.0
├── language-make@0.21.0
├── language-ruby@0.65.0
├── line-ending-converter@1.3.2
├── linter@1.11.3
├── linter-jscs@3.2.0
├── linter-jshint@1.2.1
├── merge-conflicts@1.3.7
├── minimap@4.18.0
├── multi-cursor@2.1.0
├── node-debugger@1.3.0
├── project-manager@2.6.5
└── sync-settings@0.6.0
```

**Comment by adambuczynski** [comment]
> Disabled packages could become so out-of-date that they would no longer work with the current version of Atom when enabled again
> When a disabled package is enabled, it would have to check for updates and, potentially, update before it could be enabled

Yes, I think a check might be warranted, and possibly ask or force the user to update the package before re-enabling it.

**Comment by 50Wliu** [comment]
That's really weird, disabled bundled packages should never show up as manually installed in `apm list --installed`.  Just to be safe I would `apm uninstall` them.

The force-update upon re-activation sounds good.

**Comment by adambuczynski** [comment]
I have `apm uninstall`ed them. After restart, they still show up in the list of package within Atom now, but no longer show under `apm list --installed`. Will check if they reappear again for some reason.

Could this have been a relic from some pre 1.0.0 version of Atom? I've been using it for quite a while.

**Comment by adamreisnz** [comment]
The packages have not reappeared in the list. But the issue of updating disabled packages remains.

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

Upon further review, we feel that given the concerns in https://github.com/atom/settings-view/issues/713#issuecomment-164288501, this would add too much complexity for very little gain. We also feel that having packages in a disabled state should be something temporary, not a long-term thing. Leaving things as they are will give people occasional reminders to either update and re-enable packages or finally uninstall them. As such, we're going to close this.

Thanks again for all your help!

**Comment by adamreisnz** [comment]
I think it's a fallacy to think that disabled state is temporary. As long as you keep pushing useless (to me) packages with Atom's core, I am going to disable them and keep them disabled, because I don't want them leeching memory or contributing to start up time unnecessarily.

**Comment by lee-dohm** [comment]
@adamreisnz Except core packages, even when disabled, aren't suggested for updates. So this issue still wouldn't apply for that scenario.

**Comment by adamreisnz** [comment]
Well it did, that's why I raised this issue.
I don't disable packages that I installed myself and no longer need. I just remove those.

**Comment by lee-dohm** [comment]
If they're installed in `~/.atom/packages`, even if they're also built-in, then Atom treats them like Community packages. This is why we now have the [dalek package](https://github.com/atom/dalek), to help detect and encourage people to correct this situation that causes these confusing problems.
