### ISSUE TITLE
Question about enum with Objects

### ISSUE THREAD

**Issue by silvestreh** [atom/settings-view#718]
This is mostly a question rather than a bug report. I'm trying to get a `<select>` with its options coming from an `Array` of `Object`s rather than `String`s. I managed to get the template to render correctly with the following:

```javascript
"testCombo": {
    "title": "Test",
    "description": "Test select with objects",
    "type": "object",
    "enum": [{"value": "#FFF", "label": "White"}, {"value": "#000", "label": "Black"}],
    "default": {"value": "#000", "label": "Black"}
}
```

Its output looks like this:

![captura de pantalla 2016-01-06 a las 13 04 56](https://cloud.githubusercontent.com/assets/1133339/12147138/2732425c-b476-11e5-9917-28fd7f545703.png)

![captura de pantalla 2016-01-06 a las 12 57 06](https://cloud.githubusercontent.com/assets/1133339/12146906/14456044-b475-11e5-89eb-b29c27bd4be3.png)

However, I must be doing something wrong because it won't set the default value and the `onDidChange` listener logs nothing:

```javascript
atom.config.onDidChange('atom-material-ui.colors.testCombo', (value) => console.log(value)); // Doesn't output anything
```

**Comment by lee-dohm** [comment]
Not entirely sure that what you're trying is really supported. Could you just use the strings and then map from the string to color value in code?

**Comment by silvestreh** [comment]
@lee-dohm that's what I'm doing now. But I'd like to pass a string with two colors, `#FFF,#000`, `split()` it into an array and then use them as base and accent colors in my theme. 

Right now the code is redundant and WET. [Check it out](https://github.com/silvestreh/atom-material-ui/blob/master/lib/amu-settings.js#L79). 

What I'd like to do is something like…

```javascript
atom.config.onDidChange('atom-material-ui.colors.predefinedColor', (value) => {
    var colors = value.newValue.split(',');
    
    atom.config.set('atom-material-ui.colors.baseColor', colors[0]);
    atom.config.set('atom-material-ui.colors.accentColor', colors[1]);
});
```

**Comment by lee-dohm** [comment]
Yes, I see your conundrum. I agree that you're encoding the structure in code when it should be encoded as data. But you don't have to store that data in the configuration system. If you add a constant declaration (sorry my ES6 is still developing) at the top of the file:

```javascript
const colorMap = {
  Amber: {
    base: "#FFD54F",
    accent: "#A28832"
  },
  Blue: {
    base: "#2196F3",
    accent: "#FFFFFF"
  }
  // etc
}
```

Then you can simply reference it in your `atom.config.onDidChange` handler:

```javascript
atom.config.onDidChange('atom-material-ui.colors.predefinedColor', (value) => {
    atom.config.set('atom-matrerial-ui.colors.baseColor', colorMap[value].base);
    atom.config.set('atom-material-ui.colors.accentColor', colorMap[value].accent);
});
```

I'm pretty sure that would work and be nice and DRY :grinning:

**Comment by silvestreh** [comment]
That's a smart approach to my problem. Thanks @lee-dohm! :smile:

**Comment by lee-dohm** [comment]
You're quite welcome :grinning: Mind if I close this?
