### ISSUE TITLE
Switch Atom themes based on time of day

### ISSUE THREAD

**Issue by citrusui** [atom/settings-view#725]
Okay, this is pretty straightforward. When you're coding at night, you don't want your computer screen to blind you, right? So you choose the One Dark theme, Atom Dark, or the many other themes on [atom.io](https://atom.io). Well, what if you *really* like the light theme, and don't want to get blinded when sunset comes around...?

You could enable a setting to automatically toggle between two themes; one for **daytime**, one for **night**. I might be in the minority group when I say I actually like light themes... it helps me "waken up" in the mornings. :stuck_out_tongue:

Now that I think of it, this could be turned into an API, so any and every theme can join in on the fun. This addition would really complement [f.lux](https://justgetflux.com) :sunny: 

No other text editor has this... yet.

WIndows 7 SP1, Atom 1.4.0. Here's a GIF of me switching between themes manually:

![atom-theme-switch](https://cloud.githubusercontent.com/assets/9056756/12421632/1df96e7a-be91-11e5-91d9-de76187beeb5.gif)
 
Atom 1.4.0
Tested on Windows 7 SP1 and Windows 10

**Comment by mnquintana** [comment]
This sounds like a really, really awesome idea for a package! (I too am a big fan of f.lux)

I think this is a little out of scope for settings-view though, so I'm going to close this out – however, I'd recommend posing this idea on [Discuss](https://discuss.atom.io) or Slack to see if anyone would be interested in building it (or maybe building it yourself if you'd be up for that :smile:).

**Comment by mfilenko** [comment]
Hey @citrusui,

Have you by any chance tried [sunset](https://atom.io/packages/sunset)?

Regards,
Max

**Comment by citrusui** [comment]
Nope, but I'll try it soon :D

**Comment by lednhatkhanh** [comment]
This is a very very awesome idea!
I am looking for a feature like this!

**Comment by FallingSnow** [comment]
This would be really useful. Maybe even have it use a laptop's ambient light sensor would be even better. Then use time of day as a fallback if the computer doesn't have an ambient light sensor.

**Comment by citrusui** [comment]
@FallingSnow you should check out [sunset.](https://atom.io/packages/sunset) This thread is already quite old.

**Comment by FallingSnow** [comment]
@citrusui Oh my, I can't believe I was one of those people that didn't read the whole issue :disappointed:. Thanks for pointing sunset out.
