### ISSUE TITLE
File encoding bug in Atom 1.3.3 when switching between UTF-8 and 'Western (Mac Roman)'

### ISSUE THREAD

**Issue by afischli** [atom/settings-view#728]
Repeat the bug:

1) Open a new file and save it as 'test-encoding.txt'
2) Switch encoding via Status-bar to 'Western (Mac Roman)'
3) Enter some Umlaute, e.g.  'äöüÄÖÜ' and save the file
4) Switch to 'UTF-8' encoding
5) Above entered string is transmogrified to '������' and becomes unreadable
6) Enter the same string (now in UTF-8) encoding and save the file
7) Switch back to 'Western (Mac Roman)' encoding
8) UTF-8 entered string correctly displays as '√§√∂√º√Ñ√ñ√ú' but originally entered string is corrupted

Bug: Originally with 'Western (Mac Roman)' encoding entered string 'äöüÄÖÜ' should now be restored as  originally entered (consistent with behavior of Atom in steps 6..8). However, the string changes to unreadable wrong sequence 'ÔøΩÔøΩÔøΩÔøΩÔøΩÔøΩ'. Perhaps this is a bug, which is related to Atom not understanding the difference between iconv options 'MACROMAN' and 'UTF-MAC' encoding.

I found out later, if you repeat step 4) and 7) (file saved and left unchanged since step 6) you regain the originally entered string. The bug appears only every 2nd time of switching. Since this is quite confusing I believe this is a bug, which should be fixed.

System: Atom 1.3.3, OS X 10.9.5 (Mavericks)

**Comment by lee-dohm** [comment]
This issue was moved to atom/encoding-selector#28
