### ISSUE TITLE
Add sort function to packages

### ISSUE THREAD

**Issue by juliusdanek** [atom/settings-view#729]
A sort function for packages would be great, like popularity, # of downloads, relevance, etc.

**Comment by tabascoeye** [comment]
since "number of downloads" is the only metric shown at the moment, I would also love to have a "sorting filter" for that.

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/settings-view/issues/384. You may want to subscribe there for updates.

**Comment by juliusdanek** [comment]
Thanks for pointing out. However, the other issue has remained unclosed for over a year now.
