### ISSUE TITLE
Disabled core packages show no README

### ISSUE THREAD

**Issue by mindrones** [atom/settings-view#730]
In the Settings/Packages, clicking on disabled packages, in the README section I get this:

![screen shot 2016-02-08 at 11 40 14](https://cloud.githubusercontent.com/assets/1309648/12883515/cbce9af8-ce58-11e5-983a-92231d3ea6fa.png)

while if they're enabled at Atom startup they show the README correctly.

_Specs_
- Atom: 1.5.0
- OS: OSX Yosemite 10.10.5

**Comment by 50Wliu** [comment]
I can only confirm this for core packages.  Community packages still display their READMEs when disabled.
