### ISSUE TITLE
Possible to install uninstallable packages

### ISSUE THREAD

**Issue by noseglid** [atom/settings-view#732]
Please see: https://github.com/abe33/uninstallable/issues/4

The `uninstallable` package shouldn't be possible to install on any Atom version lower than `99.0.0`. But there's seems to be some race between displaying the `install` button and the actual verification of the versions.

No biggie, but I thought I'd report it.

**Comment by sbrl** [comment]
What if I want to install a package anyway?

**Comment by 50Wliu** [comment]
You'll need to find an alternative.
