### ISSUE TITLE
Move `input[type="checkbox"]` styles to core

### ISSUE THREAD

**Issue by ssorallen** [atom/settings-view#740]
The Atom-style checkbox is great. Any chance it could be moved to core so we don't have to copy/paste the styles or add a `.settings-view` class name to get the styles applied?

**Comment by thomasjo** [comment]
Seems like a good idea to me! @simurai Any thoughts on this?

**Comment by simurai** [comment]
Yes, totally. :+1:

**Comment by ssorallen** [comment]
@simurai Thanks for providing checkboxes in core! I see they're available in v1.10+.

http://blog.atom.io/2016/08/31/atom-1-10-and-1-11-beta.html#new-ui-inputs
