### ISSUE TITLE
Move Development Packages to top when dev mode is enabled

### ISSUE THREAD

**Issue by nloomans** [atom/settings-view#741]
It is annoying to scroll all the way down in Packages when dev mode is enabled,
can we move the Development Packages section to the top when in dev mode?

**Comment by ZombieHippie** [comment]
Development packages should at the very least be above core packages by default.

**Comment by nloomans** [comment]
Tnx for the tip! Didn't notice that you can fold the groups together.

**Comment by damieng** [comment]
No plans to move dev to top although we are planning some reworking that will make these groups somewhat obsolete.
