### ISSUE TITLE
Maxed CPU when updating packages

### ISSUE THREAD

**Issue by ElegantScripting** [atom/settings-view#746]
### Prerequisites
- [N, but this is irrelevant, it's a bug in apm] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [Y] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [Y] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Updating an atom package takes 100% or more CPU.
### Steps to Reproduce
1. Be on Mac OS X El Capitan
2. Update a somewhat large package.
3. Close tab.

**Expected behavior:** It should have updated quietly.

**Actual behavior:** My fans turned on, my CPU was maxing out at 170% usage from apm.
### Versions

Latest version.

**Comment by lee-dohm** [comment]
Did you collect a CPU profile? If so, could you post it so that we can take a look?

**Comment by ElegantScripting** [comment]
What do you mean by CPU profile?

**Comment by lee-dohm** [comment]
It's mentioned in the debugging guide linked above.

**Comment by 50Wliu** [comment]
That debugging guide no longer links to the correct page.  Here's the link: http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance-problems-with-the-dev-tools-cpu-profiler

**Comment by ElegantScripting** [comment]
I'll try to get that profile next time I update a package. Until then: 
![screen shot 2016-04-24 at 2 47 42 pm](https://cloud.githubusercontent.com/assets/5307412/14769676/215be584-0a2c-11e6-9a02-16c22d225235.png)
