### ISSUE TITLE
Opening Settings tab causes incorrect scope name write in config.cson

### ISSUE THREAD

**Issue by aheckler** [atom/settings-view#747]
Here's a gist of my current `config.cson`: https://gist.github.com/aheckler/aeb7310a97c03866b87f

Note the `.source.gfm` scope at the bottom.

To reproduce:

1. Quit Atom.
2. Open `config.cson` in Atom.
3. Open the Settings tab via Atom > Preferences.

What I expected to happen: The Settings tab would open, but nothing else.

What actually happened: The Settings tab opened and overwrote this (in my config.cson):

```cson
".source.gfm":
  whitespace:
    removeTrailingWhitespace: false
```

... with this:

```cson
".gfm.source":
  whitespace:
    removeTrailingWhitespace: false
```

`.source.gfm` was incorrectly changed to `.gfm.source` which, as far as I can tell, is not a valid scope name. This happens even if I start Atom in safe mode.

Atom version 1.5.4 (installed via Homebrew)
language-gfm version 0.82.0
settings-view version 0.232.3

Mac OS X 10.11.3

**Comment by lee-dohm** [comment]
Because Atom scopes are used as CSS classes, ordering is not significant in this way. The two snippets you include are functionally equivalent. The scope keys are reordered in this way to allow for naïve duplicate checking.

Please let me know if I misunderstood your Issue!

**Comment by aheckler** [comment]
You understood it perfectly. :smile:  

However, it would still be nice to avoid this situation IMHO. For example, I keep my dotfiles (including Atom's `config.cson`) in a Git repo. This behavior causes essentially useless changes that I have to discard before every commit. 

Maybe it's a bit of an edge case, but it's definitely annoying. ¯\\_(ツ)_/¯

**Comment by lee-dohm** [comment]
> I keep my dotfiles (including Atom's config.cson) in a Git repo.

I do too: https://github.com/lee-dohm/dotfiles

> This behavior causes essentially useless changes that I have to discard before every commit.

This behavior reduces useless changes by having a stable ordering. The parts of the scope name are always in alphabetic order and the keys in the `config.cson` are stored in alphabetic order. At least, it prevents useless changes if you let Atom order things how it wants :grinning:

**Comment by aheckler** [comment]
Fair enough. :)
