### ISSUE TITLE
Package Management Uninstall reports "Does not exist" error for community packages

### ISSUE THREAD

**Issue by ZombieHippie** [atom/settings-view#760]
Because we use [`apm uninstall --hard <package>` in the package-manager.coffee file](https://github.com/atom/settings-view/blob/7e774f66f3861c1661c622696914a094946f0276/lib/package-manager.coffee#L356)

We receive an [error from apm about the package not existing](https://github.com/atom/apm/blob/0f74167051e187bd51fe9a431fb772adaf376e7c/src/uninstall.coffee#L77-L82) when `apm` attempts to uninstall the package with the `--hard` option.

![image](https://cloud.githubusercontent.com/assets/2925395/14238007/4ac4ff8c-f9f1-11e5-8e73-f8fdc7026459.png)

**Comment by ZombieHippie** [comment]
I've attempted to address this by offering the solution that if you execute uninstall with `--hard`, then apm should not throw an error if it does not exist. https://github.com/atom/apm/pull/539

**Comment by ZombieHippie** [comment]
Note: this is incredibly frustrating because settings-view does not remove the package from the list until you restart, because it "fails to uninstall" when there is a package does not exist error.

**Comment by XzAeRo** [comment]
Same thing happened to me.

When uninstalling via `apm` or via `settings-view`, an error is thrown indicating the package doesn't exist. But when Atom is restarted, the packages are effectively removed.

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#11464.
