### ISSUE TITLE
Not able to set a modul tab length to default if main settings are different

### ISSUE THREAD

**Issue by henri-hulski** [atom/settings-view#774]
### Description

I'm not able to set the tab length to the default value (2) in a language modul if I set a value in the main settings tab length,
It immediately changes to the tab length from the main settings.

__See issue atom/atom#11546.__
And also issues Lukasa/language-restructuredtext#37 and atom/language-gfm#134.

### Steps to Reproduce

1. Set tab length in main settings to 4.
2. Go to the settings of language-html package and set the tab length to 2.
3. It immediately changes to 4.
4. When you leave it empty it shows `Default: 2`. But then also changes to 4. 

It should possible to change the value to the default 2.
Now you can change it to every other value (1,3,5,etc) but not to 2.

### Versions
Atom 1.7.2 and 1.8.0-beta2

**Comment by lee-dohm** [comment]
Thanks very much! I reproduced this using Atom v1.7.2 on Mac OS X 10.11.4.

**Comment by leohacker** [comment]
Have the same issue. Why not use 4 as the default value for editor ?

**Comment by slavadir** [comment]
Confirmed with Atom 1.8.0, on Windows 10 64bit.
Note that in python, where the default tab length is 4 and not 2, the behavior is different.

**Comment by maxbrunsfeld** [comment]
Wow sorry for this terrible experience everyone. Fixing now.

**Comment by maxbrunsfeld** [comment]
This fix will be released in Atom 1.12.

**Comment by sangdth** [comment]
I still meet this problem in Atom 1.19. And have to work around by using this https://github.com/gandm/language-babel/issues/191

**Comment by lee-dohm** [comment]
@sangdth I just tried to reproduce the issue listed above using Atom v1.19.2 on Mac OS X 10.12.6 and could not. If you are experiencing a reproducible problem, please open a new issue.

**Comment by AdrianChirila** [comment]
I still reproduce this using atom-typescript package.

**Comment by sangdth** [comment]
@lee-dohm I disable/uninstall all lint related and the problem was gone. I'm using 1.21.1 Atom.

**Comment by msukmanowsky** [comment]
I can still reproduce this with Atom 1.25.1 and `language-babel` (editing tab size for `Babel ES6 JavaScript Grammar`).
