### ISSUE TITLE
Uninstalling “package xyz” failed

### ISSUE THREAD

**Issue by rm-code** [atom/settings-view#789]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? (Hopefully)
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When I try to deinstall a package I get the following error:
![screenshot 2016-05-17 13 02 28](https://cloud.githubusercontent.com/assets/11627131/15320224/ab362340-1c2f-11e6-8689-67c82aacf3bf.png)

The package still shows up in the list of installed packages, but as soon as I restart Atom it is gone (and seems to be deinstalled from the system correctly). This seems to happen with every 3rd party package.

### Log
```
Uninstalling package language-lua failed Error: Uninstalling “language-lua” failed.
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:504:21
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12) Failed to delete language-lua: Does not exist
```

### Versions

Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4

OS: OSX 10.11.4

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0.
