### ISSUE TITLE
Unable to disable 80 char guide

### ISSUE THREAD

**Issue by jglovier** [atom/settings-view#790]
I'm getting Atom setup on a new machine. I'm trying to get rid of the 80 character guide, but cannot seem to find a way to disable it. 

I thought it used to be in Settings as a checkbox with a value you could adjust for the length, but either my memory is incorrect, or it has been changed. I also checked under the View menu, but there is no toggle for it there, either.

@shiftkey pointed out that on his machine setting `Preferred Line Length` to `0` seems to be doing it, but for me that doesn't actually work as setting a `0` value results in Atom automatically changing the value to `1`, which just overlays the line at the 1 character column.

Even more strange about the previous point is that I don't even have `Soft Wrap At Preferred Line Length` checked, so if anything I would assume that `Preferred Line Length` should not be in effect until this is checked.

Hope my description is clear. Hollar if I can provide any more info.

My Atom build is `1.7.3` and I'm on `OSX 10.11.5`.

:heart:

**Comment by 50Wliu** [comment]
You can disable the `wrap-guide` package :).

**Comment by simurai** [comment]
> Even more strange about the previous point is that I don't even have `Soft Wrap At Preferred Line Length` checked, so if anything I would assume that `Preferred Line Length` should not be in effect until this is checked.

Yeah, I was thinking the exact same. But there might be people that just want the line as a visual guide and then insert new lines manually. Maybe just for comments.

> You can disable the `wrap-guide` package :).

It's probably pretty hard to figure out that "the line" is the `wrap-guide` package. Maybe for `2.0` we can make it part of core with a setting to show/hide.

**Comment by jglovier** [comment]
>It's probably pretty hard to figure out that "the line" is the wrap-guide package. Maybe for 2.0 we can make it part of core with a setting to show/hide.

Yeah, that would be ✨. IMO ideally it would be in the `View` menu directly under the `Toggle Soft Wrap` options as `Toggle Soft Wrap Guide`.
