### ISSUE TITLE
"Preferences..." opens "Settings"

### ISSUE THREAD

**Issue by ryanseys** [atom/settings-view#80]
Just an inconsistency in the naming. "Preferences..." in the Atom menu. Also, Cmd+Shift+P and searching for "Preferences" won't give you the option to open them because technically they are "Settings".

Not sure if you'll fix or find a compromise of some sort to clear any confusion. :smile:

**Comment by jlord** [comment]
:wave: I'm going through back issues and took a look at how Settings/Preferences are today in Atom. Currently you can get to them by searching either "settings" or "preferences", which it seems wasn't the case when this issue was first opened. 

Gonna close as there should hopefully be less confusion now since you can get to it with both terms :+1:

**Comment by izuzak** [comment]
Noticed another report of this in https://github.com/atom/atom/issues/6929 by @bobrocke:

> The menu item is Preferences... but the resulting window tab is Settings. They should be consistently named.

Also, I just tried typing "preferences" into the command palette and couldn't find anything:

![screen shot 2015-05-24 at 18 33 14](https://cloud.githubusercontent.com/assets/38924/7788657/226c6f7a-0244-11e5-91de-333e2549744e.png)

@jlord just to make sure -- are you seeing something different? I'm on Atom 0.202.0-08c4e8e.

**Comment by jlord** [comment]
@izuzak oh, when I said "searching" I meant in the native 'Help' menu, not Atom's command palette—but that's a good point; it should be accessible as Preferences (if we're going to call it that in the menu) from there, too. 

![screen shot 2015-05-26 at 2 32 53 pm](https://cloud.githubusercontent.com/assets/1305617/7823979/32a03072-03b4-11e5-922b-05c4398090c6.png)
![screen shot 2015-05-26 at 2 33 24 pm](https://cloud.githubusercontent.com/assets/1305617/7823981/32c978b0-03b4-11e5-844f-8f344c016151.png)

I think being consistent would be nice so it would be nice to pick one route. Curious, are we calling it 'Preferences' in the menu on Win/Linux?

**Comment by mnquintana** [comment]
@jlord Nope, it's Settings on Windows: https://github.com/atom/atom/blob/master/menus/win32.cson#L12 (But Linux gets Preferences too)
