### ISSUE TITLE
quick search for options

### ISSUE THREAD

**Issue by ruv** [atom/settings-view#807]
Why does text searching (find text, `Ctrl+F`) doesn't work on Settings page? "Find in Current Buffer" panel can be opened but nothing can be found.

Without a filter, the simple search would be a good alternative.

**Comment by Ben3eeE** [comment]
https://github.com/atom/settings-view/issues/781?

**Comment by ruv** [comment]
Yes, all other sections (Keybindings, Packages, Themes)  already have the filter tool, and it is worth to have such filter in Editor Settings section too.

Nevertheless, I suggest here an easier solution (at least it seems so) — just to support the search within plain text as in ordinary text editing pages.

**Comment by 50Wliu** [comment]
This is a duplicate of #394 - feel free to subscribe there for updates.
