### ISSUE TITLE
[request] Add settings-view:show-settings to API

### ISSUE THREAD

**Issue by refkotay** [atom/settings-view#812]
Current options see the settings view is open and do nothing. Expected behavior would be a command to show (reveal) the Settings panel aka 'core settings' while the settings view is already open.

I can make simple buttons for the other commands
```coffeescript
      @addButton('icon-keyboard', 'settings-view:show-keybindings')
```
~~But for core settings it's quite difficult.~~ Core settings uri was broken at the time
```coffeescript
      @addButton('icon-settings', () ->
         atom.workspace.open 'atom://config'
         process.nextTick () ->
            atom.workspace.getActivePaneItem().element.firstChild.firstChild.firstChild.firstChild.click()
      )
```
I would appreciate any alternatives in the meantime!
Just in case, I'm running 1.9-beta on Ubuntu

**Comment by 50Wliu** [comment]
I believe this has been added in #811 - @damieng?

**Comment by damieng** [comment]
Yes, it is although the command name is settings-view:core as the settings have been broken out into core and editor.

**Comment by refkotay** [comment]
I'm convinced that it's a bug in `atom.workspace.open`. I have had three of the six commands fail to completely resolve, often lasting for multiple sessions, then magically working again. The settings-view is always opened if necessary, but the panels are a lottery. You should definitely close this issue as the problem lies elsewhere.

Personally as a user I would get the `('settings-view').mainModule` and call `showPanel('core')`. If you guys want to trust on faith that workspace.open is busted, you might want to do the same thing, but I realize you don't have a lot to go off : )

FYI this is what I had that was breaking randomly
```coffeescript
   addSettingsViewButtons: ->
      @addButton 'settingsView', 'settings', 'settings', () -> atom.workspace.open 'atom://config/settings'
      @addButton 'settingsView', 'keyboard', 'keybindings', () -> atom.workspace.open 'atom://config/keybindings'
      @addButton 'settingsView', 'package', 'packages',  () -> atom.workspace.open 'atom://config/packages'
      @addButton 'settingsView', 'paintcan', 'themes', () -> atom.workspace.open 'atom://config/themes'
      @addButton 'settingsView', 'cloud-download', 'update-packages',() -> atom.workspace.open 'atom://config/updates'
      @addButton 'settingsView', 'plus', 'install-packages', () -> atom.workspace.open 'atom://config/install'
```

**Comment by Ben3eeE** [comment]
https://github.com/atom/settings-view/issues/744 is also about adding a `settings-view:core` command?
