### ISSUE TITLE
"Install" button is shown for disabled package after reloading detail view

### ISSUE THREAD

**Issue by ypresto** [atom/settings-view#817]
![image](https://cloud.githubusercontent.com/assets/400558/17087220/fca941bc-523f-11e6-8d26-0e8868bff51a.png)

Reproduced with 0.240.1
### Steps to reproduce
1. Show Packages
2. Select single package to show detail
3. Disable the package (if enabled)
4. Run window:reload command
### Behavior
- Expected: "Enable" button is shown
- Actual: "Install" button is shown

**Comment by Ben3eeE** [comment]
Confirmed on Windows 7 when restarting Atom with the detail view open.

**Comment by 50Wliu** [comment]
Figured out the issue.
`else if packageNames = @getAvailablePackageNames()` doesn't work before `@getInstalled()` is called because the package names cache is empty.
