### ISSUE TITLE
Settings-view overflows when pane is narrow

### ISSUE THREAD

**Issue by frantic1048** [atom/settings-view#821]
environment information:

- Atom    : 1.8.0
- Electron: 0.36.12
- Chrome  : 47.0.2526.110
- Node    : 5.1.1
- settings-view    : 0.241.0
- OS: Arch Linux latest

These days I'm writing my transparent styled ui theme. I found settings-view overflows, when pane is narrow.

![transparent_overflow_sm](https://cloud.githubusercontent.com/assets/3102803/17246173/e948685c-55bc-11e6-82ea-1bfba553cae8.gif)

Though in solid backgound themes we cannot see the overflowed content. I found another weird behavoir:  at `Install Packages` package/theme buttons.

![solid_overflow_sm](https://cloud.githubusercontent.com/assets/3102803/17246177/ecce0360-55bc-11e6-97fd-235bc07947d5.gif)

I think `overflow: auto` should be appropriate for it. And here's the fixed preview. Also weird package/theme buttons go away..

![fixed_sm](https://cloud.githubusercontent.com/assets/3102803/17246180/f04c010e-55bc-11e6-84d7-61184f1542f4.gif)

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.10.0-dev-7e006cd, Windows 10 x64.  /cc @simurai
