### ISSUE TITLE
Color picker value resets everytime

### ISSUE THREAD

**Issue by silvestreh** [atom/settings-view#832]
I've been having a problem with the color picker in Atom built from source. Last time I built it was today, August 22, 2016.

I really can't reproduce it in safe mode because no third-party packages are loaded in safe mode. I mean, I don't have access to a color picker to try in safe mode.

I created a new entry in my theme's config schema:

```json
"test": {
    "title": "Test color",
    "description": "This color picker does nothing. Has no code bound to its events.",
    "type": "color",
    "default": "#000000"
},
```

This new color picker has no JavaScript code bound to its changes. If you'd like, install [atom-material-ui](https://atom.io/packages/atom-material-ui) and try changing the theme's base or accent colors. I know it's not an isolated issue because it's been reported at atom-material/atom-material-ui#318 using a different OS.

### System Info

**Atom version**: 1.11.0-dev-89c638a (built on August 22, 2016)
**OS**: Mac OS X El Capitan 10.11.6

### Installed Packages

```shell
$apm list --installed
Community Packages (3) /Users/silvestre/.atom/packages
├── atom-material-ui@1.3.4
├── pigments@0.31.2
└── terminal-plus@0.14.5
```

### Reproduction steps

1. Open a package's settings which includes a color picker.
2. Change its value.

**Expected behavior**: The color picker retains the new value.
**Observed behavior**: The color picker gets reset to its default value.

### GIF Showing the issue

![colorpicker](https://cloud.githubusercontent.com/assets/1133339/17878818/0a032450-68c4-11e6-8ef5-4355e52588d5.gif)

### Extra information

* Problem can be reproduced in safe mode: *Can't test for the reason stated above*
* Problem started happening recently, didn't happen in an older version of Atom: *Yes*
* Problem can be reliably reproduced, doesn't happen randomly: *Yes*
* Problem happens with all files and projects, not only some files or projects: *Yes*

**Comment by damieng** [comment]
Also able to repro this.

**Comment by simurai** [comment]
```error
/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:1000

Error setting item in object: Validation failed at atom-material-ui.colors.abaseColor, {"_red":115,"_green":250,"_blue":121,"_alpha":1} cannot be coerced into a color
```

**Comment by simurai** [comment]
No, that's just the error message I get. I can repro with another theme too.

**Comment by damieng** [comment]
Hey @maxbrunsfeld this looks like it's caused by the Color rewrite to JS?  https://github.com/atom/atom/commit/3fd275a7f65781cc6eb55b0f3f2c48656aad80ed#diff-0795b1359a919ee59d7510baa3d94359
