### ISSUE TITLE
Font Family: 'Monaco' not applied to editor

### ISSUE THREAD

**Issue by preetb123** [atom/settings-view#834]
editor text font not changing even after setting font familty as 'Monaco'

**Comment by damieng** [comment]
I just tried this and it works fine here.

Can you go into the Atom menu and select Atom > Stylesheet and make sure you don't have any font-family CSS rules listed in that file.

Additionally are you using the default UI and syntax themes?  Some third party themes might override your choice.

**Comment by preetb123** [comment]
I have added Nuclide with everything default. My Atom -> Stylesheet

```
// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

**Comment by preetb123** [comment]
Issue solved after uninstalling `https://atom.io/packages/fonts`. Thanks!

**Comment by barbu110** [comment]
@preetb123 I have also installed the `fonts` package but I don't get **Monaco** in the list of fonts, although I have it installed on my system.

Could you reopen this if you have anything that could help me, please?

**Comment by damieng** [comment]
The solution appears to be to unload that package as it overrides things.

If you have Monaco installed you should just be able to specify it in your editor settings.

**Comment by ShivaShankarPuvvada** [comment]
## Adding Monaco font to ATOM:
[https://wealthyheart.wordpress.com/2017/11/11/best-way-to-load-apply-custom-fonts-in-atom/](url)

**Comment by damieng** [comment]
Download link removed as Monaco is a copyrighted font.
