### ISSUE TITLE
Unable to confirm package search with enter key

### ISSUE THREAD

**Issue by Ben3eeE** [atom/settings-view#836]
### Description
After reopening the `settings-view` I am are unable to confirm a search for packages with the <kbd>Enter</kbd> key if I visited the install packages tab.

### Steps to reproduce
1. Open a new empty Atom window in safe mode.
2. Run the `settings-view:install-packages-and-themes` command.
3. Close the `settings-view`.
4. Reopen the `settings-view` for example with <kbd>Ctrl+,</kbd>.
5. Type `package` in the package search field and try to confirm the search with <kbd>Enter</kbd>.

### Expected
`settings-view` to search for `package` packages.

### Actual
`settings-view` doesn't search for anything. Only solution is to restart Atom or search by clicking the `Packages` button.

### Gif
First open and searching for `git` works, after reopening it does not work.
![search with enter2](https://cloud.githubusercontent.com/assets/1058982/18242673/b6aab5ea-7357-11e6-84f8-822c5436e677.gif)

### Versions
Atom 1.10 Windows 7.

**Comment by thomasjo** [comment]
I was able to reproduce this.

**Comment by Akumetsu-Dev** [comment]
Same with win10 x64

**Comment by damieng** [comment]
Fixed in dbd5186d0d808a57194fcbf32639f3cd612aabfa

**Comment by damieng** [comment]
Went out in 1.10.2 and 1.11.0-beta5
