### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by KurokAhri** [atom/settings-view#839]
![](http://puu.sh/r8tki/0660528441.png)

`
function putMemes()
{

    var array = {};

    fs.readFile("memes.txt", "utf8", function (err,data) {

        if (err) {

            return console.log(err);

        }

        console.log(data);

        var memesplit = data.split('\n');

        for(var m in memesplit)

        {

            var split_m = memesplit[m].split('\t');

            array[split_m[0]] = split_m[1].substr(0, split_m[1].length);

        }

    });

    return array;
} `
Its a bot for discord. been trying to fix this forever.

**Comment by 50Wliu** [comment]
Not related to Atom.
