### ISSUE TITLE
Package system error (\QuickTime\QTSystem\ was unexpected at this time.)

### ISSUE THREAD

**Issue by caiom** [atom/settings-view#847]
Hello, I have a fresh install of Atom (1.10.2) on Windows 10 and I have this error for everything (Fetching featured packages, Search package) on the +install tab:
![2016-09-17](https://cloud.githubusercontent.com/assets/10866874/18609198/94e1aaf2-7cd2-11e6-9542-f18dfabdea8f.png)

"\QuickTime\QTSystem\ was unexpected at this time."

I could not find on the internet, so I'm posting here.

Best regards,

**Comment by 50Wliu** [comment]
Can you open up `cmd.exe`, type `echo %PATH%`, and paste the output here?  Thanks.

**Comment by damieng** [comment]
I suspect you have an entry in your PATH that has quotes around it which are not required or recommended in there.   The easiest fix is to edit your PATH to remove unnecessary quotes around entries.

APM which manages Atom packages recently had an improvement where it will find and use a git.exe from GitHub Desktop if one is not already present. 

Unfortunately if quoted entries are in the PATH it gets confused. The next version of APM should work around this issue.
