### ISSUE TITLE
fetching featured packgage failed

### ISSUE THREAD

**Issue by perdisita** [atom/settings-view#849]
I have the next error message:
Fetching featured packages failed.Hide output…
No se esperaba \Android\android-sdk\platform-tools";"C:\Program en este momento.

What's wrong?

thanks

**Comment by damieng** [comment]
You have an entry in your PATH variables that has quotes around it . While quotes are normally required around folder names with spaces they are not recommended in the PATH variable.

A future update to APM will handle this unusual case better but in the mean time I recommend removing the quotes around the PATH entries.

**Comment by perdisita** [comment]
But this problem has suddenly appeared. I have windows 10 and there is and editor where I haven't got any quote.

**Comment by damieng** [comment]
Yes, we updated APM recently to automatically add git to the PATH if you have GitHub Desktop installed but do not have git.exe on your PATH.  It did not take double-quotes in existing paths into consideration.

You can see directly if you have quotes by typing the following in a command prompt;

```
echo $PATH
```

**Comment by perdisita** [comment]
`Microsoft Windows [Versión 10.0.10586]
(c) 2015 Microsoft Corporation. Todos los derechos reservados.

C:\Users\editor>echo $PATH
$PATH

C:\Users\editor>echo $PATH
$PATH

C:\Users\editor>echo %path%
C:\wamp\bin\apache\apache2.4.2\bin;C:\wamp\bin\mysql\mysql5.5.24\bin;C:\wamp\bin\php\php5.4.3;C:\Python33\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\wbem;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\QuickTime\QTSystem;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Java\jdk1.7.0_21\bin;"C:\Program Files (x86)\Android\android-sdk\platform-tools";"C:\Program Files (x86)\Android\android-sdk\tools";C:\Development\apache-ant-1.9.1\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Git\cmd;C:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\editor\AppData\Local\atom\bin;C:\Users\editor\AppData\Roaming\npm

C:\Users\editor>`

You're right. I have quotes. How I can remove in Windows 10?

**Comment by perdisita** [comment]
thanks... I found the quotes!! thanks for your help

**Comment by damieng** [comment]
Press the Windows key and type path

Then click the *Edit the environment variables*

**Comment by damieng** [comment]
No problem. Sorry for the inconvenience. The next update to APM works around this slightly unusual configuration.
