### ISSUE TITLE
Settings subheaders

### ISSUE THREAD

**Issue by tcarlsen** [atom/settings-view#87]
I would love to see the posibility to add subheaders inside the package settings

```javascript
configDefaults: {
    validateOnSave: true,
    validateOnChange: false,
    hideOnNoErrors: false,
    useFoldModeAsDefault: false,
    rules: {
      'tagname-lowercase': true,
      'attr-lowercase': true,
      'attr-value-double-quotes': true,
      'doctype-first': true,
      'tag-pair': true,
      'spec-char-escape': true,
      'id-unique': true,
      'src-not-empty': true
    },
  }
```

Resolves in this, but it should make a sub header called Rules, and then show all rule properties 
![](http://note.io/1igz9bI)

**Comment by 50Wliu** [comment]
Has this been added with #698?  /cc @dirk-thomas

**Comment by dirk-thomas** [comment]
I haven't seen the short notation above to specify rules but the PR #698 has some example configuration as well as screen shots. I would think this was exactly the functionality requested here.

Also see atom/atom#10552 to clarify the grouping functionality in the documentation.

**Comment by 50Wliu** [comment]
Awesome, thanks for chiming in!
