### ISSUE TITLE
Needs documentation about re-enabling Settings View in case of inadvertently disabling the plugin

### ISSUE THREAD

**Issue by jeffswt** [atom/settings-view#881]
When I was being sleepless I disabled `settings-view` in `settings-view` and it immediately allowed me to do that!

Now none of my packages can be enabled.

Can you please put an announcement or a solution in the README, or add something that alerts the user of this situation, or simple disable the behavior of disabling this plugin itself?

This kind of frustrates me.

**Comment by 50Wliu** [comment]
I'm :-1: on this. If people want to disable the Settings View, we should let them as for the most part it's just a visual interface to `apm` and `config.cson`.

/cc @atom/feedback

**Comment by damieng** [comment]
As long as users can find the solution of `apm enable settings-view` we're good.  Maybe put that in the docs somewhere?

**Comment by jeffswt** [comment]
@50Wliu It took me about a minute to find the `config.cson` solution before you mentioned this, but thanks.

Mutanti mutantes, I know that this Settings View should be able to disable itself. In any way since it is a visualized interface it should give users the utmost freedom to tweak things.

But I believe that there is a necessity to put this issue into the Q&A section in case there is a chance that inexperienced users might disable this `settings-view` and not being able to switch it back on. @damieng

**Comment by damieng** [comment]
I think people will probably hit their search engine of choice and hopefully end up here.  If it's hard to solve we'll see more issues here.

**Comment by pheraph** [comment]
Ended here because I accidentally disabled the plugin. Removing the plugin from the disabled section in my config file helped.
