### ISSUE TITLE
Outdated package doesn't show in updates panel if it failed to update

### ISSUE THREAD

**Issue by 50Wliu** [atom/settings-view#886]
Here's a nice little GIF to explain.
![failed-updates-no-show](https://cloud.githubusercontent.com/assets/2766036/20993246/0917e37c-bcb7-11e6-879a-b6e9450b2aeb.gif)

Reloading Atom properly displays the update again.

Note: I'm on a different branch, but I'm pretty sure what I'm working on doesn't interfere with this in any way.

**Comment by eboracus** [comment]
Yes I've experienced something that seemed similar to this - in my case multiple updates in parallel, 1 or more fail, others succeed, failed packages no longer show as 'update-able', press `Check for Updates` to attempt to refresh and no updates show as above. This on stable release channel versions (didn't record which versions on the times I experienced it though :/ )

Tried just now to force a reproduction on 1.12.6, but `Check for Updates` worked after the "Updating to <package version> failed" error appears (package in question the `Script` package). Though could it depend on the reason for the failure and the specific error experienced, as I manually forced it to time out given that I expected the update to succeed 😕 :? What error occured in the above case?

Attempted steps (manually forced the update to fail):

- Click `Check for Updates` -> update is found
- Click `Update`
- Turn of connection to server/internet -> update times out, "ETIMEOUT" error
- Click `Check for Updates` again -> same update was found sucessfully

**Comment by 50Wliu** [comment]
Yeah, my case was a controlled failure so that I could consistently reproduce this bug.  An easy way to do it without turning off your internet connection is to open up your terminal and cd to the package directory you want to update (in my case, `%userprofile%\.atom\packages\file-icons`).  Then, at least for Windows, Atom will throw an EBUSY error when trying to access file-icons.

**Comment by eboracus** [comment]
I just tried this [enter package in question in terminal] and recieved no EBUSY error - on Mac (10.11). Tried on Windows and do indeed see EBUSY (and can then, with that error, repro the issue). Didn't know command prompt and terminal have a different effect when actively sitting inside a directory.

I see the PR is up so largely academic now anyway I guess, but posting for info anyway.
