### ISSUE TITLE
Settings view allows installation of version not supported by current version

### ISSUE THREAD

**Issue by deshiknaves** [atom/settings-view#891]
The is a previous pull request that sounds similar to this https://github.com/atom/settings-view/pull/377 - but it is not the same issue.

When you search for a plugin - for example: vim-mode-plus. Initially it shows the latest version and then after a few seconds, it shows the message:

Version 0.66.1 is not the latest version available for this package, but it's the latest that is compatible with your version of Atom.

During those few seconds, if you click install, it will install 0.72 instead of 0.66.1. It took me quite a few goes and discussion with the plugin author to realize that I was just clicking too fast.

Maybe install button should only show up once the check has been completed?

**Comment by 50Wliu** [comment]
This was fixed (again) in https://github.com/atom/settings-view/commit/a7010babf7ffa3ee261ec014f7064839918b89d7.  It should be out in Atom 1.14.0.
