### ISSUE TITLE
Downloads counter not working

### ISSUE THREAD

**Issue by uwnot** [atom/settings-view#914]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It should show the total of downloads aside the cloud icon

### Steps to Reproduce

1. Open Install package window
1. Search something
**Expected behavior:** [What you expect to happen]
Should show total of downloads for each package

**Actual behavior:** [What actually happens]
Doesn't show

![aa](https://cloud.githubusercontent.com/assets/197329/23169158/70b3034c-f829-11e6-8351-9dc4956af21c.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions

atom --version

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python
git 2.11.1.windows.1
visual studio

### Additional Information
Windows 10.14393.447

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by alice-gh** [comment]
Hmm, I wasn't able to reproduce on Windows 10 + Atom 1.14.3.  Did this issue just start for you on 1.14.3?

**Comment by rsese** [comment]
Hmm, I wasn't able to reproduce on Windows 10 + Atom 1.14.3. Did this issue just start for you on 1.14.3?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/914#issuecomment-282084682. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
