### ISSUE TITLE
Tooltips for default settings are not disposed properly

### ISSUE THREAD

**Issue by jgebhardt** [atom/settings-view#915]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the "editor" settings, the [newly added]( https://github.com/atom/settings-view/commit/65a6e66481a421a9b584859df59d9ab368087551) tooltips indicating default values are not actually disposed when the editor pane is closed.

### Steps to Reproduce

1. Open Atom 1.15.0-beta2
2. Open Settings > Editor
3. Focus on e.g. "Invisibles" --> a tooltip showing the default character (`¤`) will show up.
4. With the input field in focus, press `cmd+w` / `core:close` to close the settings view.

**Expected behavior:**
Tooltip goes away.

**Actual behavior:** [What actually happens]
Tooltip stays behind

**Reproduces how often:**
100% of the time in Atom 1.15. 
Does not reproduce in Atom 1.14.2.

**Screenshots**
Right before closing the settings view:
<img width="778" alt="screenshot 2017-02-22 17 54 17" src="https://cloud.githubusercontent.com/assets/632968/23241468/045cf4b4-f928-11e6-8027-871b4da030a8.png">

After closing, the tooltip remained behind:
<img width="781" alt="screenshot 2017-02-22 17 54 26" src="https://cloud.githubusercontent.com/assets/632968/23241471/0967ad8c-f928-11e6-98de-f85f4c989966.png">

**Comment by 50Wliu** [comment]
No more repro, looks like this was fixed in the interim.
