### ISSUE TITLE
Fetching outdated packages and themes failed.

### ISSUE THREAD

**Issue by pustovalov** [atom/settings-view#921]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have problem here:
https://github.com/atom/settings-view/blob/master/lib/package-manager.coffee#L141

### Steps to Reproduce

1. CMD+,
2. Click "Updates"

**Expected behavior:** See updates for packages

**Actual behavior:** Fetching outdated packages and themes failed.

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

1.15.0
OS: macOS 10.12.3

### Additional Information

![](https://monosnap.com/file/Y5zlhbcy3hJkRf4gz0Hpa0CoWJLZg0.png)

```
apmProcess = @runCommand args, (code, stdout, stderr) =>
  console.log("code", code)
  console.log("stdout", stdout)
  console.log("stderr", stderr)
```

```
code 1
stdout 
stderr undefined
```

**Comment by 50Wliu** [comment]
Uninstall seti-syntax for now.
