### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by wenweih** [atom/settings-view#936]
You have the core package "settings-view" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:32)
```

**Comment by 50Wliu** [comment]
You have the core package "settings-view" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

**Comment by wenweih** [comment]
@50Wliu many thanks !
