### ISSUE TITLE
unexpected border line in settings

### ISSUE THREAD

**Issue by unluisco** [atom/settings-view#952]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi, in atom settings, there is a border line that I think that don't should be there.
![settings 2017-05-16 16-00-36](https://cloud.githubusercontent.com/assets/6332263/26129451/e31d414a-3a55-11e7-8932-d4c829202ef2.png)
It is only in Core and Editor settings.

### Steps to Reproduce

1. Open Atom.
2. Go to settings.
3. And there is the border line.

**Expected behavior:**  There not should be that line. 

**Actual behavior:** There is that line.

**Reproduces how often:** 100%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0a

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.13.0

OS: macOS Sierra 10.12.4

### Additional Information

It is only a design topic.
@lee-dohm :)

**Comment by rsese** [comment]
Hmmm, I don't see the red border line at `Settings > Core` on 1.17.0 and macOS 10.12.4.  Do you have any custom CSS in your `styles.less` file?

**Comment by rsese** [comment]
(I tried both Atom Dark and One Dark 🎨)

**Comment by damieng** [comment]
I think he is referring to the extra black line above it that cuts across the tab.

**Comment by rsese** [comment]
Ahhh thanks @damieng, my 👓  failed me and I should have recognized that Skitch-ish type line right away 😊 

Which theme are you using @unluisco?  Looks kinda like One Dark?

**Comment by rsese** [comment]
Just tried One Dark and see the same thing in `Core` and `Editor` - there's a similar-ish issue with Atom dark where the top border is slightly different in `Core` and `Editor` as well.

**Comment by rsese** [comment]
@damieng pointed out the error is likely at:

https://github.com/atom/settings-view/blob/3064b396d6987074f420d7f3af9a355936957ed0/styles/settings-view.less#L183

He also mentions:

> i think basically those first two panes need to not have that style applied.

> we still need that style for the sections in packages tho i believe

> so either the css rule has to change specificity or the panes have to opt-out of it

Thanks again for reporting @unluisco :v:

**Comment by unluisco** [comment]
Hi, this will be fixed soon?
