### ISSUE TITLE
Update notification and status message of disabled packages

### ISSUE THREAD

**Issue by KSXGitHub** [atom/settings-view#955]
Moved from [this issue](https://github.com/atom/update-package-dependencies/issues/17)

> ### Description
>
> 1. Disabled packages should not be counted (`(N) Updates` message at the bottom-right corner)
>
> 2. Notification should not tell user to restart Atom to apply changes to disabled packages (or, notification shouldn't show up at all) because it makes no sense and just annoying

**Comment by 50Wliu** [comment]
> Disabled packages should not be counted ((N) Updates message at the bottom-right corner)

Should be a quick fix.

> Notification should not tell user to restart Atom to apply changes to disabled packages (or, notification shouldn't show up at all) because it makes no sense and just annoying

Should also be a quick fix.

Sorry for asking you to move issues again, but could you please separate this into two separate issues so that we can track each one individually?
