### ISSUE TITLE
Can't test/reinstall package while developing it

### ISSUE THREAD

**Issue by RobertBColton** [atom/settings-view#961]
### Description

Ok so I accidentally uninstalled a package I was working on from the settings menu just to see what it would do. Now I can't seem to figure out how to reload it at all. I've tried reloading the window, restarting Atom, and looking to see if it was on any sort of blacklist in Atom's config folder. Nothing has led to any solutions and I'd really like to know how I can get Atom to start recognizing my package again so that I can continue working on it.

### Steps to Reproduce

1. Use the package generator to start work on a new package
2. Go to the settings menu and uninstall the package

**Expected behavior:** Should be able to reinstall the package.

**Actual behavior:** The package permanently disappears.

**Reproduces how often:** Always

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.8
git
visual studio 2015

Windows 10

**Comment by rsese** [comment]
I poked at this a bit and see that the package generator creates a symlink from `%USERPROFILE%\.atom\packages\YOUR_PACKAGE_NAME` to wherever you choose to create the project on your computer.  Uninstalling looks like it just deletes the symlink so to get it back, you can manually re-create the symlink.  I had to look it up but on Windows I think you can do it like this from cmd.exe (you need to run as administrator):

```
mklink /D %USERPROFILE%\.atom\package\YOUR_PACKAGE_NAME %USERPROFILE%\path\to\your\project
```

Your package should then show up as installed again.

**Comment by RobertBColton** [comment]
That did it but perhaps some kind of documentation could be added about this? Maybe adding it to the first tutorial that uses the package generator?

**Comment by thomasjo** [comment]
Documentation could be better I suppose, but the relevant details can be found here: http://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/#hacking-on-packages

Please note that you should not manually create symlinks, but instead use the documented `apm link -d <your-package-name-here>` functionality. It is highly recommended that you only link packages that you are actively working on, in "development mode" (which is what the `-d` flag controls). By doing that, you ensure a stable and functional Atom environment that you can use to develop your package. To manually test your package while developing it, simply launch Atom in development mode via e.g. `atom -d`.

**Comment by rsese** [comment]
> Please note that you should not manually create symlinks, but instead use the documented apm link -d <your-package-name-here> functionality. It is highly recommended that you only link packages that you are actively working on, in "development mode" (which is what the -d flag controls). By doing that, you ensure a stable and functional Atom environment that you can use to develop your package. To manually test your package while developing it, simply launch Atom in development mode via e.g. atom -d.

Ohhh thanks for these details and the correction @thomasjo, super helpful 📝
