### ISSUE TITLE
There is not margin between Update all and Check for updates buttons

### ISSUE THREAD

**Issue by abaracedo** [atom/settings-view#993]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The other day I saw that the Update all and Check for updates buttons do not have a margin between them.

That is how it looks in normal and safe mode.

<img width="759" alt="normal_mode" src="https://user-images.githubusercontent.com/9487675/30252313-7ae7af9e-9670-11e7-8d83-81f40ef46c4e.png">

I have cloned the settings-view project to check the error and try to fix it but when I looked for it, it is shown correctly.

<img width="748" alt="dev_mode" src="https://user-images.githubusercontent.com/9487675/30252335-e8a5ed84-9670-11e7-82e3-5251efe59954.png">

In the rendered code these buttons have the `.pull-right` class. I searched in the project to find any reference of this class but this class is only used in the `stats` container that is inside `package-card` (`lib/package-card.js:74:56`). In dev mode this class is not added. 

Is it possible that there is any other package adding the class to the buttons?

### Steps to Reproduce

1. Open Atom
2. Open Updates in the Settings View
3. If there are not updates open the developer tools.
4. Inspect the Check for updates button and display the Update button.

**Expected behavior:** Between these buttons there should be an space.

**Actual behavior:** There is not any space between them.

**Reproduces how often:** Always

### Versions
I have a clean installation of Atom in a Macbook Pro 13" (macOS Sierra 10.12.6)

Atom version

```
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

apm version

```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0
```
### Additional Information

This is my `config.cson`

```
"*":
  core:
    disabledPackages: [
      "spell-check"
      "styleguide"
      "welcome"
    ]
    telemetryConsent: "limited"
  "exception-reporting":
    userId: 
  welcome:
    showOnStartup: false
```

**Comment by 50Wliu** [comment]
It's showing correctly locally because I've already fixed this :).  Should be out in Atom 1.21.0.
