### ISSUE TITLE
preferences open two settings tabs

### ISSUE THREAD

**Issue by unluisco** [atom/settings-view#994]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I clic preferences, that open two settings tabs.
Also happen the same with the preferences option in menubar in safe mode.

pd. sorry for my english.

### Steps to Reproduce

1. clic preferences option
2. two settings tabs are opened

**Expected behavior:** Only one tab should be opened

**Actual behavior:** two tabs are opened

**Reproduces how often:** always

### Versions
atom --version
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1

Macbook pro mid 2012
macOS Sierra 10.12.6

### Additional Information

I record this gif:
![settings](https://user-images.githubusercontent.com/6332263/30391846-800c63fe-9880-11e7-99bb-bb26086fcf4a.gif)

**Comment by rsese** [comment]
Thanks for the report!  

> Also happen the same with the preferences option in menubar in safe mode.

Atom doesn't come with a menu bar like that by default and running in safe mode disables all community packages so I'm not sure how you're using the menu bar in safe mode?

Can you share another GIF showing the issue you're seeing after starting Atom with `atom --safe`?

**Comment by unluisco** [comment]
Thank you @rsese for your help,
Here is:
![safe mode](https://user-images.githubusercontent.com/6332263/30431151-555d30cc-9923-11e7-8e4e-72eecfb8d478.gif)

**Comment by rsese** [comment]
Hmmm, did you start seeing this only after updating to `1.20.0`?

Also, can you temporarily reset to factory defaults and see if the behavior is still the same?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by unluisco** [comment]
No, it's something that's been happening a while ago.

Ok, here is:
![factory](https://user-images.githubusercontent.com/6332263/30508854-6b257da8-9a66-11e7-94c9-d2740572148b.gif)

**Comment by rsese** [comment]
Does <kbd>cmd+,</kbd> also open 2 Settings tabs?

> No, it's something that's been happening a while ago.

Do you remember the oldest version of Atom where you remember seeing this?

**Comment by unluisco** [comment]
with `cmd+,` works fine.

I remember that been happening since version 1.18

**Comment by rsese** [comment]
Is it just preferences that opens a second instance or do any other menu items do the same thing (like `Atom > About Atom` for example)?

**Comment by unluisco** [comment]
This is something curious.

![about](https://user-images.githubusercontent.com/6332263/30718160-b2eadf98-9ee4-11e7-9328-a8ff7f2a7aff.gif)

I also think it's important to mention that when the two preference windows are opened, one of them opens in the Themes category.

![themes](https://user-images.githubusercontent.com/6332263/30718244-efd42108-9ee4-11e7-9d18-2286245c87b1.gif)

**Comment by 50Wliu** [comment]
Do you have anything in your `~/.atom/init.coffee`?

**Comment by unluisco** [comment]
Thank you @50Wliu.

It was the first thing I thought before reporting it, but I checked the script and got nothing.

Also when I reset to factory everything is restarted.

> Also, can you temporarily reset to factory defaults and see if the behavior is still the same?
> http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by 50Wliu** [comment]
Ah, I missed that comment, sorry!

**Comment by unluisco** [comment]
Maybe this message has something to do?

![settings](https://user-images.githubusercontent.com/6332263/30768470-6c794d80-9fcd-11e7-8786-debbfbda4a7f.png)

**Comment by rsese** [comment]
Wow this one is so weird - I don't *think* that message is related but I guess one thing we may not have tried yet is clearing saved state?  Please save any unsaved work first as mentioned in the documentation:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by unluisco** [comment]
Yes, that works.

Now is working fine.
Thank you very much Robert

**Comment by rsese** [comment]
Oh great, glad that fixed things for you.

Just a guess, but maybe you somehow got in a state where you had multiple settings views opened (looks like it's been talked about a bit before /cc https://github.com/atom/settings-view/issues/506) and that state got saved?  Then every time you opened settings view, that state was being loaded and deleting saved state was needed to clear it up.

Going go go ahead and close this since it's no longer a problem for you :v:
