### ISSUE TITLE
Flaky test: it displays the snippets registered by the package

### ISSUE THREAD

**Issue by 50Wliu** [atom/settings-view#998]
Seen at https://ci.appveyor.com/project/Atom/settings-view/build/333/job/2l23nc4778c2is7h.  Similar to, but not exactly the same as, #973.

```
InstalledPackageView
  it displays the snippets registered by the package
    timeout: timed out after 60000 msec waiting for snippets to load
```

**Comment by 50Wliu** [comment]
So uh, I added that waitsFor to _fix_ #973.  I also just stress-tested the spec 1000 times and it didn't fail, so not sure what's going on here :/.

**Comment by maxbrunsfeld** [comment]
It just happened again: https://circleci.com/gh/atom/atom/6275.
